// packages/react-native/src/components/Attachment.tsx
import type { IconName } from '@ghds/icons';
import { useTheme } from '@shopify/restyle';
import { Pressable } from 'react-native';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box, Text } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';
import { Icon } from './Icon.js';

/** Props for {@link Attachment}. */
export interface AttachmentProps {
  /** File (or resource) name shown as the primary label. */
  name: string;
  /** Secondary metadata, e.g. a human-readable size like `"2.4 MB"`. */
  meta?: string;
  /** Optional leading icon (a `@ghds/icons` name). */
  icon?: IconName;
  /** When provided, renders a remove button that calls this handler. */
  onRemove?: () => void;
  /** Accessible label for the remove button. Defaults to `Remove {name}`. */
  removeLabel?: string;
  /** Test handle for queries. */
  testID?: string;
}

/**
 * A hand-drawn attachment chip: an optional leading icon, a file name with
 * optional metadata, and an optional remove button. The sketchy box comes from
 * `@ghds/sketch-core`; every colour, padding, radius and sketch parameter comes
 * from `@ghds/tokens` (`comp.attachment.*`) via the Restyle theme.
 */
export function Attachment({ name, meta, icon, onRemove, removeLabel, testID }: AttachmentProps) {
  const theme = useTheme<Theme>();

  const { onLayout, size, drawable } = useSketch({
    inset: theme.borderWidths.default,
    roughness: theme.attachmentSketch.roughness,
    bowing: theme.attachmentSketch.bowing,
    fillStyle: 'solid',
  });

  return (
    <Box
      onLayout={onLayout}
      flexDirection="row"
      alignItems="center"
      alignSelf="flex-start"
      gap="attachmentGap"
      paddingHorizontal="attachmentHorizontal"
      paddingVertical="attachmentVertical"
      borderRadius="attachment"
      testID={testID}
    >
      <SketchBackground
        drawable={drawable}
        size={size}
        strokeColor={theme.colors.attachmentStrokeDefault}
        fillColor={theme.colors.attachmentBgDefault}
        strokeWidth={theme.borderWidths.default}
      />
      {icon !== undefined ? (
        <Icon name={icon} size="sm" color={theme.colors.attachmentIconDefault} />
      ) : null}
      <Box flexDirection="column">
        <Text variant="label" color="attachmentTextName">
          {name}
        </Text>
        {meta !== undefined ? (
          <Text variant="caption" color="attachmentTextMeta">
            {meta}
          </Text>
        ) : null}
      </Box>
      {onRemove !== undefined ? (
        <Pressable
          onPress={onRemove}
          accessibilityRole="button"
          accessibilityLabel={removeLabel ?? `Remove ${name}`}
        >
          <Icon name="close" size="sm" color={theme.colors.attachmentIconDefault} />
        </Pressable>
      ) : null}
    </Box>
  );
}

// packages/web-components/src/components/attachment.ts
import type { IconName } from '@ghds/icons';
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';
import './icon.js';

/**
 * `<gh-attachment>` — a hand-drawn attachment chip.
 *
 * Shows an optional leading icon, a file `name` with optional `meta` (e.g. a
 * size), and, when `removable`, a close button that emits a `gh-remove`
 * `CustomEvent`. The sketchy box (outline from `@ghds/sketch-core` over a
 * token-driven fill) and every colour, padding, radius and sketch parameter come
 * from `comp.attachment.*` tokens.
 */
@customElement('gh-attachment')
export class GhAttachment extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
      }

      .attachment {
        position: relative;
        display: inline-flex;
        align-items: center;
        gap: var(--comp-attachment-gap);
        box-sizing: border-box;
        padding: var(--comp-attachment-padding-vertical) var(--comp-attachment-padding-horizontal);
        background: var(--comp-attachment-bg-default);
        border-radius: var(--comp-attachment-radius);
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-attachment-stroke-default);
        font-family: var(--sys-typography-body-fontFamily);
      }

      .icon {
        position: relative;
        display: inline-flex;
        color: var(--comp-attachment-icon-default);
      }

      .text {
        position: relative;
        display: inline-flex;
        flex-direction: column;
        min-width: 0;
      }

      .name {
        color: var(--comp-attachment-text-name);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
      }

      .meta {
        color: var(--comp-attachment-text-meta);
        font-family: var(--sys-typography-caption-fontFamily);
        font-size: var(--sys-typography-caption-fontSize);
        font-weight: var(--sys-typography-caption-fontWeight);
        line-height: var(--sys-typography-caption-lineHeight);
      }

      .remove {
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        padding: 0;
        border: none;
        background: transparent;
        color: var(--comp-attachment-icon-default);
        cursor: pointer;
      }

      .remove:focus-visible {
        outline: var(--sys-border-width-thick) solid var(--sys-color-border-focus);
        outline-offset: var(--sys-spacing-xs);
        border-radius: var(--sys-radius-sm);
      }
    `,
  ];

  /** File (or resource) name shown as the primary label. */
  @property({ type: String }) name = '';
  /** Secondary metadata, e.g. a human-readable size like `"2.4 MB"`. */
  @property({ type: String }) meta?: string;
  /** Optional leading icon (a `@ghds/icons` name). */
  @property({ type: String }) icon?: string;
  /** When true, renders a remove button that emits `gh-remove`. */
  @property({ type: Boolean, reflect: true }) removable = false;

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.attachment.sketch.roughness,
      bowing: tokens.comp.attachment.sketch.bowing,
    };
  }

  private readonly handleRemove = (): void => {
    this.dispatchEvent(new CustomEvent('gh-remove', { bubbles: true, composed: true }));
  };

  protected override render(): unknown {
    return html`<div class="attachment" part="attachment">
      ${this.renderSketch()}
      ${
        this.icon
          ? html`<span class="icon"
            ><gh-icon name=${this.icon as IconName} size="sm"></gh-icon
          ></span>`
          : nothing
      }
      <span class="text">
        <span class="name">${this.name}</span>
        ${this.meta !== undefined ? html`<span class="meta">${this.meta}</span>` : nothing}
      </span>
      ${
        this.removable
          ? html`<button
            class="remove"
            type="button"
            aria-label=${`Remove ${this.name}`}
            @click=${this.handleRemove}
          >
            <gh-icon name="close" size="sm"></gh-icon>
          </button>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-attachment': GhAttachment;
  }
}
