// packages/react-native/src/components/Avatar.tsx
import { useTheme } from '@shopify/restyle';
import { useState } from 'react';
import { Image, type ImageStyle } from 'react-native';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box, Text } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';

/** Rendered diameter of an {@link Avatar}. */
export type AvatarSize = 'sm' | 'md' | 'lg';

/** Props for {@link Avatar}. */
export interface AvatarProps {
  /** Image URI. Falls back to initials (then an empty circle) on load failure. */
  src?: string;
  /** Name — used for the accessible label and the initials fallback. */
  name?: string;
  /** Overrides the accessible label (defaults to `name`). */
  alt?: string;
  /** Rendered diameter. Defaults to `'md'`. */
  size?: AvatarSize;
  /** Test handle for queries. */
  testID?: string;
}

/** First letters of the first and last whitespace-separated words, uppercased. */
export function initialsFrom(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) {
    return '';
  }
  const first = parts[0]?.charAt(0) ?? '';
  const last = parts.length > 1 ? (parts.at(-1)?.charAt(0) ?? '') : '';
  return (first + last).toUpperCase();
}

const IMAGE_STYLE: ImageStyle = { width: '100%', height: '100%' };

/**
 * A hand-drawn circular avatar. Shows an image when `src` loads, otherwise the
 * initials derived from `name`, otherwise an empty sketched circle. The sketchy
 * ellipse outline comes from `@ghds/sketch-core` (rendered with
 * `react-native-svg`); every colour, size and sketch parameter is sourced from
 * `@ghds/tokens` via the Restyle theme (`comp.avatar.*`).
 */
export function Avatar({ src, name, alt, size = 'md', testID }: AvatarProps) {
  const theme = useTheme<Theme>();
  // Track *which* src failed rather than a sticky boolean, so a new `src` is
  // retried instead of being stranded behind the initials fallback forever.
  const [failedSrc, setFailedSrc] = useState<string | undefined>(undefined);

  const {
    onLayout,
    size: measured,
    drawable,
  } = useSketch({
    shape: 'ellipse',
    inset: theme.borderWidths.default,
    roughness: theme.avatarSketch.roughness,
    bowing: theme.avatarSketch.bowing,
  });

  const dimension = theme.avatarSizes[size];
  const label = alt ?? name;
  const showImage = src !== undefined && failedSrc !== src;

  return (
    <Box
      onLayout={onLayout}
      alignItems="center"
      justifyContent="center"
      backgroundColor="avatarBg"
      style={{
        width: dimension,
        height: dimension,
        borderRadius: dimension / 2,
        overflow: 'hidden',
      }}
      testID={testID}
      accessibilityRole={label ? 'image' : undefined}
      accessibilityLabel={label}
    >
      <SketchBackground
        drawable={drawable}
        size={measured}
        strokeColor={theme.colors.avatarStroke}
        strokeWidth={theme.borderWidths.default}
      />
      {showImage ? (
        <Image
          source={{ uri: src }}
          onError={() => setFailedSrc(src)}
          style={IMAGE_STYLE}
          // Decorative: the container Box already carries the accessible name,
          // so the image must not create a second node announcing it again.
          accessible={false}
          accessibilityLabel=""
        />
      ) : (
        <Text variant="label" color="avatarText">
          {name ? initialsFrom(name) : ''}
        </Text>
      )}
    </Box>
  );
}

// packages/web-components/src/components/avatar.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { ellipse } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, type PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Rendered diameter of a `<gh-avatar>`. */
export type GhAvatarSize = 'sm' | 'md' | 'lg';

/**
 * `<gh-avatar>` — a hand-drawn circular avatar.
 *
 * Shows an image when `src` loads, otherwise the initials derived from `name`,
 * otherwise an empty sketched circle. The sketchy ellipse outline comes from
 * `@ghds/sketch-core`; every colour, size and sketch parameter is token-driven
 * (`comp.avatar.*`). Exposed to assistive tech as an `img` with `name`/`alt`.
 */
@customElement('gh-avatar')
export class GhAvatar extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
        --_avatar-size: var(--comp-avatar-size-md);
        width: var(--_avatar-size);
        height: var(--_avatar-size);
      }

      :host([size='sm']) {
        --_avatar-size: var(--comp-avatar-size-sm);
      }

      :host([size='lg']) {
        --_avatar-size: var(--comp-avatar-size-lg);
      }

      .avatar {
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        box-sizing: border-box;
        width: 100%;
        height: 100%;
        overflow: hidden;
        border-radius: var(--sys-radius-pill);
        background: var(--comp-avatar-bg);
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-avatar-stroke);
        user-select: none;
      }

      .initials {
        position: relative;
        color: var(--comp-avatar-text);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
      }

      :host([size='sm']) .initials {
        font-size: var(--sys-typography-caption-fontSize);
      }

      :host([size='lg']) .initials {
        font-size: var(--sys-typography-body-fontSize);
      }

      img {
        position: relative;
        width: 100%;
        height: 100%;
        object-fit: cover;
        border-radius: inherit;
      }
    `,
  ];

  /** Rendered diameter. */
  @property({ type: String, reflect: true }) size: GhAvatarSize = 'md';
  /** Image URL. Falls back to initials, then an empty circle, on load failure. */
  @property({ type: String }) src = '';
  /** Name — used for the accessible label and the initials fallback. */
  @property({ type: String }) name = '';
  /** Overrides the accessible label (defaults to `name`). */
  @property({ type: String }) alt = '';

  @state() private imageFailed = false;

  private readonly internals: ElementInternals = this.attachInternals();

  private get initials(): string {
    const name = this.name.trim();
    if (!name) {
      return '';
    }
    const parts = name.split(/\s+/).filter(Boolean);
    const first = parts[0]?.charAt(0) ?? '';
    const last = parts.length > 1 ? (parts.at(-1)?.charAt(0) ?? '') : '';
    return (first + last).toUpperCase();
  }

  protected override willUpdate(changed: PropertyValues): void {
    // Retry a new image instead of stranding it behind the fallback: a fresh
    // `src` clears a prior load failure.
    if (changed.has('src')) {
      this.imageFailed = false;
    }
  }

  protected override updated(): void {
    const label = this.alt || this.name;
    if (label) {
      this.internals.role = 'img';
      this.internals.ariaLabel = label;
    } else {
      this.internals.role = null;
      this.internals.ariaLabel = null;
    }
  }

  private readonly handleError = (): void => {
    this.imageFailed = true;
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return ellipse(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.avatar.sketch.roughness,
      bowing: tokens.comp.avatar.sketch.bowing,
    };
  }

  protected override render(): unknown {
    const showImage = this.src !== '' && !this.imageFailed;
    return html`<span class="avatar" part="avatar">
      ${this.renderSketch()}
      ${
        showImage
          ? html`<img src=${this.src} alt="" @error=${this.handleError} />`
          : html`<span class="initials" aria-hidden="true">${this.initials}</span>`
      }
    </span>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-avatar': GhAvatar;
  }
}
