// packages/react/src/components/Bubble.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Who sent the message a {@link Bubble} holds. */
export type BubbleVariant = 'received' | 'sent';

export interface BubbleProps extends HTMLAttributes<HTMLDivElement> {
  /**
   * `'received'` (default) is a muted incoming bubble; `'sent'` is a filled
   * outgoing bubble in the primary colour.
   */
  variant?: BubbleVariant;
}

const bubble = tokens.comp.bubble;
const c = cssVars.comp.bubble;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

/**
 * A hand-drawn chat bubble. The sketchy rounded box (outline + fill) comes from
 * `@ghds/sketch-core`; colour, padding, radius and sketch parameters come from
 * `@ghds/tokens` (`comp.bubble.*`). Alignment within a conversation is the
 * caller's concern (see {@link Message}); the bubble only paints itself.
 */
export const Bubble = forwardRef<HTMLDivElement, BubbleProps>(function Bubble(
  { variant = 'received', children, style, ...rest },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: bubble.sketch.roughness,
    bowing: bubble.sketch.bowing,
    inset: INSET,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-block',
    boxSizing: 'border-box',
    maxWidth: '100%',
    padding: `${bubble.padding.vertical} ${bubble.padding.horizontal}`,
    color: c.text[variant],
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    fontWeight: tokens.sys.typography.body.fontWeight,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
    ...style,
  };

  return (
    <div ref={ref} style={rootStyle} {...rest}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke[variant]}
        strokeWidth={STROKE_WIDTH}
        fillColor={c.bg[variant]}
        fillRendering="fill"
      />
      <span style={{ position: 'relative' }}>{children}</span>
    </div>
  );
});

// packages/web-components/src/components/bubble.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Who sent the message a `<gh-bubble>` holds. */
export type GhBubbleVariant = 'received' | 'sent';

/**
 * `<gh-bubble>` — a hand-drawn chat bubble.
 *
 * The sketchy rounded box (outline from `@ghds/sketch-core` over a token-driven
 * fill) frames slotted content. `'received'` (default) is a muted incoming
 * bubble; `'sent'` is a filled outgoing bubble in the primary colour. Alignment
 * within a conversation is the caller's concern (see `<gh-message>`); the bubble
 * only paints itself. Colours come from `comp.bubble.*` tokens.
 */
@customElement('gh-bubble')
export class GhBubble extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        max-width: 100%;
      }

      .bubble {
        position: relative;
        box-sizing: border-box;
        max-width: 100%;
        padding: var(--comp-bubble-padding-vertical) var(--comp-bubble-padding-horizontal);
        background: var(--comp-bubble-bg-received);
        border-radius: var(--comp-bubble-radius);
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-bubble-stroke-received);
      }

      .content {
        position: relative;
        color: var(--comp-bubble-text-received);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        font-weight: var(--sys-typography-body-fontWeight);
        line-height: var(--sys-typography-body-lineHeight);
      }

      :host([variant='sent']) .bubble {
        background: var(--comp-bubble-bg-sent);
        color: var(--comp-bubble-stroke-sent);
      }

      :host([variant='sent']) .content {
        color: var(--comp-bubble-text-sent);
      }
    `,
  ];

  /** Incoming (`'received'`, default) or outgoing (`'sent'`) styling. */
  @property({ type: String, reflect: true }) variant: GhBubbleVariant = 'received';

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.bubble.sketch.roughness,
      bowing: tokens.comp.bubble.sketch.bowing,
    };
  }

  protected override render(): unknown {
    return html`<div class="bubble" part="bubble">
      ${this.renderSketch()}
      <span class="content"><slot></slot></span>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-bubble': GhBubble;
  }
}
