// packages/react/src/components/Checkbox.tsx
import { tokens } from '@ghds/tokens';
import { Label } from '@radix-ui/react-label';
import {
  type ChangeEvent,
  type CSSProperties,
  forwardRef,
  type InputHTMLAttributes,
  useContext,
  useEffect,
  useId,
  useRef,
  useState,
} from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { CheckboxGroupContext } from './CheckboxGroup.js';
import { Icon } from './Icon.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface CheckboxProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  /** Visible label. Associated to the input via Radix `Label` for accessibility. */
  label?: string;
  /**
   * DOM-only tri-state indicator — not a native HTML attribute. Set imperatively
   * on the underlying `<input>` via `element.indeterminate`, matching native
   * checkbox behavior. Purely visual; does not affect `checked`/form value.
   */
  indeterminate?: boolean;
  /** Identifies this checkbox within a `CheckboxGroup`. Ignored standalone. */
  value?: string;
}

const checkbox = tokens.comp.checkbox;
const c = cssVars.comp.checkbox;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
const SIZE = toPx(tokens.comp.checkbox.size);

function resolveColors(checked: boolean, hovered: boolean, disabled: boolean) {
  if (disabled) {
    return {
      stroke: c.stroke.disabled,
      fill: checked ? c.bg.checked.disabled : c.bg.unchecked.disabled,
    };
  }
  return {
    stroke: hovered ? c.stroke.hover : checked ? c.stroke.checked : c.stroke.default,
    fill: checked ? (hovered ? c.bg.checked.hover : c.bg.checked.default) : c.bg.unchecked.default,
  };
}

/**
 * A hand-drawn checkbox. The sketchy box comes from `@ghds/sketch-core` (via
 * {@link useSketch}); the check/indeterminate mark reuses the existing `Icon`
 * component (`check`/`minus`) rather than inventing new glyph geometry. A real
 * `<input type="checkbox">` carries all native keyboard/focus/form behavior;
 * the sketch box and mark are purely decorative (`aria-hidden`).
 *
 * Works controlled (`checked`/`onChange`) or uncontrolled (`defaultChecked`),
 * like a native input. Inside a `CheckboxGroup`, `checked` is derived from the
 * group's `value` array via `value` — the group's own `onValueChange` still
 * fires alongside any `onChange` passed directly to this Checkbox.
 */
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  {
    label,
    indeterminate = false,
    value,
    checked,
    defaultChecked,
    disabled = false,
    style,
    onMouseEnter,
    onMouseLeave,
    onFocus,
    onBlur,
    onChange,
    id,
    ...rest
  },
  forwardedRef,
) {
  const reactId = useId();
  const inputId = id ?? reactId;
  const group = useContext(CheckboxGroupContext);

  const [hovered, setHovered] = useState(false);
  const [focused, setFocused] = useState(false);
  const [internalChecked, setInternalChecked] = useState(defaultChecked ?? false);
  const [internalIndeterminate, setInternalIndeterminate] = useState(indeterminate);
  const inputRef = useRef<HTMLInputElement>(null);

  const groupChecked = group && value !== undefined ? group.value.includes(value) : undefined;
  const isChecked = groupChecked ?? checked ?? internalChecked;
  const isDisabled = disabled || group?.disabled === true;

  // Mirrors native checkbox activation: clicking clears `indeterminate`, so we
  // track it as internal state (like `internalChecked`) rather than trusting
  // the `indeterminate` prop to still match the real DOM property after a click.
  useEffect(() => {
    setInternalIndeterminate(indeterminate);
  }, [indeterminate]);

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = internalIndeterminate;
    }
  }, [internalIndeterminate]);

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    shape: 'rectangle',
    roughness: checkbox.sketch.roughness,
    bowing: checkbox.sketch.bowing,
    fillStyle: 'solid',
    inset: INSET,
  });

  const colors = resolveColors(isChecked, hovered, isDisabled);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    const next = event.target.checked;
    if (group && value !== undefined) {
      const nextValue = next ? [...group.value, value] : group.value.filter((v) => v !== value);
      group.onValueChange(nextValue);
    } else if (checked === undefined) {
      setInternalChecked(next);
    }
    setInternalIndeterminate(false);
    onChange?.(event);
  };

  const fieldStyle: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: checkbox.gap,
    fontFamily: tokens.sys.typography.body.fontFamily,
    cursor: isDisabled ? 'not-allowed' : 'pointer',
  };

  const boxStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    width: SIZE,
    height: SIZE,
    flexShrink: 0,
    outline: focused ? `${STROKE_WIDTH}px solid ${c.stroke.focus}` : 'none',
    outlineOffset: tokens.sys.spacing.xs,
    ...style,
  };

  const inputStyle: CSSProperties = {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    margin: 0,
    opacity: 0,
    cursor: isDisabled ? 'not-allowed' : 'pointer',
  };

  const labelStyle: CSSProperties = {
    color: isDisabled ? c.text.disabled : c.text.label,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
  };

  const ref = mergeRefs(sketchRef, inputRef, forwardedRef);

  return (
    <span style={fieldStyle}>
      <span style={boxStyle}>
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={colors.stroke}
          strokeWidth={STROKE_WIDTH}
          fillColor={colors.fill}
          fillRendering="fill"
        />
        {(isChecked || internalIndeterminate) && (
          <Icon
            name={internalIndeterminate ? 'minus' : 'check'}
            size="sm"
            style={{ color: c.mark }}
          />
        )}
        <input
          ref={ref}
          type="checkbox"
          id={inputId}
          checked={isChecked}
          disabled={isDisabled}
          style={inputStyle}
          onChange={handleChange}
          onMouseEnter={(event) => {
            setHovered(true);
            onMouseEnter?.(event);
          }}
          onMouseLeave={(event) => {
            setHovered(false);
            onMouseLeave?.(event);
          }}
          onFocus={(event) => {
            setFocused(true);
            onFocus?.(event);
          }}
          onBlur={(event) => {
            setFocused(false);
            onBlur?.(event);
          }}
          {...rest}
        />
      </span>
      {label !== undefined && (
        <Label htmlFor={inputId} style={labelStyle}>
          {label}
        </Label>
      )}
    </span>
  );
});

// packages/web-components/src/components/checkbox.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import './icon.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/**
 * `<gh-checkbox>` — a hand-drawn checkbox.
 *
 * The sketchy box comes from `@ghds/sketch-core` (filled solid when checked);
 * the check/indeterminate mark reuses `<gh-icon>` rather than inventing new
 * glyph geometry. A real `<input type="checkbox">` in the shadow DOM carries
 * all native keyboard/click behavior; `ElementInternals` bridges its boolean
 * state to real `<form>` participation (form value present only when checked,
 * matching native `<input type="checkbox">` submission semantics) and exposes
 * `:state(checked)`/`:state(indeterminate)` for consumers to style by.
 */
@customElement('gh-checkbox')
export class GhCheckbox extends SketchyBase {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...SketchyBase.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
        align-items: center;
        gap: var(--comp-checkbox-gap);
        color: var(--comp-checkbox-stroke-default);
        cursor: pointer;
      }

      :host(:hover) {
        color: var(--comp-checkbox-stroke-hover);
      }

      :host([checked]) {
        color: var(--comp-checkbox-stroke-checked);
        --ghds-sketch-fill-color: var(--comp-checkbox-bg-checked-default);
      }

      :host([checked]:hover) {
        --ghds-sketch-fill-color: var(--comp-checkbox-bg-checked-hover);
      }

      :host(:not([checked])) {
        --ghds-sketch-fill-color: var(--comp-checkbox-bg-unchecked-default);
      }

      :host([disabled]) {
        color: var(--comp-checkbox-stroke-disabled);
        cursor: not-allowed;
      }

      :host([disabled][checked]) {
        --ghds-sketch-fill-color: var(--comp-checkbox-bg-checked-disabled);
      }

      :host([disabled]:not([checked])) {
        --ghds-sketch-fill-color: var(--comp-checkbox-bg-unchecked-disabled);
      }

      .box {
        position: relative;
        box-sizing: border-box;
        width: var(--comp-checkbox-size);
        height: var(--comp-checkbox-size);
        flex-shrink: 0;
        display: inline-flex;
        align-items: center;
        justify-content: center;
      }

      .box:focus-within {
        outline: var(--sys-border-width-default) solid var(--comp-checkbox-stroke-focus);
        outline-offset: var(--sys-spacing-xs);
      }

      gh-icon {
        position: relative;
        color: var(--comp-checkbox-mark);
      }

      input {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        margin: 0;
        opacity: 0;
        cursor: inherit;
      }

      label {
        color: var(--comp-checkbox-text-label);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
      }

      :host([disabled]) label {
        color: var(--comp-checkbox-text-disabled);
      }
    `,
  ];

  /** Checked state. */
  @property({ type: Boolean, reflect: true }) checked = false;
  /** Tri-state visual indicator. Does not affect the submitted form value. */
  @property({ type: Boolean, reflect: true }) indeterminate = false;
  /** Disables interaction and form participation. */
  @property({ type: Boolean, reflect: true }) disabled = false;
  /** Submitted control name. */
  @property({ type: String }) name = '';
  /** Submitted value when checked. */
  @property({ type: String }) value = 'on';
  /** Optional visible label, also the accessible name. */
  @property({ type: String }) label = '';

  @query('.box') private boxEl!: HTMLDivElement;
  @query('input') private inputEl!: HTMLInputElement;

  private readonly internals: ElementInternals = this.attachInternals();
  private readonly checkboxId = `gh-checkbox-${Math.random().toString(36).slice(2)}`;

  protected override get frame(): HTMLElement {
    return this.boxEl ?? this;
  }

  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.checkbox.sketch.roughness,
      bowing: tokens.comp.checkbox.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override firstUpdated(): void {
    super.firstUpdated();
    if (this.inputEl) {
      this.inputEl.indeterminate = this.indeterminate;
    }
    this.syncFormState();
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('indeterminate') && this.inputEl) {
      this.inputEl.indeterminate = this.indeterminate;
    }
    if (
      changed.has('checked') ||
      changed.has('indeterminate') ||
      changed.has('value') ||
      changed.has('disabled')
    ) {
      this.syncFormState();
    }
  }

  private syncFormState(): void {
    this.internals.setFormValue(this.checked ? this.value : null);
    // `ElementInternals.states` (CustomStateSet) isn't implemented in every
    // environment yet (e.g. jsdom) — guard so this degrades gracefully rather
    // than throwing where it's unsupported.
    this.internals.states?.delete('checked');
    this.internals.states?.delete('indeterminate');
    if (this.checked) {
      this.internals.states?.add('checked');
    }
    if (this.indeterminate) {
      this.internals.states?.add('indeterminate');
    }
  }

  private readonly handleChange = (): void => {
    this.checked = this.inputEl.checked;
    // Mirrors native checkbox activation: clicking clears `indeterminate`, so
    // our reflected property and the shadow `<input>`'s real DOM property
    // (already cleared by the browser) stay in sync.
    this.indeterminate = false;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
  };

  formResetCallback(): void {
    this.checked = false;
  }

  formDisabledCallback(disabled: boolean): void {
    this.disabled = disabled;
  }

  formStateRestoreCallback(state: string | File | FormData | null): void {
    this.checked = typeof state === 'string';
  }

  protected override render(): unknown {
    return html`<div class="box">
        ${this.renderSketch()}
        ${
          this.checked || this.indeterminate
            ? html`<gh-icon name=${this.indeterminate ? 'minus' : 'check'} size="sm"></gh-icon>`
            : nothing
        }
        <input
          id=${this.checkboxId}
          type="checkbox"
          .checked=${this.checked}
          aria-label=${this.label ? nothing : this.getAttribute('aria-label') || nothing}
          ?disabled=${this.disabled}
          @change=${this.handleChange}
        />
      </div>
      ${this.label ? html`<label for=${this.checkboxId}>${this.label}</label>` : nothing}`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-checkbox': GhCheckbox;
  }
}
