// packages/react/src/components/CheckboxGroup.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, createContext, type ReactNode } from 'react';

export interface CheckboxGroupContextValue {
  readonly value: string[];
  readonly onValueChange: (value: string[]) => void;
  readonly disabled?: boolean;
}

/** Internal — read by `Checkbox` when rendered inside a `CheckboxGroup`. */
export const CheckboxGroupContext = createContext<CheckboxGroupContextValue | null>(null);

export interface CheckboxGroupProps {
  /** Currently checked values. */
  value: string[];
  onValueChange: (value: string[]) => void;
  /** Accessible name for the group (exposed via `aria-label`). */
  label?: string;
  /** Direction to stack child checkboxes. Defaults to `'column'`. */
  layout?: 'row' | 'column';
  /** Disables every checkbox in the group. */
  disabled?: boolean;
  children: ReactNode;
}

/**
 * Groups related `Checkbox` controls, managing a shared `value: string[]`.
 * Unlike `RadioGroup`, checkboxes are independently selectable — this is a
 * layout + native `<fieldset>`/`<legend>` grouping plus shared state, not a
 * mutual-exclusivity mechanism. A `Checkbox` given a `value` prop reads
 * `checked`/emits changes through this context; without a surrounding group,
 * `Checkbox` works exactly like a standalone native checkbox.
 */
export function CheckboxGroup({
  value,
  onValueChange,
  label,
  layout = 'column',
  disabled,
  children,
}: CheckboxGroupProps) {
  const fieldsetStyle: CSSProperties = {
    border: 'none',
    margin: 0,
    padding: 0,
  };

  const listStyle: CSSProperties = {
    display: 'flex',
    flexDirection: layout === 'row' ? 'row' : 'column',
    gap: tokens.sys.spacing.sm,
  };

  return (
    <fieldset style={fieldsetStyle}>
      {label !== undefined && <legend>{label}</legend>}
      <div style={listStyle}>
        <CheckboxGroupContext.Provider value={{ value, onValueChange, disabled }}>
          {children}
        </CheckboxGroupContext.Provider>
      </div>
    </fieldset>
  );
}

// packages/web-components/src/components/checkbox-group.ts
import { css, html, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/**
 * `<gh-checkbox-group>` — a presentational grouping wrapper for slotted
 * `<gh-checkbox>` elements. Unlike `<gh-radio-group>`, checkboxes are
 * independently selectable, so this element does not manage shared state or
 * mutual exclusivity — it only provides layout and an accessible group name
 * (via `<fieldset>`/`<legend>`). Each slotted `<gh-checkbox>` manages its own
 * `checked`/`name`/`value`.
 */
@customElement('gh-checkbox-group')
export class GhCheckboxGroup extends LitElement {
  static override styles = css`
    fieldset {
      border: none;
      margin: 0;
      padding: 0;
    }

    .list {
      display: flex;
      flex-direction: column;
      gap: var(--sys-spacing-sm);
    }

    :host([layout='row']) .list {
      flex-direction: row;
    }
  `;

  /** Accessible name for the group, rendered as the `<legend>`. */
  @property({ type: String }) label = '';
  /** Direction to stack slotted checkboxes. */
  @property({ type: String, reflect: true }) layout: 'row' | 'column' = 'column';
  /**
   * Disables every slotted `<gh-checkbox>`. Reflected onto the internal
   * `<fieldset>` — the browser's native fieldset-disabling algorithm cascades
   * `disabled` to form-associated descendants (via `formDisabledCallback`),
   * so no manual propagation into slotted children is needed.
   */
  @property({ type: Boolean, reflect: true }) disabled = false;

  protected override render(): unknown {
    return html`<fieldset ?disabled=${this.disabled}>
      ${this.label ? html`<legend>${this.label}</legend>` : null}
      <div class="list"><slot></slot></div>
    </fieldset>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-checkbox-group': GhCheckboxGroup;
  }
}
