// packages/react/src/components/Command.tsx
import { tokens } from '@ghds/tokens';
import {
  type CSSProperties,
  type KeyboardEvent,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import { cssVars } from '../lib/cssVars.js';
import { toPx } from '../lib/units.js';
import { Icon } from './Icon.js';
import { Modal } from './Modal.js';

/** A single runnable command. */
export interface CommandItem {
  value: string;
  label: string;
  /** Extra terms matched by the filter (not shown). */
  keywords?: string[];
  disabled?: boolean;
}

/** A titled group of {@link CommandItem}s. */
export interface CommandGroup {
  heading: string;
  items: CommandItem[];
}

export interface CommandProps {
  /** The grouped commands. */
  groups: CommandGroup[];
  /** Called with the value of the chosen command. */
  onSelect?: (value: string) => void;
  /** Search input placeholder. */
  placeholder?: string;
  /** Shown when the query matches nothing. */
  emptyMessage?: string;
  /** Accessible label for the palette. */
  'aria-label'?: string;
  /** Focus the search input on mount. Defaults to `true`. */
  autoFocus?: boolean;
}

const command = tokens.comp.command;
const c = cssVars.comp.command;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);

function matches(item: CommandItem, query: string): boolean {
  if (query === '') {
    return true;
  }
  const q = query.toLowerCase();
  return (
    item.label.toLowerCase().includes(q) ||
    (item.keywords ?? []).some((k) => k.toLowerCase().includes(q))
  );
}

/**
 * A hand-drawn command palette: a search input filtering a grouped
 * `role="listbox"`. DOM focus stays on the input (`role="combobox"`) while
 * `aria-activedescendant` drives a roving highlight over the visible commands.
 * ArrowUp/Down move the highlight, Enter runs the highlighted command. Colours
 * come from `@ghds/tokens` (`comp.command.*`). For a modal palette, use
 * {@link CommandDialog}.
 */
export function Command({
  groups,
  onSelect,
  placeholder = 'Type a command or search…',
  emptyMessage = 'No results found.',
  'aria-label': ariaLabel,
  autoFocus = true,
}: CommandProps) {
  const baseId = useId();
  const listboxId = `${baseId}-listbox`;
  const [query, setQuery] = useState('');
  const [highlight, setHighlight] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  // The flat list of visible (matching) commands, with their group headings.
  const visible = useMemo(() => {
    const out: { item: CommandItem; heading: string }[] = [];
    for (const group of groups) {
      for (const item of group.items) {
        if (matches(item, query)) {
          out.push({ item, heading: group.heading });
        }
      }
    }
    return out;
  }, [groups, query]);

  const enabledIndexes = useMemo(
    () =>
      visible
        .map((v, i) => ({ v, i }))
        .filter((x) => !x.v.item.disabled)
        .map((x) => x.i),
    [visible],
  );

  // Keep the highlight on a visible, enabled row as the query changes.
  useEffect(() => {
    setHighlight(enabledIndexes[0] ?? 0);
  }, [enabledIndexes]);

  useEffect(() => {
    if (autoFocus) {
      inputRef.current?.focus();
    }
  }, [autoFocus]);

  const getOptionId = (value: string) => `${baseId}-option-${value}`;

  const move = (direction: 1 | -1) => {
    if (enabledIndexes.length === 0) {
      return;
    }
    const pos = enabledIndexes.indexOf(highlight);
    const startPos = pos === -1 ? 0 : pos;
    const nextPos = (startPos + direction + enabledIndexes.length) % enabledIndexes.length;
    const next = enabledIndexes[nextPos];
    if (next !== undefined) {
      setHighlight(next);
    }
  };

  const run = (item: CommandItem) => {
    if (item.disabled) {
      return;
    }
    onSelect?.(item.value);
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        move(1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        move(-1);
        break;
      case 'Enter': {
        event.preventDefault();
        const entry = visible[highlight];
        if (entry) {
          run(entry.item);
        }
        break;
      }
    }
  };

  const highlightedValue = visible[highlight]?.item.value;

  const rootStyle: CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    width: '100%',
    background: c.bg,
    color: c.text.default,
    fontFamily: tokens.sys.typography.body.fontFamily,
  };

  const inputRowStyle: CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.sys.spacing.sm,
    padding: `${tokens.sys.spacing.sm} ${tokens.sys.spacing.md}`,
    borderBottom: `${STROKE_WIDTH}px solid ${c.input.stroke}`,
    color: c.text.muted,
  };

  const inputStyle: CSSProperties = {
    flex: 1,
    minWidth: 0,
    border: 'none',
    outline: 'none',
    background: 'transparent',
    color: c.text.default,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
  };

  // Track a running index so option ids line up with the flat `visible` list.
  let flatIndex = -1;

  return (
    <div style={rootStyle}>
      <div style={inputRowStyle}>
        <Icon name="search" size="sm" />
        <input
          ref={inputRef}
          type="text"
          role="combobox"
          aria-label={ariaLabel ?? 'Command'}
          aria-expanded="true"
          aria-controls={listboxId}
          aria-activedescendant={
            highlightedValue !== undefined ? getOptionId(highlightedValue) : undefined
          }
          autoComplete="off"
          placeholder={placeholder}
          value={query}
          style={inputStyle}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={handleKeyDown}
        />
      </div>
      <div
        id={listboxId}
        role="listbox"
        aria-label={ariaLabel ?? 'Commands'}
        style={{
          maxHeight: '20rem',
          overflowY: 'auto',
          padding: command.padding,
        }}
      >
        {visible.length === 0 ? (
          <div style={{ padding: tokens.sys.spacing.md, color: c.text.muted, textAlign: 'center' }}>
            {emptyMessage}
          </div>
        ) : (
          groups.map((group) => {
            const groupVisible = group.items.filter((item) => matches(item, query));
            if (groupVisible.length === 0) {
              return null;
            }
            return (
              // biome-ignore lint/a11y/useSemanticElements: this is a listbox option group; a <fieldset> would be invalid inside role="listbox"
              <div key={group.heading} role="group" aria-label={group.heading}>
                <div
                  style={{
                    padding: `${tokens.sys.spacing.xs} ${tokens.sys.spacing.sm}`,
                    color: c.text.muted,
                    fontSize: tokens.sys.typography.caption.fontSize,
                    fontWeight: tokens.sys.typography.label.fontWeight,
                  }}
                >
                  {group.heading}
                </div>
                {groupVisible.map((item) => {
                  flatIndex += 1;
                  const isHighlighted = flatIndex === highlight;
                  const optionStyle: CSSProperties = {
                    display: 'flex',
                    alignItems: 'center',
                    padding: `${tokens.sys.spacing.sm} ${tokens.sys.spacing.sm}`,
                    borderRadius: tokens.sys.radius.sm,
                    cursor: item.disabled ? 'not-allowed' : 'pointer',
                    color: c.text.default,
                    opacity: item.disabled ? 0.5 : 1,
                    background: isHighlighted && !item.disabled ? c.item.selected : 'transparent',
                  };
                  const rowIndex = flatIndex;
                  return (
                    // biome-ignore lint/a11y/useKeyWithClickEvents: keyboard handling lives on the combobox input (aria-activedescendant); options are pointer targets
                    // biome-ignore lint/a11y/useFocusableInteractive: options are never focused — DOM focus stays on the input by design
                    <div
                      key={item.value}
                      id={getOptionId(item.value)}
                      role="option"
                      aria-selected={isHighlighted}
                      aria-disabled={item.disabled || undefined}
                      style={optionStyle}
                      onMouseDown={(e) => e.preventDefault()}
                      onClick={() => run(item)}
                      onMouseEnter={() => !item.disabled && setHighlight(rowIndex)}
                    >
                      {item.label}
                    </div>
                  );
                })}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}

export interface CommandDialogProps extends CommandProps {
  /** Whether the palette is shown. */
  open: boolean;
  /** Called when the dialog requests to close (Escape, scrim click). */
  onClose: () => void;
}

/**
 * A {@link Command} palette in a modal dialog. Reuses {@link Modal} for the
 * portal, scrim, focus trap, Escape-to-close and scroll lock. Selecting a
 * command does not auto-close — call `onClose` from your `onSelect` if desired.
 */
export function CommandDialog({ open, onClose, ...commandProps }: CommandDialogProps) {
  return (
    <Modal open={open} onClose={onClose}>
      <Command {...commandProps} />
    </Modal>
  );
}

// packages/web-components/src/components/command.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** One command-palette entry. */
export interface GhCommandItem {
  value: string;
  label: string;
  group?: string;
  keywords?: string[];
  disabled?: boolean;
}

let commandUid = 0;

/**
 * `<gh-command>` — a hand-drawn command palette (searchable menu).
 *
 * Built on the native `<dialog>` (`showModal()`) for focus trapping and the top
 * layer. A search `<input role="combobox">` filters `items` (by label and
 * `keywords`) into a `role="listbox"`, optionally grouped. Arrow keys move the
 * highlight, Enter runs (dispatches a `command` `CustomEvent<string>`), Escape
 * closes (dispatches `close`). Colours and sketch parameters come from
 * `@ghds/tokens` (`comp.command.*`).
 */
@customElement('gh-command')
export class GhCommand extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        color: var(--comp-command-stroke);
      }

      dialog {
        position: relative;
        box-sizing: border-box;
        width: 100%;
        max-width: 32rem;
        padding: var(--comp-command-padding);
        border: none;
        background: transparent;
        color: var(--comp-command-text-default);
        overflow: visible;
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        line-height: var(--sys-typography-body-lineHeight);
      }

      dialog::backdrop {
        background: var(--sys-color-bg-overlay);
      }

      .search {
        position: relative;
        box-sizing: border-box;
        width: 100%;
        margin: 0 0 var(--sys-spacing-sm);
        padding: var(--sys-spacing-sm);
        border: none;
        border-bottom: var(--sys-border-width-default) solid var(--comp-command-input-stroke);
        outline: none;
        background: transparent;
        color: var(--comp-command-text-default);
        font: inherit;
      }

      .list {
        position: relative;
        display: flex;
        flex-direction: column;
        gap: var(--sys-spacing-xs);
        max-height: 20rem;
        overflow-y: auto;
        list-style: none;
        margin: 0;
        padding: 0;
      }

      .group-label {
        padding: var(--sys-spacing-xs) var(--sys-spacing-sm);
        color: var(--comp-command-text-muted);
        font-size: var(--sys-typography-caption-fontSize);
        text-transform: uppercase;
      }

      .item {
        display: flex;
        align-items: center;
        padding: var(--sys-spacing-xs) var(--sys-spacing-sm);
        border-radius: var(--sys-radius-sm);
        color: var(--comp-command-text-default);
        cursor: pointer;
      }

      .item[aria-disabled='true'] {
        color: var(--sys-color-text-disabled);
        cursor: not-allowed;
      }

      .item.highlighted:not([aria-disabled='true']) {
        background: var(--comp-command-item-hover);
      }

      .empty {
        padding: var(--sys-spacing-md);
        color: var(--comp-command-text-muted);
        text-align: center;
      }

      .sketch-fill {
        fill: var(--comp-command-bg);
        stroke: none;
      }
    `,
  ];

  /** All commands. */
  @property({ attribute: false }) items: GhCommandItem[] = [];
  /** Whether the palette is shown. */
  @property({ type: Boolean, reflect: true }) open = false;
  /** Placeholder for the search field. */
  @property({ type: String }) placeholder = 'Type a command or search…';
  /** Text shown when nothing matches. */
  @property({ type: String }) emptyMessage = 'No results found.';

  @state() private query = '';
  @state() private highlightedValue = '';

  @query('dialog') private dialogEl?: HTMLDialogElement;
  @query('.search') private searchEl?: HTMLInputElement;

  private readonly uid = `gh-command-${commandUid++}`;

  protected override get frame(): HTMLElement {
    return this.dialogEl ?? this;
  }

  private get filtered(): GhCommandItem[] {
    const q = this.query.trim().toLowerCase();
    if (!q) {
      return this.items;
    }
    return this.items.filter((item) => {
      const haystack = [item.label, ...(item.keywords ?? [])].join(' ').toLowerCase();
      return haystack.includes(q);
    });
  }

  private enabled(): GhCommandItem[] {
    return this.filtered.filter((item) => !item.disabled);
  }

  private optionId(value: string): string {
    return `${this.uid}-item-${value}`;
  }

  protected override willUpdate(changed: PropertyValues): void {
    // Reset the search state before render (not in `updated`) so opening the
    // palette doesn't schedule a second update.
    if (changed.has('open') && this.open) {
      this.query = '';
      this.highlightedValue = this.enabled()[0]?.value ?? '';
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (!changed.has('open')) {
      return;
    }
    const dialog = this.dialogEl;
    if (!dialog) {
      return;
    }
    if (this.open && !dialog.open) {
      try {
        dialog.showModal();
      } catch {
        dialog.setAttribute('open', '');
      }
      this.measure();
      this.updateComplete.then(() => this.searchEl?.focus());
    } else if (!this.open && dialog.open) {
      dialog.close();
    }
  }

  private requestClose(): void {
    this.dispatchEvent(new CustomEvent('close', { bubbles: true, composed: true }));
  }

  private moveHighlight(direction: 1 | -1): void {
    const enabled = this.enabled();
    if (enabled.length === 0) {
      return;
    }
    const currentIndex = enabled.findIndex((item) => item.value === this.highlightedValue);
    const nextIndex = (currentIndex + direction + enabled.length) % enabled.length;
    this.highlightedValue = enabled[nextIndex]?.value ?? '';
  }

  private run(value: string): void {
    const item = this.items.find((i) => i.value === value);
    if (!item || item.disabled) {
      return;
    }
    this.dispatchEvent(
      new CustomEvent('command', { detail: value, bubbles: true, composed: true }),
    );
    this.requestClose();
  }

  private readonly onInput = (): void => {
    this.query = this.searchEl?.value ?? '';
    this.highlightedValue = this.enabled()[0]?.value ?? '';
  };

  private readonly onCancel = (event: Event): void => {
    event.preventDefault();
    this.requestClose();
  };

  private readonly onKeydown = (event: KeyboardEvent): void => {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this.moveHighlight(1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.moveHighlight(-1);
        break;
      case 'Enter':
        if (this.highlightedValue) {
          event.preventDefault();
          this.run(this.highlightedValue);
        }
        break;
    }
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.command.sketch.roughness,
      bowing: tokens.comp.command.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    const filtered = this.filtered;
    const listId = `${this.uid}-list`;
    let lastGroup: string | undefined;
    return html`<dialog
      aria-label="Command palette"
      @cancel=${this.onCancel}
      @keydown=${this.onKeydown}
    >
      ${this.renderSketch()}
      <input
        class="search"
        type="text"
        role="combobox"
        autocomplete="off"
        aria-autocomplete="list"
        aria-expanded="true"
        aria-controls=${listId}
        aria-activedescendant=${this.highlightedValue ? this.optionId(this.highlightedValue) : nothing}
        placeholder=${this.placeholder}
        .value=${this.query}
        @input=${this.onInput}
      />
      <ul class="list" id=${listId} role="listbox">
        ${
          filtered.length === 0
            ? html`<li class="empty">${this.emptyMessage}</li>`
            : filtered.map((item) => {
                const heading =
                  item.group && item.group !== lastGroup
                    ? html`<li class="group-label" role="presentation">${item.group}</li>`
                    : nothing;
                lastGroup = item.group;
                return html`${heading}<li
                  id=${this.optionId(item.value)}
                  class=${item.value === this.highlightedValue ? 'item highlighted' : 'item'}
                  role="option"
                  aria-selected=${item.value === this.highlightedValue}
                  aria-disabled=${item.disabled ? 'true' : nothing}
                  @click=${() => this.run(item.value)}
                  @mouseenter=${() => {
                    if (!item.disabled) {
                      this.highlightedValue = item.value;
                    }
                  }}
                >
                  ${item.label}
                </li>`;
              })
        }
      </ul>
    </dialog>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-command': GhCommand;
  }
}
