// packages/react/src/components/HoverCard.tsx
import {
  autoUpdate,
  flip,
  offset,
  type Placement,
  shift,
  useFloating,
} from '@floating-ui/react-dom';
import { tokens } from '@ghds/tokens';
import {
  type CSSProperties,
  cloneElement,
  isValidElement,
  type ReactElement,
  type ReactNode,
  type Ref,
  useEffect,
  useId,
  useRef,
  useState,
} from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface HoverCardProps {
  /** The element that reveals the card on hover / focus. */
  trigger: ReactElement;
  /** Card content. */
  children: ReactNode;
  /** Delay (ms) before opening on hover. Defaults to the `normal` duration. */
  openDelay?: number;
  /** Delay (ms) before closing after leaving. Defaults to the `normal` duration. */
  closeDelay?: number;
  /** Preferred placement. Defaults to `'bottom'`. */
  placement?: Placement;
}

const hoverCard = tokens.comp.hoverCard;
const c = cssVars.comp.hoverCard;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
const DEFAULT_DELAY = Number.parseFloat(tokens.sys.animation.duration.normal);

/**
 * A hand-drawn hover card: a non-modal floating panel that opens when the
 * trigger is hovered (after `openDelay`) or focused, and closes after
 * `closeDelay` once the pointer leaves both the trigger and the card. The
 * trigger is linked to the card via `aria-describedby`. Positioned with
 * `@floating-ui/react-dom`; colours and sketch parameters come from
 * `@ghds/tokens` (`comp.hoverCard.*`).
 */
export function HoverCard({
  trigger,
  children,
  openDelay = DEFAULT_DELAY,
  closeDelay = DEFAULT_DELAY,
  placement = 'bottom',
}: HoverCardProps) {
  const cardId = useId();
  const [open, setOpen] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(
    () => () => {
      if (timerRef.current) {
        clearTimeout(timerRef.current);
      }
    },
    [],
  );

  const { refs, floatingStyles } = useFloating({
    open,
    placement,
    strategy: 'fixed',
    whileElementsMounted: open ? autoUpdate : undefined,
    middleware: [
      offset(toPx(hoverCard.offset)),
      flip(),
      shift({ padding: toPx(tokens.sys.spacing.sm) }),
    ],
  });

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: hoverCard.sketch.roughness,
    bowing: hoverCard.sketch.bowing,
    inset: INSET,
  });

  const clearTimer = () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  };
  const scheduleOpen = () => {
    clearTimer();
    timerRef.current = setTimeout(() => setOpen(true), openDelay);
  };
  const scheduleClose = () => {
    clearTimer();
    timerRef.current = setTimeout(() => setOpen(false), closeDelay);
  };

  if (!isValidElement(trigger)) {
    throw new Error('HoverCard expects a single React element as `trigger`');
  }

  // biome-ignore lint/suspicious/noExplicitAny: merging handlers onto an unknown child element's props
  const triggerProps = trigger.props as any;
  const triggerChildRef = (trigger as { ref?: Ref<unknown> }).ref ?? triggerProps.ref;
  const renderedTrigger = cloneElement(trigger, {
    ref: mergeRefs(refs.setReference, triggerChildRef),
    'aria-describedby': open ? cardId : triggerProps['aria-describedby'],
    onMouseEnter: (e: unknown) => {
      scheduleOpen();
      triggerProps.onMouseEnter?.(e);
    },
    onMouseLeave: (e: unknown) => {
      scheduleClose();
      triggerProps.onMouseLeave?.(e);
    },
    onFocus: (e: unknown) => {
      clearTimer();
      setOpen(true);
      triggerProps.onFocus?.(e);
    },
    onBlur: (e: unknown) => {
      scheduleClose();
      triggerProps.onBlur?.(e);
    },
    // biome-ignore lint/suspicious/noExplicitAny: cloneElement props for an unknown child type
  } as any);

  const cardStyle: CSSProperties = {
    ...floatingStyles,
    ...sketchHostStyle,
    display: open ? 'block' : 'none',
    zIndex: tokens.sys.zIndex.overlay,
    boxSizing: 'border-box',
    minWidth: '12rem',
    maxWidth: '20rem',
    padding: `${hoverCard.padding.vertical} ${hoverCard.padding.horizontal}`,
    color: c.text,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
  };

  return (
    <>
      {renderedTrigger}
      {/* biome-ignore lint/a11y/noStaticElementInteractions: pointer handlers only keep the non-modal card open while hovered; it holds no interactive role of its own */}
      <div
        ref={mergeRefs(refs.setFloating, sketchRef)}
        id={cardId}
        style={cardStyle}
        onMouseEnter={clearTimer}
        onMouseLeave={scheduleClose}
      >
        {open && (
          <SketchSurface
            drawable={drawable}
            width={size.width}
            height={size.height}
            strokeColor={c.stroke}
            strokeWidth={STROKE_WIDTH}
            fillColor={c.bg}
            fillRendering="fill"
            shadowColor={c.stroke}
          />
        )}
        <div style={{ position: 'relative' }}>{children}</div>
      </div>
    </>
  );
}

// packages/web-components/src/components/hover-card.ts
import { computePosition, flip, offset, shift } from '@floating-ui/dom';
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

let hoverCardUid = 0;

/**
 * `<gh-hover-card>` — a hand-drawn hover card.
 *
 * Wraps a focusable trigger (slot `trigger`) and reveals a floating panel of
 * rich content (default slot) on hover (after `delay`) or focus, hiding on
 * leave / blur / Escape. Positioned with `@floating-ui/dom`; the trigger is
 * linked to the panel via `aria-describedby`. Colours, padding and sketch
 * parameters come from `@ghds/tokens` (`comp.hoverCard.*`).
 */
@customElement('gh-hover-card')
export class GhHoverCard extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        color: var(--comp-hoverCard-stroke);
      }

      .trigger {
        display: inline-flex;
        cursor: pointer;
        color: inherit;
      }

      .trigger:focus-visible {
        outline: var(--sys-border-width-thick) solid var(--comp-hoverCard-stroke);
        outline-offset: var(--sys-spacing-xs);
      }

      .panel {
        position: fixed;
        left: 0;
        top: 0;
        z-index: var(--sys-zIndex-popover, var(--sys-zIndex-tooltip));
        display: none;
        box-sizing: border-box;
        min-width: 14rem;
        max-width: 20rem;
        padding: var(--comp-hoverCard-padding-vertical) var(--comp-hoverCard-padding-horizontal);
        color: var(--comp-hoverCard-text);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        line-height: var(--sys-typography-body-lineHeight);
      }

      :host([open]) .panel {
        display: block;
      }

      .content {
        position: relative;
      }

      .sketch-fill {
        fill: var(--comp-hoverCard-bg);
        stroke: none;
      }
    `,
  ];

  /** Delay (ms) before showing on hover. Defaults to the `slow` motion duration. */
  @property({ type: Number }) delay = Number.parseFloat(tokens.sys.animation.duration.slow);
  /** Controlled open state. */
  @property({ type: Boolean, reflect: true }) open = false;

  @query('.trigger') private triggerEl?: HTMLElement;
  @query('.panel') private panelEl?: HTMLElement;

  private focused = false;
  private readonly panelId = `gh-hover-card-${hoverCardUid++}`;
  private timer: ReturnType<typeof setTimeout> | null = null;

  protected override get frame(): HTMLElement {
    return this.panelEl ?? this;
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener('mouseenter', this.onEnter);
    this.addEventListener('mouseleave', this.onLeave);
    this.addEventListener('focusin', this.onFocus);
    this.addEventListener('focusout', this.onBlur);
    this.addEventListener('keydown', this.onKeydown);
  }

  override disconnectedCallback(): void {
    this.removeEventListener('mouseenter', this.onEnter);
    this.removeEventListener('mouseleave', this.onLeave);
    this.removeEventListener('focusin', this.onFocus);
    this.removeEventListener('focusout', this.onBlur);
    this.removeEventListener('keydown', this.onKeydown);
    this.clearTimer();
    super.disconnectedCallback();
  }

  private clearTimer(): void {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  }

  private readonly onEnter = (): void => {
    this.clearTimer();
    this.timer = setTimeout(() => void this.reveal(), this.delay);
  };
  private readonly onFocus = (): void => {
    this.focused = true;
    void this.reveal();
  };
  private readonly onLeave = (): void => {
    if (!this.focused) {
      this.dismiss();
    }
  };
  private readonly onBlur = (): void => {
    this.focused = false;
    this.dismiss();
  };
  private readonly onKeydown = (event: KeyboardEvent): void => {
    if (event.key === 'Escape') {
      this.dismiss();
    }
  };

  private async reveal(): Promise<void> {
    this.clearTimer();
    this.open = true;
    this.triggerEl?.setAttribute('aria-describedby', this.panelId);
    await this.updateComplete;
    const trigger = this.triggerEl;
    const panel = this.panelEl;
    if (trigger && panel) {
      const { x, y } = await computePosition(trigger, panel, {
        strategy: 'fixed',
        placement: 'bottom',
        middleware: [
          offset(Number.parseFloat(tokens.comp.hoverCard.offset)),
          flip(),
          shift({ padding: Number.parseFloat(tokens.sys.spacing.sm) }),
        ],
      });
      panel.style.left = `${x}px`;
      panel.style.top = `${y}px`;
      this.measure();
    }
  }

  private dismiss(): void {
    this.clearTimer();
    this.open = false;
    this.triggerEl?.removeAttribute('aria-describedby');
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.hoverCard.sketch.roughness,
      bowing: tokens.comp.hoverCard.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return html`<span class="trigger" tabindex="0"><slot name="trigger"></slot></span>
      <div class="panel" id=${this.panelId} role="dialog">
        ${this.renderSketch()}
        <div class="content"><slot></slot></div>
      </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-hover-card': GhHoverCard;
  }
}
