// packages/react/src/components/Item.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Visual treatment of an {@link Item} row. */
export type ItemVariant = 'default' | 'muted' | 'outline';

export interface ItemProps extends HTMLAttributes<HTMLDivElement> {
  /**
   * Surface treatment. `'default'` is transparent; `'muted'` fills a subtle
   * background; `'outline'` draws a hand-drawn border. Defaults to `'default'`.
   */
  variant?: ItemVariant;
  /** Marks the row as the selected/active one (fills the selected background). */
  selected?: boolean;
}

const item = tokens.comp.item;
const c = cssVars.comp.item;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

/**
 * A flexible list-row primitive: a horizontal band of optional leading media,
 * a growing content column, and trailing actions. Compose it with
 * {@link ItemMedia}, {@link ItemContent}, {@link ItemTitle},
 * {@link ItemDescription} and {@link ItemActions}.
 *
 * The `'outline'` variant paints a sketchy border via `@ghds/sketch-core`; all
 * colours, spacing and sketch parameters come from `@ghds/tokens`
 * (`comp.item.*`). Renders a plain `<div>` — set a role (e.g. `listitem`,
 * `option`) on the container as your composition requires.
 */
export const Item = forwardRef<HTMLDivElement, ItemProps>(function Item(
  { variant = 'default', selected = false, children, style, ...rest },
  forwardedRef,
) {
  const outline = variant === 'outline';
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    roughness: item.sketch.roughness,
    bowing: item.sketch.bowing,
    inset: INSET,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);

  const background = selected ? c.bg.selected : variant === 'muted' ? c.bg.hover : undefined;

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'flex',
    alignItems: 'center',
    gap: item.gap,
    boxSizing: 'border-box',
    padding: `${item.padding.vertical} ${item.padding.horizontal}`,
    borderRadius: item.radius,
    background,
    color: c.text.title,
    fontFamily: tokens.sys.typography.body.fontFamily,
    ...style,
  };

  return (
    <div ref={ref} style={rootStyle} {...rest}>
      {outline && (
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={c.stroke.default}
          strokeWidth={STROKE_WIDTH}
        />
      )}
      {children}
    </div>
  );
});

/** Leading media slot (icon, avatar, thumbnail). */
export const ItemMedia = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ItemMedia({ children, style, ...rest }, forwardedRef) {
    const mediaStyle: CSSProperties = {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      ...style,
    };
    return (
      <div ref={forwardedRef} style={mediaStyle} {...rest}>
        {children}
      </div>
    );
  },
);

/** Growing content column between the media and the actions. */
export const ItemContent = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ItemContent({ children, style, ...rest }, forwardedRef) {
    const contentStyle: CSSProperties = {
      display: 'flex',
      flexDirection: 'column',
      gap: tokens.sys.spacing.xs,
      flex: 1,
      minWidth: 0,
      ...style,
    };
    return (
      <div ref={forwardedRef} style={contentStyle} {...rest}>
        {children}
      </div>
    );
  },
);

/** Primary line of the content column. */
export const ItemTitle = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ItemTitle({ children, style, ...rest }, forwardedRef) {
    const titleStyle: CSSProperties = {
      color: c.text.title,
      fontFamily: tokens.sys.typography.label.fontFamily,
      fontSize: tokens.sys.typography.label.fontSize,
      fontWeight: tokens.sys.typography.label.fontWeight,
      lineHeight: String(tokens.sys.typography.label.lineHeight),
      ...style,
    };
    return (
      <div ref={forwardedRef} style={titleStyle} {...rest}>
        {children}
      </div>
    );
  },
);

/** Secondary, muted line of the content column. */
export const ItemDescription = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ItemDescription({ children, style, ...rest }, forwardedRef) {
    const descriptionStyle: CSSProperties = {
      color: c.text.description,
      fontFamily: tokens.sys.typography.caption.fontFamily,
      fontSize: tokens.sys.typography.caption.fontSize,
      fontWeight: tokens.sys.typography.caption.fontWeight,
      lineHeight: String(tokens.sys.typography.caption.lineHeight),
      ...style,
    };
    return (
      <div ref={forwardedRef} style={descriptionStyle} {...rest}>
        {children}
      </div>
    );
  },
);

/** Trailing actions slot (buttons, badges, chevrons). */
export const ItemActions = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ItemActions({ children, style, ...rest }, forwardedRef) {
    const actionsStyle: CSSProperties = {
      display: 'flex',
      alignItems: 'center',
      gap: tokens.sys.spacing.sm,
      flexShrink: 0,
      ...style,
    };
    return (
      <div ref={forwardedRef} style={actionsStyle} {...rest}>
        {children}
      </div>
    );
  },
);

// packages/web-components/src/components/item.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Visual treatment of a `<gh-item>` row. */
export type GhItemVariant = 'default' | 'muted' | 'outline';

/**
 * `<gh-item>` — a flexible list-row primitive: a horizontal band of optional
 * leading media (`media` slot), a growing content column (default slot), and
 * trailing actions (`actions` slot).
 *
 * The `'outline'` variant paints a sketchy border via `@ghds/sketch-core`;
 * `'muted'` fills a subtle hover background; `'default'` is transparent. The
 * `selected` state fills the selected background. All colours, spacing and
 * sketch parameters come from `@ghds/tokens` (`comp.item.*`).
 */
@customElement('gh-item')
export class GhItem extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        color: var(--comp-item-stroke-default);
      }

      .item {
        position: relative;
        display: flex;
        align-items: center;
        gap: var(--comp-item-gap);
        box-sizing: border-box;
        padding: var(--comp-item-padding-vertical) var(--comp-item-padding-horizontal);
        border-radius: var(--comp-item-radius);
        color: var(--comp-item-text-title);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        font-weight: var(--sys-typography-body-fontWeight);
        line-height: var(--sys-typography-body-lineHeight);
      }

      :host([variant='muted']) .item {
        background: var(--comp-item-bg-hover);
      }

      :host([selected]) .item {
        background: var(--comp-item-bg-selected);
      }

      .media {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
      }

      .content {
        position: relative;
        display: flex;
        flex-direction: column;
        gap: var(--sys-spacing-xs);
        flex: 1;
        min-width: 0;
      }

      .actions {
        position: relative;
        display: flex;
        align-items: center;
        gap: var(--sys-spacing-sm);
        flex-shrink: 0;
      }

      ::slotted([slot='title']) {
        color: var(--comp-item-text-title);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
      }

      ::slotted([slot='description']) {
        color: var(--comp-item-text-description);
        font-family: var(--sys-typography-caption-fontFamily);
        font-size: var(--sys-typography-caption-fontSize);
        font-weight: var(--sys-typography-caption-fontWeight);
        line-height: var(--sys-typography-caption-lineHeight);
      }
    `,
  ];

  /**
   * Surface treatment. `'default'` is transparent; `'muted'` fills a subtle
   * background; `'outline'` draws a hand-drawn border. Defaults to `'default'`.
   */
  @property({ type: String, reflect: true }) variant: GhItemVariant = 'default';
  /** Marks the row as the selected/active one (fills the selected background). */
  @property({ type: Boolean, reflect: true }) selected = false;

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.item.sketch.roughness,
      bowing: tokens.comp.item.sketch.bowing,
    };
  }

  protected override render(): unknown {
    return html`<div class="item" part="item">
      ${this.variant === 'outline' ? this.renderSketch() : nothing}
      <div class="media" part="media"><slot name="media"></slot></div>
      <div class="content" part="content">
        <slot name="title"></slot>
        <slot></slot>
        <slot name="description"></slot>
      </div>
      <div class="actions" part="actions"><slot name="actions"></slot></div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-item': GhItem;
  }
}
