// packages/react-native/src/components/Item.tsx
import { useTheme } from '@shopify/restyle';
import type { ReactNode } from 'react';
import { type GestureResponderEvent, Pressable } from 'react-native';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box, Text } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';

/** Visual treatment of an {@link Item} row. */
export type ItemVariant = 'default' | 'muted' | 'outline';

/** Props for {@link Item}. */
export interface ItemProps {
  /**
   * Surface treatment. `'default'` is transparent; `'muted'` fills a subtle
   * background; `'outline'` draws a hand-drawn border. Defaults to `'default'`.
   */
  variant?: ItemVariant;
  /** Marks the row as the selected/active one (fills the selected background). */
  selected?: boolean;
  /** Row content — compose with the `Item*` sub-components. */
  children?: ReactNode;
  /** Press handler; when set the row is exposed as a button. */
  onPress?: (event: GestureResponderEvent) => void;
  /** Test handle for queries. */
  testID?: string;
  /** Accessible label for the row. */
  accessibilityLabel?: string;
}

/**
 * A flexible list-row primitive: a horizontal band of optional leading media,
 * a growing content column, and trailing actions. Compose it with
 * {@link ItemMedia}, {@link ItemContent}, {@link ItemTitle},
 * {@link ItemDescription} and {@link ItemActions}.
 *
 * The `'outline'` variant paints a sketchy border via `@ghds/sketch-core`; all
 * colours, spacing and sketch parameters come from `@ghds/tokens`
 * (`comp.item.*`) via the Restyle theme.
 */
export function Item({
  variant = 'default',
  selected = false,
  children,
  onPress,
  testID,
  accessibilityLabel,
}: ItemProps) {
  const theme = useTheme<Theme>();
  const outline = variant === 'outline';

  const { onLayout, size, drawable } = useSketch({
    inset: theme.borderWidths.default,
    roughness: theme.itemSketch.roughness,
    bowing: theme.itemSketch.bowing,
  });

  let backgroundColor: 'itemBgSelected' | 'itemBgHover' | 'transparent';
  if (selected) {
    backgroundColor = 'itemBgSelected';
  } else if (variant === 'muted') {
    backgroundColor = 'itemBgHover';
  } else {
    backgroundColor = 'transparent';
  }

  const row = (
    <Box
      onLayout={onLayout}
      flexDirection="row"
      alignItems="center"
      gap="itemGap"
      paddingHorizontal="itemHorizontal"
      paddingVertical="itemVertical"
      borderRadius="item"
      backgroundColor={backgroundColor}
      testID={onPress ? undefined : testID}
      accessibilityLabel={onPress ? undefined : accessibilityLabel}
    >
      {outline ? (
        <SketchBackground
          drawable={drawable}
          size={size}
          strokeColor={theme.colors.itemStrokeDefault}
          strokeWidth={theme.borderWidths.default}
        />
      ) : null}
      {children}
    </Box>
  );

  if (onPress) {
    return (
      <Pressable
        onPress={onPress}
        testID={testID}
        accessibilityRole="button"
        accessibilityLabel={accessibilityLabel}
      >
        {row}
      </Pressable>
    );
  }

  return row;
}

/** Leading media slot (icon, avatar, thumbnail). */
export function ItemMedia({ children }: { children?: ReactNode }) {
  return (
    <Box alignItems="center" justifyContent="center" flexShrink={0}>
      {children}
    </Box>
  );
}

/** Growing content column between the media and the actions. */
export function ItemContent({ children }: { children?: ReactNode }) {
  return (
    <Box flexDirection="column" gap="xs" flex={1} minWidth={0}>
      {children}
    </Box>
  );
}

/** Primary line of the content column. */
export function ItemTitle({ children }: { children?: ReactNode }) {
  return (
    <Text variant="label" color="itemTextTitle">
      {children}
    </Text>
  );
}

/** Secondary, muted line of the content column. */
export function ItemDescription({ children }: { children?: ReactNode }) {
  return (
    <Text variant="caption" color="itemTextDescription">
      {children}
    </Text>
  );
}

/** Trailing actions slot (buttons, badges, chevrons). */
export function ItemActions({ children }: { children?: ReactNode }) {
  return (
    <Box flexDirection="row" alignItems="center" gap="sm" flexShrink={0}>
      {children}
    </Box>
  );
}

// packages/web-components/src/components/item.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Visual treatment of a `<gh-item>` row. */
export type GhItemVariant = 'default' | 'muted' | 'outline';

/**
 * `<gh-item>` — a flexible list-row primitive: a horizontal band of optional
 * leading media (`media` slot), a growing content column (default slot), and
 * trailing actions (`actions` slot).
 *
 * The `'outline'` variant paints a sketchy border via `@ghds/sketch-core`;
 * `'muted'` fills a subtle hover background; `'default'` is transparent. The
 * `selected` state fills the selected background. All colours, spacing and
 * sketch parameters come from `@ghds/tokens` (`comp.item.*`).
 */
@customElement('gh-item')
export class GhItem extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        color: var(--comp-item-stroke-default);
      }

      .item {
        position: relative;
        display: flex;
        align-items: center;
        gap: var(--comp-item-gap);
        box-sizing: border-box;
        padding: var(--comp-item-padding-vertical) var(--comp-item-padding-horizontal);
        border-radius: var(--comp-item-radius);
        color: var(--comp-item-text-title);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        font-weight: var(--sys-typography-body-fontWeight);
        line-height: var(--sys-typography-body-lineHeight);
      }

      :host([variant='muted']) .item {
        background: var(--comp-item-bg-hover);
      }

      :host([selected]) .item {
        background: var(--comp-item-bg-selected);
      }

      .media {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
      }

      .content {
        position: relative;
        display: flex;
        flex-direction: column;
        gap: var(--sys-spacing-xs);
        flex: 1;
        min-width: 0;
      }

      .actions {
        position: relative;
        display: flex;
        align-items: center;
        gap: var(--sys-spacing-sm);
        flex-shrink: 0;
      }

      ::slotted([slot='title']) {
        color: var(--comp-item-text-title);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
      }

      ::slotted([slot='description']) {
        color: var(--comp-item-text-description);
        font-family: var(--sys-typography-caption-fontFamily);
        font-size: var(--sys-typography-caption-fontSize);
        font-weight: var(--sys-typography-caption-fontWeight);
        line-height: var(--sys-typography-caption-lineHeight);
      }
    `,
  ];

  /**
   * Surface treatment. `'default'` is transparent; `'muted'` fills a subtle
   * background; `'outline'` draws a hand-drawn border. Defaults to `'default'`.
   */
  @property({ type: String, reflect: true }) variant: GhItemVariant = 'default';
  /** Marks the row as the selected/active one (fills the selected background). */
  @property({ type: Boolean, reflect: true }) selected = false;

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.item.sketch.roughness,
      bowing: tokens.comp.item.sketch.bowing,
    };
  }

  protected override render(): unknown {
    return html`<div class="item" part="item">
      ${this.variant === 'outline' ? this.renderSketch() : nothing}
      <div class="media" part="media"><slot name="media"></slot></div>
      <div class="content" part="content">
        <slot name="title"></slot>
        <slot></slot>
        <slot name="description"></slot>
      </div>
      <div class="actions" part="actions"><slot name="actions"></slot></div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-item': GhItem;
  }
}
