// packages/react/src/components/NativeSelect.tsx
import { tokens } from '@ghds/tokens';
import { Label } from '@radix-ui/react-label';
import {
  type CSSProperties,
  type FocusEvent,
  forwardRef,
  type SelectHTMLAttributes,
  useState,
} from 'react';
import { useFormFieldWiring } from '../hooks/useFormFieldWiring.js';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { toPx } from '../lib/units.js';
import { Icon } from './Icon.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface NativeSelectProps extends Omit<SelectHTMLAttributes<HTMLSelectElement>, 'size'> {
  /** Visible label. Associated to the select via Radix `Label` for accessibility. */
  label?: string;
  /** Error message. When set, the field is marked invalid and the text announced. */
  error?: string;
}

const nativeSelect = tokens.comp.nativeSelect;
const c = cssVars.comp.nativeSelect;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

function resolveStroke(focused: boolean, hasError: boolean): string {
  if (hasError) {
    return c.stroke.danger;
  }
  return focused ? c.stroke.focus : c.stroke.default;
}

/**
 * A hand-drawn wrapper around a real native `<select>`. Unlike {@link Select}
 * (a fully custom listbox), this keeps the platform's native dropdown — useful
 * on touch devices and for long option lists — and only restyles the closed
 * control with the sketchy box and a chevron. Every colour, padding, radius and
 * sketch parameter comes from `@ghds/tokens` (`comp.nativeSelect.*`). A Radix
 * `Label` is associated with the `<select>`, and error state is exposed via
 * `aria-invalid` + `aria-describedby` and a `role="alert"` message.
 */
export const NativeSelect = forwardRef<HTMLSelectElement, NativeSelectProps>(function NativeSelect(
  {
    label,
    error,
    id,
    disabled = false,
    style,
    children,
    onFocus,
    onBlur,
    'aria-describedby': ariaDescribedByProp,
    'aria-invalid': ariaInvalidProp,
    ...rest
  },
  forwardedRef,
) {
  const {
    fieldId: selectId,
    errorId,
    hasError,
    describedBy,
    showLabel,
    showOwnError,
  } = useFormFieldWiring(id, label, error);

  const [focused, setFocused] = useState(false);

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: nativeSelect.sketch.roughness,
    bowing: nativeSelect.sketch.bowing,
    inset: INSET,
  });

  const fieldStyle: CSSProperties = {
    display: 'inline-flex',
    flexDirection: 'column',
    gap: nativeSelect.gap,
    fontFamily: tokens.sys.typography.body.fontFamily,
    ...style,
  };

  const labelStyle: CSSProperties = {
    color: c.text.label,
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.label.lineHeight),
  };

  const controlStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'flex',
    alignItems: 'center',
    boxSizing: 'border-box',
  };

  const selectStyle: CSSProperties = {
    flex: 1,
    boxSizing: 'border-box',
    width: '100%',
    margin: 0,
    // Room on the right for the overlaid chevron.
    padding: `${nativeSelect.padding.vertical} calc(${nativeSelect.padding.horizontal} + ${tokens.sys.icon.size.sm}) ${nativeSelect.padding.vertical} ${nativeSelect.padding.horizontal}`,
    border: 'none',
    outline: 'none',
    background: 'transparent',
    appearance: 'none',
    WebkitAppearance: 'none',
    MozAppearance: 'none',
    color: disabled ? c.text.disabled : c.text.value,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    fontWeight: tokens.sys.typography.body.fontWeight,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
    cursor: disabled ? 'not-allowed' : 'pointer',
  };

  const chevronStyle: CSSProperties = {
    position: 'absolute',
    right: nativeSelect.padding.horizontal,
    top: '50%',
    transform: 'translateY(-50%)',
    pointerEvents: 'none',
    color: disabled ? c.icon.disabled : c.icon.default,
  };

  const errorStyle: CSSProperties = {
    color: c.text.danger,
    fontFamily: tokens.sys.typography.caption.fontFamily,
    fontSize: tokens.sys.typography.caption.fontSize,
    fontWeight: tokens.sys.typography.caption.fontWeight,
    lineHeight: String(tokens.sys.typography.caption.lineHeight),
  };

  return (
    <div style={fieldStyle}>
      {showLabel && (
        <Label htmlFor={selectId} style={labelStyle}>
          {label}
        </Label>
      )}
      <div ref={sketchRef} style={controlStyle}>
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={resolveStroke(focused, hasError)}
          strokeWidth={STROKE_WIDTH}
          fillColor={disabled ? c.bg.disabled : c.bg.default}
          fillRendering="fill"
        />
        <select
          ref={forwardedRef}
          id={selectId}
          disabled={disabled}
          aria-invalid={ariaInvalidProp ?? (hasError || undefined)}
          aria-describedby={
            [ariaDescribedByProp, describedBy].filter(Boolean).join(' ') || undefined
          }
          style={selectStyle}
          onFocus={(event: FocusEvent<HTMLSelectElement>) => {
            setFocused(true);
            onFocus?.(event);
          }}
          onBlur={(event: FocusEvent<HTMLSelectElement>) => {
            setFocused(false);
            onBlur?.(event);
          }}
          {...rest}
        >
          {children}
        </select>
        <Icon name="chevron-down" size="sm" style={chevronStyle} />
      </div>
      {showOwnError && (
        <span id={errorId} role="alert" style={errorStyle}>
          {error}
        </span>
      )}
    </div>
  );
});

// packages/web-components/src/components/native-select.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';
import './icon.js';

let nativeSelectIdCounter = 0;

/**
 * `<gh-native-select>` — a hand-drawn wrapper around a real native `<select>`.
 *
 * Unlike `<gh-select>` (a fully custom listbox), this keeps the platform's
 * native dropdown — useful on touch devices and for long option lists — and only
 * restyles the closed control with a sketchy box and a trailing chevron. Pass a
 * native `<select>` (with its `<option>`s) as the default slot:
 *
 * ```html
 * <gh-native-select label="Country"><select>…</select></gh-native-select>
 * ```
 *
 * The box is a sketchy rectangle outline from `@ghds/sketch-core` over a
 * token-driven fill. The outline stroke uses `currentColor`: the host resolves
 * it to `comp.nativeSelect.stroke.default`, switches to the focus colour on
 * `:focus-within`, and to the danger colour when `invalid`. Every colour,
 * padding, radius and sketch parameter comes from `comp.nativeSelect.*` tokens.
 */
@customElement('gh-native-select')
export class GhNativeSelect extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
        flex-direction: column;
        gap: var(--comp-nativeSelect-gap);
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-nativeSelect-stroke-default);
        font-family: var(--sys-typography-body-fontFamily);
      }

      :host(:focus-within) {
        color: var(--comp-nativeSelect-stroke-focus);
      }

      :host([invalid]) {
        color: var(--comp-nativeSelect-stroke-danger);
      }

      .label {
        color: var(--comp-nativeSelect-text-label);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
      }

      .control {
        position: relative;
        display: flex;
        align-items: center;
        box-sizing: border-box;
        background: var(--comp-nativeSelect-bg-default);
        border-radius: var(--comp-nativeSelect-radius);
      }

      :host([disabled]) .control {
        background: var(--comp-nativeSelect-bg-disabled);
      }

      ::slotted(select) {
        position: relative;
        flex: 1;
        box-sizing: border-box;
        width: 100%;
        margin: 0;
        /* Room on the right for the overlaid chevron. */
        padding: var(--comp-nativeSelect-padding-vertical)
          calc(
            var(--comp-nativeSelect-padding-horizontal) + var(--sys-icon-size-sm) +
              var(--sys-spacing-xs)
          )
          var(--comp-nativeSelect-padding-vertical) var(--comp-nativeSelect-padding-horizontal);
        border: none;
        outline: none;
        background: transparent;
        appearance: none;
        -webkit-appearance: none;
        color: var(--comp-nativeSelect-text-value);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        font-weight: var(--sys-typography-body-fontWeight);
        line-height: var(--sys-typography-body-lineHeight);
        cursor: pointer;
      }

      ::slotted(select:disabled) {
        color: var(--comp-nativeSelect-text-disabled);
        cursor: not-allowed;
      }

      .chevron {
        position: absolute;
        right: var(--comp-nativeSelect-padding-horizontal);
        top: 50%;
        transform: translateY(-50%);
        pointer-events: none;
        color: var(--comp-nativeSelect-icon-default);
      }

      :host([disabled]) .chevron {
        color: var(--comp-nativeSelect-icon-disabled);
      }
    `,
  ];

  /** Disables the control and mutes the surface. Propagated to the slotted `<select>`. */
  @property({ type: Boolean, reflect: true }) disabled = false;
  /** Marks the field invalid, painting the danger stroke. */
  @property({ type: Boolean, reflect: true }) invalid = false;
  /** Optional visible label; also the accessible name of the slotted `<select>`. */
  @property({ type: String }) label?: string;

  @query('.control') private controlEl!: HTMLDivElement;

  private readonly labelId = `gh-native-select-${++nativeSelectIdCounter}-label`;

  /** The drawn box is the control row only — not the label above it. */
  protected override get frame(): HTMLElement {
    return this.controlEl ?? this;
  }

  /** The slotted native `<select>`, if present. */
  private get selectEl(): HTMLSelectElement | null {
    const slot = this.shadowRoot?.querySelector('slot');
    const assigned = slot?.assignedElements({ flatten: true }) ?? [];
    for (const node of assigned) {
      if (node instanceof HTMLSelectElement) {
        return node;
      }
      const nested = node.querySelector?.('select');
      if (nested instanceof HTMLSelectElement) {
        return nested;
      }
    }
    return null;
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('disabled') || changed.has('invalid') || changed.has('label')) {
      this.syncSelect();
    }
  }

  private readonly syncSelect = (): void => {
    const select = this.selectEl;
    if (!select) {
      return;
    }
    select.disabled = this.disabled;
    if (this.invalid) {
      select.setAttribute('aria-invalid', 'true');
    } else {
      select.removeAttribute('aria-invalid');
    }
    if (this.label !== undefined) {
      select.setAttribute('aria-labelledby', this.labelId);
    } else {
      select.removeAttribute('aria-labelledby');
    }
    // Re-measure in case enabling/disabling changed the control's metrics.
    this.measure();
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.nativeSelect.sketch.roughness,
      bowing: tokens.comp.nativeSelect.sketch.bowing,
    };
  }

  protected override render(): unknown {
    return html`${
      this.label !== undefined
        ? html`<span class="label" id=${this.labelId}>${this.label}</span>`
        : nothing
    }
      <div class="control" part="control">
        ${this.renderSketch()}
        <slot @slotchange=${this.syncSelect}></slot>
        <gh-icon class="chevron" name="chevron-down" size="sm"></gh-icon>
      </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-native-select': GhNativeSelect;
  }
}
