// packages/react/src/components/NavigationMenu.tsx
import { autoUpdate, flip, offset, shift, useFloating } from '@floating-ui/react-dom';
import { tokens } from '@ghds/tokens';
import {
  type CSSProperties,
  type KeyboardEvent,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import { useClickOutside } from '../hooks/useClickOutside.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { Icon } from './Icon.js';

/** A link inside a {@link NavigationMenu} dropdown panel. */
export interface NavigationMenuLink {
  label: string;
  href: string;
  description?: string;
}

/** One top-level entry in a {@link NavigationMenu}. */
export interface NavigationMenuItem {
  label: string;
  /** A direct link (renders an `<a>` with no dropdown). */
  href?: string;
  /** Dropdown links (renders a disclosure button + panel). */
  links?: NavigationMenuLink[];
  /** Marks this entry as the current section. */
  active?: boolean;
}

export interface NavigationMenuProps {
  /** The top-level navigation entries. */
  items: NavigationMenuItem[];
  /** Accessible label for the `<nav>`. */
  'aria-label'?: string;
}

const navigationMenu = tokens.comp.navigationMenu;
const c = cssVars.comp.navigationMenu;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);

/**
 * A hand-drawn navigation menu: a `<nav>` of top-level entries. A plain entry
 * renders an `<a>`; an entry with `links` renders a disclosure button that
 * opens a floating panel of links on hover/click, closing on Escape or outside
 * click. Positioned with `@floating-ui/react-dom`; colours come from
 * `@ghds/tokens` (`comp.navigationMenu.*`).
 */
export function NavigationMenu({ items, 'aria-label': ariaLabel }: NavigationMenuProps) {
  const baseId = useId();
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const triggersRef = useRef<(HTMLButtonElement | null)[]>([]);
  const panelRef = useRef<HTMLDivElement>(null);

  const { refs, floatingStyles } = useFloating({
    open: openIndex !== null,
    placement: 'bottom-start',
    strategy: 'fixed',
    whileElementsMounted: openIndex !== null ? autoUpdate : undefined,
    middleware: [
      offset(toPx(tokens.sys.spacing.xs)),
      flip(),
      shift({ padding: toPx(tokens.sys.spacing.sm) }),
    ],
  });

  useEffect(() => {
    if (openIndex !== null) {
      refs.setReference(triggersRef.current[openIndex] ?? null);
    }
  }, [openIndex, refs]);

  const outsideRefs = useMemo(() => [panelRef], []);
  useClickOutside(
    outsideRefs,
    openIndex !== null,
    useCallback(() => setOpenIndex(null), []),
  );

  const openLinks = openIndex !== null ? (items[openIndex]?.links ?? []) : [];

  const handleTriggerKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number) => {
    if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      setOpenIndex(index);
    } else if (event.key === 'Escape') {
      setOpenIndex(null);
    }
  };

  const navStyle: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.sys.spacing.xs,
    fontFamily: tokens.sys.typography.label.fontFamily,
  };

  const entryStyle = (active: boolean): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.sys.spacing.xs,
    padding: `${tokens.sys.spacing.xs} ${tokens.sys.spacing.sm}`,
    border: 'none',
    borderRadius: navigationMenu.radius,
    background: 'transparent',
    color: active ? c.text.active : c.text.default,
    textDecoration: 'none',
    cursor: 'pointer',
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
  });

  const panelStyle: CSSProperties = {
    ...floatingStyles,
    display: openIndex !== null ? 'flex' : 'none',
    flexDirection: 'column',
    gap: tokens.sys.spacing.xs,
    zIndex: tokens.sys.zIndex.dropdown,
    minWidth: '14rem',
    boxSizing: 'border-box',
    padding: navigationMenu.padding,
    background: c.bg,
    border: `${STROKE_WIDTH}px solid ${c.stroke}`,
    borderRadius: navigationMenu.radius,
    boxShadow: c.shadow,
  };

  return (
    <nav aria-label={ariaLabel} style={navStyle}>
      <ul
        style={{
          display: 'flex',
          gap: tokens.sys.spacing.xs,
          margin: 0,
          padding: 0,
          listStyle: 'none',
        }}
      >
        {items.map((item, index) => (
          <li key={item.label} onMouseLeave={() => openIndex === index && setOpenIndex(null)}>
            {item.links ? (
              <button
                ref={(el) => {
                  triggersRef.current[index] = el;
                }}
                type="button"
                id={`${baseId}-trigger-${index}`}
                aria-haspopup="menu"
                aria-expanded={openIndex === index}
                style={entryStyle(item.active ?? false)}
                onClick={() => setOpenIndex((prev) => (prev === index ? null : index))}
                onMouseEnter={() => setOpenIndex(index)}
                onKeyDown={(event) => handleTriggerKeyDown(event, index)}
              >
                {item.label}
                <Icon
                  name="chevron-down"
                  size="sm"
                  style={{
                    transform: openIndex === index ? 'rotate(180deg)' : undefined,
                    transition: `transform ${tokens.sys.animation.duration.fast} ${tokens.sys.animation.easing.standard}`,
                  }}
                />
              </button>
            ) : (
              <a href={item.href} style={entryStyle(item.active ?? false)}>
                {item.label}
              </a>
            )}
          </li>
        ))}
      </ul>
      <div
        ref={mergeRefs(refs.setFloating, panelRef)}
        role="menu"
        aria-label={openIndex !== null ? items[openIndex]?.label : undefined}
        style={panelStyle}
        onMouseEnter={() => openIndex !== null && setOpenIndex(openIndex)}
        onKeyDown={(event) => {
          if (event.key === 'Escape') {
            setOpenIndex(null);
            if (openIndex !== null) {
              triggersRef.current[openIndex]?.focus();
            }
          }
        }}
      >
        {openLinks.map((link) => (
          <a
            key={link.href}
            href={link.href}
            role="menuitem"
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: tokens.sys.spacing.xs,
              padding: `${tokens.sys.spacing.xs} ${tokens.sys.spacing.sm}`,
              borderRadius: navigationMenu.radius,
              color: c.text.default,
              textDecoration: 'none',
            }}
          >
            <span style={{ fontWeight: tokens.sys.typography.label.fontWeight }}>{link.label}</span>
            {link.description !== undefined && (
              <span
                style={{
                  color: tokens.sys.color.text.secondary,
                  fontSize: tokens.sys.typography.caption.fontSize,
                }}
              >
                {link.description}
              </span>
            )}
          </a>
        ))}
      </div>
    </nav>
  );
}

// packages/web-components/src/components/navigation-menu.ts
import { autoUpdate, computePosition, flip, offset, shift } from '@floating-ui/dom';
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** A leaf navigation link. */
export interface GhNavigationLink {
  label: string;
  href: string;
  description?: string;
}

/** A top-level navigation item: a direct link or a group with a dropdown. */
export interface GhNavigationItem {
  label: string;
  href?: string;
  children?: GhNavigationLink[];
}

let navigationMenuUid = 0;

/**
 * `<gh-navigation-menu>` — a hand-drawn site navigation bar.
 *
 * Renders a `role="navigation"` row of links; items with `children` open a
 * shared floating panel of sub-links on hover / click, positioned with
 * `@floating-ui/dom` and drawn as a sketchy, solid box (`@ghds/sketch-core`).
 * Arrow Left/Right rove the top-level items, Escape closes. Colours and sketch
 * parameters come from `@ghds/tokens` (`comp.navigationMenu.*`).
 */
@customElement('gh-navigation-menu')
export class GhNavigationMenu extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        color: var(--comp-navigationMenu-stroke);
      }

      .list {
        display: inline-flex;
        align-items: center;
        gap: var(--sys-spacing-xs);
        list-style: none;
        margin: 0;
        padding: 0;
      }

      .top {
        display: inline-flex;
        align-items: center;
        gap: var(--sys-spacing-xs);
        box-sizing: border-box;
        margin: 0;
        padding: var(--comp-navigationMenu-padding);
        border: none;
        border-radius: var(--comp-navigationMenu-radius);
        background: transparent;
        color: var(--comp-navigationMenu-text-default);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
        text-decoration: none;
        cursor: pointer;
      }

      .top:hover {
        background: var(--comp-navigationMenu-item-hover);
      }

      .top:focus-visible {
        outline: var(--sys-border-width-thick) solid var(--comp-navigationMenu-stroke);
        outline-offset: var(--sys-spacing-xs);
      }

      .panel {
        position: fixed;
        left: 0;
        top: 0;
        z-index: var(--sys-zIndex-popover, var(--sys-zIndex-dropdown));
        display: none;
        box-sizing: border-box;
        min-width: 14rem;
        padding: var(--comp-navigationMenu-padding);
        color: var(--comp-navigationMenu-text-default);
      }

      .panel.open {
        display: block;
      }

      .links {
        position: relative;
        display: flex;
        flex-direction: column;
        gap: var(--sys-spacing-xs);
      }

      .link {
        display: flex;
        flex-direction: column;
        padding: var(--sys-spacing-xs) var(--sys-spacing-sm);
        border-radius: var(--sys-radius-sm);
        color: var(--comp-navigationMenu-text-default);
        text-decoration: none;
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
      }

      .link:hover {
        background: var(--comp-navigationMenu-item-hover);
        color: var(--comp-navigationMenu-text-active);
      }

      .link .desc {
        color: var(--sys-color-text-secondary);
        font-size: var(--sys-typography-caption-fontSize);
      }

      .sketch-fill {
        fill: var(--comp-navigationMenu-bg);
        stroke: none;
      }
    `,
  ];

  /** The navigation items. */
  @property({ attribute: false }) items: GhNavigationItem[] = [];
  /** Accessible label for the navigation region. */
  @property({ type: String }) label = '';

  @state() private activeIndex = -1;

  @query('.panel') private panelEl?: HTMLElement;

  private readonly uid = `gh-navigation-menu-${navigationMenuUid++}`;
  private cleanupAutoUpdate?: () => void;
  private triggers: HTMLElement[] = [];

  protected override get frame(): HTMLElement {
    return this.panelEl ?? this;
  }

  override disconnectedCallback(): void {
    this.cleanupAutoUpdate?.();
    document.removeEventListener('pointerdown', this.onPointerDown);
    super.disconnectedCallback();
  }

  private readonly onPointerDown = (event: PointerEvent): void => {
    if (!event.composedPath().includes(this)) {
      this.close();
    }
  };

  private async openAt(index: number, trigger: HTMLElement): Promise<void> {
    this.activeIndex = index;
    document.addEventListener('pointerdown', this.onPointerDown);
    await this.updateComplete;
    const panel = this.panelEl;
    if (panel) {
      this.cleanupAutoUpdate?.();
      this.cleanupAutoUpdate = autoUpdate(trigger, panel, () => {
        computePosition(trigger, panel, {
          strategy: 'fixed',
          placement: 'bottom-start',
          middleware: [
            offset(Number.parseFloat(tokens.sys.spacing.xs)),
            flip(),
            shift({ padding: Number.parseFloat(tokens.sys.spacing.sm) }),
          ],
        }).then(({ x, y }) => {
          panel.style.left = `${x}px`;
          panel.style.top = `${y}px`;
          this.measure();
        });
      });
    }
  }

  private close(): void {
    this.activeIndex = -1;
    this.cleanupAutoUpdate?.();
    this.cleanupAutoUpdate = undefined;
    document.removeEventListener('pointerdown', this.onPointerDown);
  }

  private readonly onKeydown = (event: KeyboardEvent): void => {
    this.triggers = [...(this.shadowRoot?.querySelectorAll<HTMLElement>('.top') ?? [])];
    const current = this.triggers.indexOf(this.shadowRoot?.activeElement as HTMLElement);
    if (event.key === 'Escape') {
      this.close();
      return;
    }
    if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') {
      return;
    }
    if (current === -1 || this.triggers.length === 0) {
      return;
    }
    event.preventDefault();
    const direction = event.key === 'ArrowRight' ? 1 : -1;
    const next = (current + direction + this.triggers.length) % this.triggers.length;
    this.triggers[next]?.focus();
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.navigationMenu.sketch.roughness,
      bowing: tokens.comp.navigationMenu.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    const active = this.activeIndex >= 0 ? this.items[this.activeIndex] : undefined;
    const panelId = `${this.uid}-panel`;
    return html`<nav aria-label=${this.label || nothing} @keydown=${this.onKeydown}>
      <ul class="list">
        ${this.items.map((item, index) => {
          if (item.children && item.children.length > 0) {
            return html`<li>
              <button
                class="top"
                type="button"
                aria-haspopup="true"
                aria-expanded=${this.activeIndex === index ? 'true' : 'false'}
                aria-controls=${panelId}
                @click=${(e: MouseEvent) =>
                  this.activeIndex === index
                    ? this.close()
                    : this.openAt(index, e.currentTarget as HTMLElement)}
                @mouseenter=${(e: MouseEvent) => this.openAt(index, e.currentTarget as HTMLElement)}
              >
                ${item.label}
              </button>
            </li>`;
          }
          return html`<li>
            <a class="top" href=${item.href ?? '#'} @mouseenter=${() => this.close()}
              >${item.label}</a
            >
          </li>`;
        })}
      </ul>
      <div
        class=${active ? 'panel open' : 'panel'}
        id=${panelId}
        role="menu"
        @mouseleave=${() => this.close()}
      >
        ${this.renderSketch()}
        <div class="links">
          ${(active?.children ?? []).map(
            (link) => html`<a class="link" role="menuitem" href=${link.href}>
              <span>${link.label}</span>
              ${link.description ? html`<span class="desc">${link.description}</span>` : nothing}
            </a>`,
          )}
        </div>
      </div>
    </nav>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-navigation-menu': GhNavigationMenu;
  }
}
