// packages/react/src/components/Sheet.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, type ReactNode, useId } from 'react';
import { createPortal } from 'react-dom';
import { useFocusTrap } from '../hooks/useFocusTrap.js';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Edge the sheet slides in from. */
export type SheetSide = 'left' | 'right' | 'top' | 'bottom';

export interface SheetProps {
  /** Whether the sheet is shown. */
  open: boolean;
  /** Called when the user requests to close (scrim click, Escape). */
  onClose: () => void;
  /** Edge the panel is anchored to. Defaults to `'right'`. */
  side?: SheetSide;
  /** Accessible title, wired to `aria-labelledby`. */
  title?: string;
  /** Sheet body. */
  children?: ReactNode;
  /** Close when the scrim is clicked. Defaults to `true`. */
  closeOnScrimClick?: boolean;
}

const sheet = tokens.comp.sheet;
const c = cssVars.comp.sheet;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

function panelPosition(side: SheetSide): CSSProperties {
  const horizontal = side === 'left' || side === 'right';
  return horizontal
    ? {
        top: 0,
        bottom: 0,
        [side]: 0,
        height: '100%',
        width: 'min(24rem, 100%)',
      }
    : {
        left: 0,
        right: 0,
        [side]: 0,
        width: '100%',
        maxHeight: '80vh',
      };
}

/**
 * A hand-drawn side sheet. Like {@link Modal} but anchored to a screen edge
 * (`side`). Rendered through a portal with a scrim, `role="dialog"` +
 * `aria-modal`, focus trapping, Escape-to-close, scroll lock and focus
 * restoration (see {@link useFocusTrap}). Colours and sketch parameters come
 * from `@ghds/tokens` (`comp.sheet.*`).
 */
export function Sheet({
  open,
  onClose,
  side = 'right',
  title,
  children,
  closeOnScrimClick = true,
}: SheetProps) {
  const titleId = useId();
  const { containerRef, onKeyDown } = useFocusTrap<HTMLDivElement>(open, onClose);

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: sheet.sketch.roughness,
    bowing: sheet.sketch.bowing,
    inset: INSET,
  });

  if (!open) {
    return null;
  }

  const scrimStyle: CSSProperties = {
    position: 'fixed',
    inset: 0,
    zIndex: sheet.zIndex,
    background: c.scrim,
    opacity: tokens.sys.opacity.scrim,
  };

  const panelStyle: CSSProperties = {
    ...sketchHostStyle,
    position: 'fixed',
    zIndex: sheet.zIndex,
    boxSizing: 'border-box',
    overflow: 'auto',
    padding: sheet.padding,
    color: tokens.sys.color.text.primary,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
    ...panelPosition(side),
  };

  const titleStyle: CSSProperties = {
    position: 'relative',
    margin: `0 0 ${sheet.padding}`,
    color: tokens.sys.color.text.primary,
    fontFamily: tokens.sys.typography.title.fontFamily,
    fontSize: tokens.sys.typography.title.fontSize,
    fontWeight: tokens.sys.typography.title.fontWeight,
    lineHeight: String(tokens.sys.typography.title.lineHeight),
  };

  return createPortal(
    <>
      <div
        style={scrimStyle}
        aria-hidden="true"
        onClick={closeOnScrimClick ? onClose : undefined}
      />
      <div
        ref={mergeRefs(containerRef, sketchRef)}
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? titleId : undefined}
        data-side={side}
        tabIndex={-1}
        style={panelStyle}
        onKeyDown={onKeyDown}
      >
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={c.stroke}
          strokeWidth={STROKE_WIDTH}
          fillColor={c.bg}
          fillRendering="fill"
        />
        {title && (
          <h2 id={titleId} style={titleStyle}>
            {title}
          </h2>
        )}
        <div style={{ position: 'relative' }}>{children}</div>
      </div>
    </>,
    document.body,
  );
}

// packages/web-components/src/components/sheet.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

let sheetUid = 0;

export type GhSheetSide = 'left' | 'right' | 'top' | 'bottom';

/**
 * `<gh-sheet>` — a hand-drawn edge-anchored panel.
 *
 * Built on the native `<dialog>` (`showModal()`) like `gh-modal` for free focus
 * trapping, top layer and Escape-to-close, but anchored to an edge via the
 * `side` attribute (default `right`). The panel is a sketchy, solid box
 * (`@ghds/sketch-core`). Reflects `open`, dispatches a `close` `CustomEvent` on
 * Escape / backdrop click. Colours and sketch parameters come from
 * `@ghds/tokens` (`comp.sheet.*`).
 */
@customElement('gh-sheet')
export class GhSheet extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        color: var(--comp-sheet-stroke);
      }

      dialog {
        position: fixed;
        box-sizing: border-box;
        margin: 0;
        padding: var(--comp-sheet-padding);
        border: none;
        background: transparent;
        color: var(--sys-color-text-primary);
        overflow: visible;
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        line-height: var(--sys-typography-body-lineHeight);
      }

      dialog[data-side='right'] {
        inset: 0 0 0 auto;
        height: 100%;
        width: min(24rem, 100%);
      }

      dialog[data-side='left'] {
        inset: 0 auto 0 0;
        height: 100%;
        width: min(24rem, 100%);
      }

      dialog[data-side='top'] {
        inset: 0 0 auto 0;
        width: 100%;
        max-height: 80vh;
      }

      dialog[data-side='bottom'] {
        inset: auto 0 0 0;
        width: 100%;
        max-height: 80vh;
      }

      dialog::backdrop {
        background: var(--comp-sheet-scrim);
      }

      .title {
        position: relative;
        margin: 0 0 var(--sys-spacing-md);
        color: var(--sys-color-text-primary);
        font-family: var(--sys-typography-title-fontFamily);
        font-size: var(--sys-typography-title-fontSize);
        font-weight: var(--sys-typography-title-fontWeight);
        line-height: var(--sys-typography-title-lineHeight);
      }

      .body {
        position: relative;
      }

      .sketch-fill {
        fill: var(--comp-sheet-bg);
        stroke: none;
      }
    `,
  ];

  /** Whether the sheet is shown. */
  @property({ type: Boolean, reflect: true }) open = false;
  /** Edge the sheet is anchored to. */
  @property({ type: String, reflect: true }) side: GhSheetSide = 'right';
  /** Accessible title, rendered as a heading and wired to `aria-labelledby`. */
  @property({ type: String }) heading = '';
  /** Close when the backdrop is clicked. */
  @property({ type: Boolean }) closeOnScrimClick = true;

  @query('dialog') private dialogEl?: HTMLDialogElement;

  private readonly titleId = `gh-sheet-${sheetUid++}-title`;

  protected override get frame(): HTMLElement {
    return this.dialogEl ?? this;
  }

  protected override updated(changed: PropertyValues): void {
    if (!changed.has('open')) {
      return;
    }
    const dialog = this.dialogEl;
    if (!dialog) {
      return;
    }
    if (this.open && !dialog.open) {
      try {
        dialog.showModal();
      } catch {
        dialog.setAttribute('open', '');
      }
      this.measure();
    } else if (!this.open && dialog.open) {
      dialog.close();
    }
  }

  private readonly requestClose = (): void => {
    this.dispatchEvent(new CustomEvent('close', { bubbles: true, composed: true }));
  };

  private readonly onCancel = (event: Event): void => {
    event.preventDefault();
    this.requestClose();
  };

  private readonly onDialogClick = (event: MouseEvent): void => {
    if (!this.closeOnScrimClick) {
      return;
    }
    const dialog = this.dialogEl;
    if (!dialog || event.target !== dialog) {
      return;
    }
    const rect = dialog.getBoundingClientRect();
    const inside =
      event.clientX >= rect.left &&
      event.clientX <= rect.right &&
      event.clientY >= rect.top &&
      event.clientY <= rect.bottom;
    if (!inside) {
      this.requestClose();
    }
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.sheet.sketch.roughness,
      bowing: tokens.comp.sheet.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return html`<dialog
      data-side=${this.side}
      aria-labelledby=${this.heading ? this.titleId : nothing}
      @cancel=${this.onCancel}
      @click=${this.onDialogClick}
    >
      ${this.renderSketch()}
      ${this.heading ? html`<h2 class="title" id=${this.titleId}>${this.heading}</h2>` : nothing}
      <div class="body"><slot></slot></div>
    </dialog>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-sheet': GhSheet;
  }
}
