// packages/react-native/src/components/Skeleton.tsx
import { useTheme } from '@shopify/restyle';
import { useRef } from 'react';
import { Animated, type DimensionValue, Easing } from 'react-native';
import { useReducedMotionLoop } from '../motion.js';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';

/** Shape of a {@link Skeleton} placeholder. */
export type SkeletonVariant = 'rect' | 'text' | 'circle';

/** Props for {@link Skeleton}. */
export interface SkeletonProps {
  /** Placeholder shape. Defaults to `'rect'`. */
  variant?: SkeletonVariant;
  /** Width (number ⇒ px). Defaults to `'100%'` (or the diameter for `circle`). */
  width?: DimensionValue;
  /** Height (number ⇒ px). Defaults per variant. */
  height?: DimensionValue;
  /** Test handle for queries. */
  testID?: string;
}

/**
 * A hand-drawn loading placeholder: a solid, token-driven surface with a sketchy
 * outline (`@ghds/sketch-core`, rendered with `react-native-svg`) that gently
 * pulses opacity while content loads. Colours, radius, the pulse duration, and
 * the dimmed opacity all come from `@ghds/tokens` via the Restyle theme
 * (`comp.skeleton.*` / `sys.opacity.disabled`). The pulse is suppressed when the
 * OS "reduce motion" setting is on. Hidden from assistive tech — announce the
 * busy state on the region it replaces.
 */
export function Skeleton({ variant = 'rect', width, height, testID }: SkeletonProps) {
  const theme = useTheme<Theme>();
  const isCircle = variant === 'circle';
  const pulse = useRef(new Animated.Value(1)).current;

  const { onLayout, size, drawable } = useSketch({
    shape: isCircle ? 'ellipse' : 'rectangle',
    inset: theme.borderWidths.default,
    roughness: theme.skeletonSketch.roughness,
    bowing: theme.skeletonSketch.bowing,
  });

  const duration = theme.skeletonDuration;
  const pulseMin = theme.skeletonPulseMin;

  useReducedMotionLoop(
    () =>
      Animated.loop(
        Animated.sequence([
          Animated.timing(pulse, {
            toValue: pulseMin,
            duration: duration * 1.5,
            easing: Easing.inOut(Easing.ease),
            useNativeDriver: true,
          }),
          Animated.timing(pulse, {
            toValue: 1,
            duration: duration * 1.5,
            easing: Easing.inOut(Easing.ease),
            useNativeDriver: true,
          }),
        ]),
      ),
    [pulse, pulseMin, duration],
  );

  const diameter: DimensionValue = height ?? width ?? theme.spacing['2xl'];
  const resolvedWidth: DimensionValue = isCircle ? diameter : (width ?? '100%');
  const resolvedHeight: DimensionValue = isCircle
    ? diameter
    : (height ?? (variant === 'text' ? theme.spacing.md : theme.spacing.lg));
  const radius = isCircle || variant === 'text' ? theme.borderRadii.pill : theme.skeletonRadius;

  return (
    <Animated.View style={{ opacity: pulse, alignSelf: isCircle ? 'flex-start' : 'stretch' }}>
      <Box
        onLayout={onLayout}
        backgroundColor="skeletonBg"
        style={{
          width: resolvedWidth,
          height: resolvedHeight,
          borderRadius: radius,
          overflow: 'hidden',
        }}
        testID={testID}
        aria-hidden={true}
        accessibilityElementsHidden={true}
        importantForAccessibility="no-hide-descendants"
      >
        <SketchBackground
          drawable={drawable}
          size={size}
          strokeColor={theme.colors.skeletonStroke}
          strokeWidth={theme.borderWidths.default}
        />
      </Box>
    </Animated.View>
  );
}

// packages/web-components/src/components/skeleton.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { ellipse, rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Shape of a `<gh-skeleton>` placeholder. */
export type GhSkeletonVariant = 'rect' | 'text' | 'circle';

/**
 * `<gh-skeleton>` — a hand-drawn loading placeholder.
 *
 * A sketchy filled shape (`@ghds/sketch-core`) that gently pulses opacity while
 * content loads. Colours, radius, and the pulse duration are token-driven
 * (`comp.skeleton.*`); the dimmed opacity is `sys.opacity.disabled`. The pulse
 * is suppressed under `prefers-reduced-motion: reduce`. The host is
 * `aria-hidden` — announce the busy state on the region it replaces.
 *
 * The host element itself is the sized box (`inline-block`, matching the React
 * implementation); its width/height/radius are applied in `updated()` so the
 * base `ResizeObserver` (which watches the host) re-measures whenever `width`,
 * `height`, or `variant` change.
 */
@customElement('gh-skeleton')
export class GhSkeleton extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        position: relative;
        box-sizing: border-box;
        color: var(--comp-skeleton-stroke);
        animation: gh-skeleton-pulse calc(var(--comp-skeleton-duration) * 3) ease-in-out infinite;
      }

      @keyframes gh-skeleton-pulse {
        0%,
        100% {
          opacity: 1;
        }
        50% {
          opacity: var(--sys-opacity-disabled);
        }
      }

      @media (prefers-reduced-motion: reduce) {
        :host {
          animation: none;
        }
      }

      /* Override the base's line-stroked fill with a solid region fill. */
      .sketch-fill {
        fill: var(--comp-skeleton-bg);
        stroke: none;
      }
    `,
  ];

  /** Placeholder shape. */
  @property({ type: String, reflect: true }) variant: GhSkeletonVariant = 'rect';
  /** Width as a CSS value. Defaults to `100%` (or the diameter for `circle`). */
  @property({ type: String }) width = '';
  /** Height as a CSS value. Defaults per variant. */
  @property({ type: String }) height = '';

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('aria-hidden', 'true');
  }

  // For `circle`, both axes share one diameter (matching React/RN) so passing a
  // single dimension yields a square, not an ellipse.
  private get circleDiameter(): string {
    return this.height || this.width || 'var(--sys-spacing-2xl)';
  }

  private get resolvedWidth(): string {
    if (this.variant === 'circle') {
      return this.circleDiameter;
    }
    return this.width || '100%';
  }

  private get resolvedHeight(): string {
    if (this.variant === 'circle') {
      return this.circleDiameter;
    }
    return (
      this.height || (this.variant === 'text' ? 'var(--sys-spacing-md)' : 'var(--sys-spacing-lg)')
    );
  }

  private get resolvedRadius(): string {
    return this.variant === 'rect' ? 'var(--comp-skeleton-radius)' : 'var(--sys-radius-pill)';
  }

  protected override updated(): void {
    // Size the host box; changing it triggers the base ResizeObserver → measure.
    this.style.width = this.resolvedWidth;
    this.style.height = this.resolvedHeight;
    this.style.borderRadius = this.resolvedRadius;
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return this.variant === 'circle'
      ? ellipse(0, 0, width, height, options)
      : rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.skeleton.sketch.roughness,
      bowing: tokens.comp.skeleton.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return this.renderSketch();
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-skeleton': GhSkeleton;
  }
}
