// packages/web-components/src/components/alert.ts
import type { IconName } from '@ghds/icons';
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';
import './icon.js';

/** Severity of a `<gh-alert>`. */
export type GhAlertVariant = 'info' | 'success' | 'warning' | 'danger';

const ICON: Record<GhAlertVariant, IconName> = {
  info: 'info',
  success: 'check',
  warning: 'warning',
  danger: 'warning',
};

/**
 * `<gh-alert>` — a hand-drawn inline alert/banner. A sketchy box
 * (`@ghds/sketch-core`) with a severity-coloured outline + icon and a slotted
 * message. `danger` exposes `role="alert"`; the rest `role="status"`. Dispatches
 * a `dismiss` event from the optional close button. Token-driven (`comp.alert.*`).
 */
@customElement('gh-alert')
export class GhAlert extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        --_alert-stroke: var(--comp-alert-stroke-info);
        --_alert-icon: var(--comp-alert-icon-info);
        color: var(--_alert-stroke);
      }
      :host([variant='success']) {
        --_alert-stroke: var(--comp-alert-stroke-success);
        --_alert-icon: var(--comp-alert-icon-success);
      }
      :host([variant='warning']) {
        --_alert-stroke: var(--comp-alert-stroke-warning);
        --_alert-icon: var(--comp-alert-icon-warning);
      }
      :host([variant='danger']) {
        --_alert-stroke: var(--comp-alert-stroke-danger);
        --_alert-icon: var(--comp-alert-icon-danger);
      }
      .alert {
        position: relative;
        display: flex;
        align-items: flex-start;
        gap: var(--comp-alert-gap);
        box-sizing: border-box;
        padding: var(--comp-alert-padding);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        line-height: var(--sys-typography-body-lineHeight);
      }
      .icon {
        position: relative;
        display: inline-flex;
        color: var(--_alert-icon);
      }
      .content {
        position: relative;
        flex: 1;
        min-width: 0;
        color: var(--comp-alert-text-body);
      }
      .title {
        color: var(--comp-alert-text-title);
        font-weight: var(--sys-typography-label-fontWeight);
      }
      .close {
        position: relative;
        display: inline-flex;
        padding: 0;
        border: none;
        background: transparent;
        color: var(--comp-alert-text-body);
        cursor: pointer;
      }
      .sketch-fill {
        fill: var(--comp-alert-bg);
        stroke: none;
      }
    `,
  ];

  @property({ type: String, reflect: true }) variant: GhAlertVariant = 'info';
  @property({ type: String }) heading = '';
  @property({ type: Boolean }) dismissible = false;

  private readonly internals: ElementInternals = this.attachInternals();

  protected override updated(): void {
    this.internals.role = this.variant === 'danger' ? 'alert' : 'status';
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.alert.sketch.roughness,
      bowing: tokens.comp.alert.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return html`<div class="alert" part="alert">
      ${this.renderSketch()}
      <span class="icon"><gh-icon name=${ICON[this.variant]} size="sm"></gh-icon></span>
      <div class="content">
        ${this.heading ? html`<div class="title">${this.heading}</div>` : nothing}
        <div><slot></slot></div>
      </div>
      ${
        this.dismissible
          ? html`<button
              class="close"
              aria-label="Dismiss"
              @click=${() =>
                this.dispatchEvent(new CustomEvent('dismiss', { bubbles: true, composed: true }))}
            >
              <gh-icon name="close" size="sm"></gh-icon>
            </button>`
          : nothing
      }
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-alert': GhAlert;
  }
}

// packages/react/src/components/Alert.tsx
import type { IconName } from '@ghds/icons';
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { Icon } from './Icon.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Severity of an {@link Alert}. */
export type AlertVariant = 'info' | 'success' | 'warning' | 'danger';

export interface AlertProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  /** Severity. Defaults to `'info'`. */
  variant?: AlertVariant;
  /** Optional bold title. */
  title?: ReactNode;
  /** Message body. */
  children?: ReactNode;
  /** When provided, renders a dismiss button that calls this. */
  onDismiss?: () => void;
}

const alert = tokens.comp.alert;
const c = cssVars.comp.alert;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

const ICON: Record<AlertVariant, IconName> = {
  info: 'info',
  success: 'check',
  warning: 'warning',
  danger: 'warning',
};

/**
 * A hand-drawn inline alert/banner. A sketchy box (`@ghds/sketch-core`) with a
 * severity-coloured outline and icon plus a message. Danger alerts use
 * `role="alert"` (assertive); the rest use `role="status"` (polite). Colours,
 * padding, and sketch parameters come from `@ghds/tokens` (`comp.alert.*`).
 */
export const Alert = forwardRef<HTMLDivElement, AlertProps>(function Alert(
  { variant = 'info', title, children, onDismiss, style, ...rest },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: alert.sketch.roughness,
    bowing: alert.sketch.bowing,
    inset: INSET,
  });
  const ref = mergeRefs(sketchRef, forwardedRef);

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'flex',
    alignItems: 'flex-start',
    gap: alert.gap,
    boxSizing: 'border-box',
    padding: alert.padding,
    color: c.text.body,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
    ...style,
  };

  const titleStyle: CSSProperties = {
    color: c.text.title,
    fontWeight: tokens.sys.typography.label.fontWeight,
  };

  return (
    // `role` is spread-then-overridden so the variant-derived live-region role
    // always wins over an incidental caller-supplied role.
    <div ref={ref} style={rootStyle} {...rest} role={variant === 'danger' ? 'alert' : 'status'}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke[variant]}
        strokeWidth={STROKE_WIDTH}
        fillColor={c.bg}
        fillRendering="fill"
      />
      <span style={{ position: 'relative', display: 'inline-flex', color: c.icon[variant] }}>
        <Icon name={ICON[variant]} size="sm" />
      </span>
      <div style={{ position: 'relative', flex: 1, minWidth: 0 }}>
        {title !== undefined && <div style={titleStyle}>{title}</div>}
        {children !== undefined && <div>{children}</div>}
      </div>
      {onDismiss && (
        <button
          type="button"
          aria-label="Dismiss"
          onClick={onDismiss}
          style={{
            position: 'relative',
            display: 'inline-flex',
            padding: 0,
            border: 'none',
            background: 'transparent',
            color: c.text.body,
            cursor: 'pointer',
          }}
        >
          <Icon name="close" size="sm" />
        </button>
      )}
    </div>
  );
});
