// packages/web-components/src/components/avatar.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { ellipse } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, type PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Rendered diameter of a `<gh-avatar>`. */
export type GhAvatarSize = 'sm' | 'md' | 'lg';

/**
 * `<gh-avatar>` — a hand-drawn circular avatar.
 *
 * Shows an image when `src` loads, otherwise the initials derived from `name`,
 * otherwise an empty sketched circle. The sketchy ellipse outline comes from
 * `@ghds/sketch-core`; every colour, size and sketch parameter is token-driven
 * (`comp.avatar.*`). Exposed to assistive tech as an `img` with `name`/`alt`.
 */
@customElement('gh-avatar')
export class GhAvatar extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
        --_avatar-size: var(--comp-avatar-size-md);
        width: var(--_avatar-size);
        height: var(--_avatar-size);
      }

      :host([size='sm']) {
        --_avatar-size: var(--comp-avatar-size-sm);
      }

      :host([size='lg']) {
        --_avatar-size: var(--comp-avatar-size-lg);
      }

      .avatar {
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        box-sizing: border-box;
        width: 100%;
        height: 100%;
        overflow: hidden;
        border-radius: var(--sys-radius-pill);
        background: var(--comp-avatar-bg);
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-avatar-stroke);
        user-select: none;
      }

      .initials {
        position: relative;
        color: var(--comp-avatar-text);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
      }

      :host([size='sm']) .initials {
        font-size: var(--sys-typography-caption-fontSize);
      }

      :host([size='lg']) .initials {
        font-size: var(--sys-typography-body-fontSize);
      }

      img {
        position: relative;
        width: 100%;
        height: 100%;
        object-fit: cover;
        border-radius: inherit;
      }
    `,
  ];

  /** Rendered diameter. */
  @property({ type: String, reflect: true }) size: GhAvatarSize = 'md';
  /** Image URL. Falls back to initials, then an empty circle, on load failure. */
  @property({ type: String }) src = '';
  /** Name — used for the accessible label and the initials fallback. */
  @property({ type: String }) name = '';
  /** Overrides the accessible label (defaults to `name`). */
  @property({ type: String }) alt = '';

  @state() private imageFailed = false;

  private readonly internals: ElementInternals = this.attachInternals();

  private get initials(): string {
    const name = this.name.trim();
    if (!name) {
      return '';
    }
    const parts = name.split(/\s+/).filter(Boolean);
    const first = parts[0]?.charAt(0) ?? '';
    const last = parts.length > 1 ? (parts.at(-1)?.charAt(0) ?? '') : '';
    return (first + last).toUpperCase();
  }

  protected override willUpdate(changed: PropertyValues): void {
    // Retry a new image instead of stranding it behind the fallback: a fresh
    // `src` clears a prior load failure.
    if (changed.has('src')) {
      this.imageFailed = false;
    }
  }

  protected override updated(): void {
    const label = this.alt || this.name;
    if (label) {
      this.internals.role = 'img';
      this.internals.ariaLabel = label;
    } else {
      this.internals.role = null;
      this.internals.ariaLabel = null;
    }
  }

  private readonly handleError = (): void => {
    this.imageFailed = true;
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return ellipse(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.avatar.sketch.roughness,
      bowing: tokens.comp.avatar.sketch.bowing,
    };
  }

  protected override render(): unknown {
    const showImage = this.src !== '' && !this.imageFailed;
    return html`<span class="avatar" part="avatar">
      ${this.renderSketch()}
      ${
        showImage
          ? html`<img src=${this.src} alt="" @error=${this.handleError} />`
          : html`<span class="initials" aria-hidden="true">${this.initials}</span>`
      }
    </span>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-avatar': GhAvatar;
  }
}

// packages/react/src/components/Avatar.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes, useState } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Rendered diameter of an {@link Avatar}. */
export type AvatarSize = 'sm' | 'md' | 'lg';

export interface AvatarProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  /** Image URL. Falls back to initials (then an empty circle) if it fails to load. */
  src?: string;
  /** Person/entity name — used for the accessible label and the initials fallback. */
  name?: string;
  /** Overrides the accessible label (defaults to `name`). */
  alt?: string;
  /** Rendered diameter. Defaults to `'md'`. */
  size?: AvatarSize;
}

const avatar = tokens.comp.avatar;
const c = cssVars.comp.avatar;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

interface TypographyRole {
  readonly fontFamily: string;
  readonly fontSize: string;
  readonly lineHeight: number;
  readonly fontWeight: number;
}

const FONT: Record<AvatarSize, TypographyRole> = {
  sm: tokens.sys.typography.caption,
  md: tokens.sys.typography.label,
  lg: tokens.sys.typography.body,
};

/** First letters of the first and last whitespace-separated words, uppercased. */
export function initialsFrom(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) {
    return '';
  }
  const first = parts[0]?.charAt(0) ?? '';
  const last = parts.length > 1 ? (parts.at(-1)?.charAt(0) ?? '') : '';
  return (first + last).toUpperCase();
}

/**
 * A hand-drawn circular avatar. Shows an image when `src` loads, otherwise the
 * initials derived from `name`, otherwise an empty sketched circle. The sketchy
 * ellipse outline comes from `@ghds/sketch-core` (via {@link useSketch}); every
 * colour, size and sketch parameter is sourced from `@ghds/tokens`
 * (`comp.avatar.*`).
 */
export const Avatar = forwardRef<HTMLSpanElement, AvatarProps>(function Avatar(
  { src, name, alt, size = 'md', style, ...rest },
  forwardedRef,
) {
  // Track *which* src failed rather than a sticky boolean, so a new `src`
  // (e.g. a refreshed signed URL after the old one expired) is retried instead
  // of being stranded behind the initials fallback forever.
  const [failedSrc, setFailedSrc] = useState<string | undefined>(undefined);
  const {
    ref: sketchRef,
    drawable,
    size: measured,
  } = useSketch<HTMLSpanElement>({
    shape: 'ellipse',
    roughness: avatar.sketch.roughness,
    bowing: avatar.sketch.bowing,
    inset: INSET,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);
  const dimension = avatar.size[size];
  const label = alt ?? name;
  const showImage = src !== undefined && failedSrc !== src;
  const font = FONT[size];

  const rootStyle: CSSProperties = {
    // Scopes the `SketchSurface` (`z-index: -1`) to this avatar.
    ...sketchHostStyle,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    width: dimension,
    height: dimension,
    borderRadius: tokens.sys.radius.pill,
    overflow: 'hidden',
    flexShrink: 0,
    background: c.bg,
    color: c.text,
    fontFamily: font.fontFamily,
    fontSize: font.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(font.lineHeight),
    userSelect: 'none',
    ...style,
  };

  // A named avatar is an image landmark; an anonymous one is decorative.
  const a11y = label
    ? ({ role: 'img', 'aria-label': label } as const)
    : ({ 'aria-hidden': true } as const);

  return (
    <span ref={ref} style={rootStyle} {...a11y} {...rest}>
      <SketchSurface
        drawable={drawable}
        width={measured.width}
        height={measured.height}
        strokeColor={c.stroke}
        strokeWidth={STROKE_WIDTH}
      />
      {showImage ? (
        <img
          src={src}
          alt=""
          onError={() => setFailedSrc(src)}
          style={{
            position: 'relative',
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            borderRadius: 'inherit',
          }}
        />
      ) : (
        <span aria-hidden="true" style={{ position: 'relative' }}>
          {name ? initialsFrom(name) : null}
        </span>
      )}
    </span>
  );
});
