// packages/web-components/src/components/button.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, type PropertyValues } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

export type GhButtonVariant = 'primary' | 'danger' | 'neutral';
export type GhButtonType = 'button' | 'submit' | 'reset';

/**
 * `<gh-button>` — a hand-drawn button.
 *
 * The visible box is a sketchy rectangle outline from `@ghds/sketch-core`; a
 * real (focusable, keyboard-operable) `<button>` sits on top and owns the
 * semantics. Colors, padding and sketch roughness/bowing all come from
 * `comp.button.*` / `sys.*` tokens. Form-associated, so `type="submit"`/`"reset"`
 * drive the containing form.
 */
@customElement('gh-button')
export class GhButton extends SketchyBase {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...SketchyBase.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        color: var(--sys-color-bg-primary-default);
        cursor: pointer;
      }

      :host(:hover) {
        color: var(--sys-color-bg-primary-hover);
      }

      :host(:active) {
        color: var(--sys-color-bg-primary-active);
      }

      :host([variant='danger']) {
        color: var(--sys-color-bg-danger-default);
      }

      :host([variant='danger']:hover) {
        color: var(--sys-color-bg-danger-hover);
      }

      :host([variant='neutral']) {
        color: var(--sys-color-text-primary);
      }

      :host([variant='neutral']:hover) {
        color: var(--sys-color-text-link);
      }

      :host([disabled]) {
        color: var(--sys-color-text-disabled);
        cursor: not-allowed;
      }

      button {
        appearance: none;
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: var(--sys-spacing-sm);
        width: 100%;
        box-sizing: border-box;
        margin: 0;
        padding: var(--comp-button-padding-vertical) var(--comp-button-padding-horizontal);
        background: transparent;
        border: none;
        color: currentColor;
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
        cursor: inherit;
      }

      .label {
        position: relative;
        display: inline-flex;
        align-items: center;
        gap: var(--sys-spacing-sm);
      }

      button:focus-visible {
        outline: var(--sys-border-width-thick) solid var(--sys-color-border-focus);
        outline-offset: var(--sys-spacing-xs);
        border-radius: var(--sys-radius-sm);
      }

      button:disabled {
        cursor: not-allowed;
      }
    `,
  ];

  /** Visual/semantic colour role. */
  @property({ type: String, reflect: true }) variant: GhButtonVariant = 'primary';
  /** Native button behaviour for form association. */
  @property({ type: String }) type: GhButtonType = 'button';
  /** Disables interaction and dims the control. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  private readonly internals: ElementInternals = this.attachInternals();

  override connectedCallback(): void {
    super.connectedCallback();
    if (!this.hasAttribute('role')) {
      this.internals.role = 'button';
    }
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('disabled')) {
      this.internals.ariaDisabled = this.disabled ? 'true' : 'false';
    }
  }

  /** Button outline: a sketchy rectangle filling the measured box. */
  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  /** Roughness/bowing come from the button's own component tokens. */
  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.button.sketch.roughness,
      bowing: tokens.comp.button.sketch.bowing,
    };
  }

  private readonly handleClick = (event: MouseEvent): void => {
    if (this.disabled) {
      event.preventDefault();
      event.stopImmediatePropagation();
      return;
    }
    const form = this.internals.form;
    if (!form) {
      return;
    }
    if (this.type === 'submit') {
      form.requestSubmit();
    } else if (this.type === 'reset') {
      form.reset();
    }
  };

  protected override render(): unknown {
    return html`<button
      part="button"
      type=${this.type}
      ?disabled=${this.disabled}
      @click=${this.handleClick}
    >
      ${this.renderSketch()}
      <span class="label"><slot></slot></span>
    </button>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-button': GhButton;
  }
}

// packages/react/src/components/Button.tsx
import { tokens } from '@ghds/tokens';
import { Slot, Slottable } from '@radix-ui/react-slot';
import type React from 'react';
import { type ButtonHTMLAttributes, type CSSProperties, forwardRef, useState } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface } from './SketchSurface.js';

/** Visual intent of the button. */
export type ButtonVariant = 'primary' | 'danger' | 'neutral';

export interface ButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'color'> {
  /** Visual intent. Defaults to `'primary'`. */
  variant?: ButtonVariant;
  /**
   * Render as the single child element (Radix `Slot`) instead of a `<button>`,
   * e.g. to make a link look like a button while keeping its semantics.
   */
  asChild?: boolean;
}

// Sketch numerics + dimensions (theme-independent) come from the raw token
// object; colors come from `c` as CSS-variable references so dark mode applies.
const button = tokens.comp.button;
const c = cssVars.comp.button;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

interface ButtonColors {
  readonly stroke: string;
  readonly text: string;
  readonly fill?: string;
}

interface VariantTokens {
  readonly fill: { default: string; hover: string; active: string };
  readonly stroke: string;
  readonly text: string;
  /** Whether the resting state is filled (`primary`/`danger`) or outline (`neutral`). */
  readonly filledAtRest: boolean;
}

const VARIANTS: Record<ButtonVariant, VariantTokens> = {
  primary: {
    fill: { default: c.bg.primary.default, hover: c.bg.primary.hover, active: c.bg.primary.active },
    stroke: c.stroke.primary,
    text: c.text.primary,
    filledAtRest: true,
  },
  danger: {
    fill: { default: c.bg.danger.default, hover: c.bg.danger.hover, active: c.bg.danger.active },
    stroke: c.stroke.danger,
    text: c.text.danger,
    filledAtRest: true,
  },
  neutral: {
    fill: {
      default: c.bg.neutral.default,
      hover: c.bg.neutral.hover,
      active: c.bg.neutral.active,
    },
    stroke: c.stroke.neutral,
    text: c.text.neutral,
    filledAtRest: false,
  },
};

interface InteractionState {
  readonly hovered: boolean;
  readonly pressed: boolean;
}

function resolveColors(
  variant: ButtonVariant,
  state: InteractionState,
  disabled: boolean,
): ButtonColors {
  const v = VARIANTS[variant];
  if (disabled) {
    return {
      stroke: c.stroke.neutral,
      text: c.text.disabled,
      fill: variant === 'neutral' ? undefined : c.bg.primary.disabled,
    };
  }
  const fill = state.pressed ? v.fill.active : state.hovered ? v.fill.hover : v.fill.default;
  // Outline variants stay unfilled until hovered/pressed.
  const showFill = v.filledAtRest || state.hovered || state.pressed;
  return { stroke: v.stroke, text: v.text, fill: showFill ? fill : undefined };
}

/**
 * A hand-drawn button. Its sketchy outline + fill come from `@ghds/sketch-core`
 * (via {@link useSketch}); every color, padding, radius, typography and sketch
 * parameter is sourced from `@ghds/tokens` (`comp.button.*` / `sys.*`). The
 * accessible `<button>` (or a slotted element via `asChild`) carries all native
 * keyboard/focus behaviour; the SVG is purely decorative (`aria-hidden`).
 */
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  {
    variant = 'primary',
    asChild = false,
    children,
    disabled = false,
    style,
    onMouseEnter,
    onMouseLeave,
    onMouseDown,
    onMouseUp,
    onBlur,
    onFocus,
    type,
    ...rest
  },
  forwardedRef,
) {
  const [state, setState] = useState<InteractionState>({ hovered: false, pressed: false });
  const [focused, setFocused] = useState(false);

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLButtonElement>({
    fillStyle: 'solid',
    roughness: button.sketch.roughness,
    bowing: button.sketch.bowing,
    inset: INSET,
  });

  const colors = resolveColors(variant, state, disabled);

  const rootStyle: CSSProperties = {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    padding: `${button.padding.vertical} ${button.padding.horizontal}`,
    border: 'none',
    background: 'transparent',
    appearance: 'none',
    cursor: disabled ? 'not-allowed' : 'pointer',
    color: colors.text,
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.label.lineHeight),
    outline: focused ? `${STROKE_WIDTH}px solid ${c.focus.ring}` : 'none',
    outlineOffset: tokens.sys.spacing.xs,
    ...style,
  };

  const surface = (
    <SketchSurface
      drawable={drawable}
      width={size.width}
      height={size.height}
      strokeColor={colors.stroke}
      strokeWidth={STROKE_WIDTH}
      fillColor={colors.fill}
      fillRendering="fill"
    />
  );

  const handlers = {
    onMouseEnter: (event: React.MouseEvent<HTMLButtonElement>) => {
      setState((s) => ({ ...s, hovered: true }));
      onMouseEnter?.(event);
    },
    onMouseLeave: (event: React.MouseEvent<HTMLButtonElement>) => {
      setState({ hovered: false, pressed: false });
      onMouseLeave?.(event);
    },
    onMouseDown: (event: React.MouseEvent<HTMLButtonElement>) => {
      setState((s) => ({ ...s, pressed: true }));
      onMouseDown?.(event);
    },
    onMouseUp: (event: React.MouseEvent<HTMLButtonElement>) => {
      setState((s) => ({ ...s, pressed: false }));
      onMouseUp?.(event);
    },
    onFocus: (event: React.FocusEvent<HTMLButtonElement>) => {
      setFocused(true);
      onFocus?.(event);
    },
    onBlur: (event: React.FocusEvent<HTMLButtonElement>) => {
      setFocused(false);
      setState({ hovered: false, pressed: false });
      onBlur?.(event);
    },
  };

  const ref = mergeRefs(sketchRef, forwardedRef);

  if (asChild) {
    return (
      <Slot
        ref={ref}
        style={rootStyle}
        data-variant={variant}
        aria-disabled={disabled || undefined}
        {...handlers}
        {...rest}
      >
        {surface}
        <Slottable>{children}</Slottable>
      </Slot>
    );
  }

  return (
    <button
      ref={ref}
      type={type ?? 'button'}
      style={rootStyle}
      data-variant={variant}
      disabled={disabled}
      {...handlers}
      {...rest}
    >
      {surface}
      <span style={{ position: 'relative' }}>{children}</span>
    </button>
  );
});
