// packages/web-components/src/components/direction.ts
import { css, html, LitElement, type PropertyValues } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/** Reading direction of the UI. */
export type GhDirectionValue = 'ltr' | 'rtl';

/**
 * `<gh-direction>` — propagates a reading direction (`ltr` / `rtl`) to its
 * slotted subtree by mirroring the value onto the host's own `dir` attribute,
 * so descendant GHDS components and CSS logical properties resolve against it.
 *
 * Behavioral only — it renders no visible box and owns no design values, so
 * there is no sketch layer (it extends `LitElement`, not `SketchyBase`).
 */
@customElement('gh-direction')
export class GhDirection extends LitElement {
  static override styles = css`
    :host {
      display: contents;
    }
  `;

  /** Reading direction applied to the slotted subtree. Defaults to `'ltr'`. */
  @property({ type: String, reflect: true }) override dir: GhDirectionValue = 'ltr';

  protected override updated(changed: PropertyValues): void {
    if (changed.has('dir')) {
      // Mirror onto the actual DOM attribute so logical properties inherit it.
      this.setAttribute('dir', this.dir);
    }
  }

  protected override render(): unknown {
    return html`<slot></slot>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-direction': GhDirection;
  }
}

// packages/react/src/components/Direction.tsx
import { createContext, type ReactNode, useContext } from 'react';

/** Reading direction of the UI. */
export type Direction = 'ltr' | 'rtl';

const DirectionContext = createContext<Direction>('ltr');

export interface DirectionProviderProps {
  /** Reading direction applied to all descendant GHDS components. */
  dir: Direction;
  children?: ReactNode;
}

/**
 * Propagates a reading direction (`ltr` / `rtl`) to descendant GHDS components
 * through React context. Behavioral only — it renders no DOM element and owns
 * no design values, so there is no sketch layer.
 *
 * Set the matching `dir` attribute on your document/root element for CSS logical
 * properties to resolve; this provider lets components read the value in JS
 * (via {@link useDirection}) without each one inspecting the DOM.
 */
export function DirectionProvider({ dir, children }: DirectionProviderProps) {
  return <DirectionContext.Provider value={dir}>{children}</DirectionContext.Provider>;
}

/**
 * Reads the nearest ancestor {@link DirectionProvider}'s direction. Returns
 * `'ltr'` when no provider is present.
 */
export function useDirection(): Direction {
  return useContext(DirectionContext);
}
