// packages/web-components/src/components/kbd.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/**
 * `<gh-kbd>` — a hand-drawn keyboard key.
 *
 * Wraps slotted key text in a small sketchy, solid-filled box
 * (`@ghds/sketch-core`). Rendered as an inline `<kbd>` element. Colours, padding
 * and sketch parameters come from `@ghds/tokens` (`comp.kbd.*`).
 */
@customElement('gh-kbd')
export class GhKbd extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
        color: var(--comp-kbd-stroke);
        vertical-align: middle;
      }

      kbd {
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        box-sizing: border-box;
        min-width: 1.5em;
        padding: var(--comp-kbd-padding-vertical) var(--comp-kbd-padding-horizontal);
        color: var(--comp-kbd-text);
        font-family: var(--sys-typography-caption-fontFamily);
        font-size: var(--sys-typography-caption-fontSize);
        line-height: var(--sys-typography-caption-lineHeight);
      }

      .label {
        position: relative;
      }

      .sketch-fill {
        fill: var(--comp-kbd-bg);
        stroke: none;
      }
    `,
  ];

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.kbd.sketch.roughness,
      bowing: tokens.comp.kbd.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return html`<kbd part="key">
      ${this.renderSketch()}
      <span class="label"><slot></slot></span>
    </kbd>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-kbd': GhKbd;
  }
}

// packages/react/src/components/Kbd.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface KbdProps extends HTMLAttributes<HTMLElement> {}

const kbd = tokens.comp.kbd;
const c = cssVars.comp.kbd;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

/**
 * A hand-drawn keyboard key. Renders a `<kbd>` with a sketchy outline + fill
 * (`@ghds/sketch-core`); every colour, padding and sketch parameter comes from
 * `@ghds/tokens` (`comp.kbd.*`). The SVG is decorative (`aria-hidden`); the
 * `<kbd>` element carries the semantics.
 */
export const Kbd = forwardRef<HTMLElement, KbdProps>(function Kbd(
  { children, style, ...rest },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLElement>({
    fillStyle: 'solid',
    roughness: kbd.sketch.roughness,
    bowing: kbd.sketch.bowing,
    inset: INSET,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    minWidth: '1.5em',
    padding: `${kbd.padding.vertical} ${kbd.padding.horizontal}`,
    color: c.text,
    fontFamily: tokens.sys.typography.code.fontFamily,
    fontSize: tokens.sys.typography.caption.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: 1,
    whiteSpace: 'nowrap',
    ...style,
  };

  return (
    <kbd ref={ref} style={rootStyle} {...rest}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke}
        strokeWidth={STROKE_WIDTH}
        fillColor={c.bg}
        fillRendering="fill"
      />
      <span style={{ position: 'relative' }}>{children}</span>
    </kbd>
  );
});
