// packages/web-components/src/components/label.ts
import { css, html, LitElement, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/**
 * `<gh-label>` — a form field label.
 *
 * Renders a `<label>` around its slotted content. When `for` names an element,
 * clicking the label focuses/activates that control (resolved against the
 * document so it works across the shadow boundary). Typography comes from
 * `sys.typography.label`; colours from `@ghds/tokens` (`comp.label.*`).
 */
@customElement('gh-label')
export class GhLabel extends LitElement {
  static override styles = css`
    :host {
      display: inline-flex;
      align-items: center;
      gap: var(--comp-label-gap);
      color: var(--comp-label-text-default);
      font-family: var(--sys-typography-label-fontFamily);
      font-size: var(--sys-typography-label-fontSize);
      font-weight: var(--sys-typography-label-fontWeight);
      line-height: var(--sys-typography-label-lineHeight);
      cursor: default;
    }

    :host([disabled]) {
      color: var(--comp-label-text-disabled);
      cursor: not-allowed;
    }

    label {
      display: inline-flex;
      align-items: center;
      gap: var(--comp-label-gap);
      color: inherit;
      font: inherit;
      cursor: inherit;
    }
  `;

  /** Id of the control this label describes (resolved against the document). */
  @property({ type: String }) for = '';
  /** Dims the label and blocks its click-to-focus behaviour. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  private readonly onClick = (): void => {
    if (this.disabled || !this.for) {
      return;
    }
    const target = this.ownerDocument.getElementById(this.for) as
      | (HTMLElement & { focus?: () => void; click?: () => void })
      | null;
    if (!target) {
      return;
    }
    target.focus?.();
    if (
      target instanceof HTMLInputElement &&
      (target.type === 'checkbox' || target.type === 'radio')
    ) {
      target.click();
    }
  };

  protected override render(): unknown {
    return html`<label for=${this.for || nothing} @click=${this.onClick}><slot></slot></label>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-label': GhLabel;
  }
}

// packages/react/src/components/Label.tsx
import { tokens } from '@ghds/tokens';
import { Label as RadixLabel } from '@radix-ui/react-label';
import { type ComponentPropsWithoutRef, type CSSProperties, forwardRef } from 'react';
import { cssVars } from '../lib/cssVars.js';

export interface LabelProps extends ComponentPropsWithoutRef<typeof RadixLabel> {
  /** Renders the label in its disabled colour when `true`. */
  disabled?: boolean;
}

const c = cssVars.comp.label;

/**
 * A form label. Wraps Radix `Label` so clicking it focuses/activates the
 * associated control (`htmlFor`, or a nested control). Typography comes from
 * `sys.typography.label` and colour from `@ghds/tokens` (`comp.label.*`). Not
 * sketchy — it is plain text that accompanies a hand-drawn control.
 */
export const Label = forwardRef<HTMLLabelElement, LabelProps>(function Label(
  { disabled = false, style, ...rest },
  forwardedRef,
) {
  const labelStyle: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: c.gap,
    color: disabled ? c.text.disabled : c.text.default,
    cursor: disabled ? 'not-allowed' : 'default',
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.label.lineHeight),
    ...style,
  };

  return (
    <RadixLabel
      ref={forwardedRef}
      data-disabled={disabled || undefined}
      style={labelStyle}
      {...rest}
    />
  );
});
