// packages/web-components/src/components/marker.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Highlight tone of a `<gh-marker>`. */
export type GhMarkerVariant = 'default' | 'success' | 'info' | 'danger';

/**
 * `<gh-marker>` — a hand-drawn highlighter.
 *
 * Wraps inline slotted text in a semantic `<mark>` and paints a sketchy hachure
 * scribble (`@ghds/sketch-core`) behind it — a fill with no hard box — so the
 * words stay readable through the highlight. The highlight colour comes from
 * `comp.marker.color.<variant>`; the text colour is inherited, never set.
 */
@customElement('gh-marker')
export class GhMarker extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline;
        position: relative;
        /* A little horizontal breathing room so the scribble overshoots the glyphs. */
        padding: 0 var(--sys-spacing-xs);
        /* Paints the hachure fill lines; text colour stays inherited. */
        --ghds-sketch-fill-color: var(--comp-marker-color-default);
      }

      :host([variant='success']) {
        --ghds-sketch-fill-color: var(--comp-marker-color-success);
      }

      :host([variant='info']) {
        --ghds-sketch-fill-color: var(--comp-marker-color-info);
      }

      :host([variant='danger']) {
        --ghds-sketch-fill-color: var(--comp-marker-color-danger);
      }

      /* Highlighter strokes read thicker than a regular fill. */
      .sketch-fill {
        stroke-width: var(--sys-border-width-thick);
      }

      mark {
        position: relative;
        background: transparent;
        color: inherit;
      }
    `,
  ];

  /** Highlight colour. Defaults to `'default'` (a warm highlighter yellow). */
  @property({ type: String, reflect: true }) variant: GhMarkerVariant = 'default';

  /** A hachure-filled rectangle with the outline box stripped — fill only. */
  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    const drawable = rectangle(0, 0, width, height, options);
    return { ...drawable, strokePaths: [] };
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.marker.sketch.roughness,
      bowing: tokens.comp.marker.sketch.bowing,
      fillStyle: 'hachure',
      hachureGap: tokens.sys.sketch.hachureGap,
      hachureAngle: tokens.sys.sketch.hachureAngle,
    };
  }

  protected override render(): unknown {
    return html`${this.renderSketch()}<mark part="mark"><slot></slot></mark>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-marker': GhMarker;
  }
}

// packages/react/src/components/Marker.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Highlight tone of a {@link Marker}. */
export type MarkerVariant = 'default' | 'success' | 'info' | 'danger';

export interface MarkerProps extends HTMLAttributes<HTMLElement> {
  /** Highlight colour. Defaults to `'default'` (a warm highlighter yellow). */
  variant?: MarkerVariant;
}

const c = cssVars.comp.marker;
const FILL_STROKE_WIDTH = toPx(tokens.sys.border.width.thick);

/**
 * A hand-drawn highlighter. Wraps inline text in a semantic `<mark>` and paints
 * a sketchy hachure stroke behind it (`@ghds/sketch-core`), so the words stay
 * readable through the scribble. The highlight colour comes from
 * `@ghds/tokens` (`comp.marker.*`); the text colour is inherited, never set.
 */
export const Marker = forwardRef<HTMLElement, MarkerProps>(function Marker(
  { variant = 'default', children, style, ...rest },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLElement>({
    fillStyle: 'hachure',
    roughness: tokens.comp.marker.sketch.roughness,
    bowing: tokens.comp.marker.sketch.bowing,
    hachureGap: tokens.sys.sketch.hachureGap,
    hachureAngle: tokens.sys.sketch.hachureAngle,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline',
    background: 'transparent',
    color: 'inherit',
    // A little horizontal breathing room so the scribble overshoots the glyphs.
    padding: `0 ${tokens.sys.spacing.xs}`,
    ...style,
  };

  return (
    <mark ref={ref} style={rootStyle} {...rest}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.color[variant]}
        strokeWidth={FILL_STROKE_WIDTH}
        fillColor={c.color[variant]}
        fillRendering="stroke"
        fillStrokeWidth={FILL_STROKE_WIDTH}
      />
      <span style={{ position: 'relative' }}>{children}</span>
    </mark>
  );
});
