// packages/web-components/src/components/message.ts
import { css, html, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/** Which side of the conversation a `<gh-message>` sits on. */
export type GhMessageSide = 'received' | 'sent';

/**
 * `<gh-message>` — a hand-drawn chat message row.
 *
 * Lays out an optional leading avatar (`avatar` slot) and a content column: an
 * author/timestamp header (`author` / `timestamp` slots) above the message body
 * (default slot, typically a `<gh-bubble>`). `side` flips the row so outgoing
 * (`'sent'`) messages align to the end. Spacing and the header text colours come
 * from `comp.message.*` tokens.
 */
@customElement('gh-message')
export class GhMessage extends LitElement {
  static override styles = css`
    :host {
      display: block;
    }

    .row {
      display: flex;
      flex-direction: row;
      align-items: flex-start;
      gap: var(--comp-message-rowGap);
    }

    :host([side='sent']) .row {
      flex-direction: row-reverse;
    }

    .avatar {
      display: flex;
      flex-shrink: 0;
    }

    .content {
      display: flex;
      flex-direction: column;
      gap: var(--comp-message-gap);
      min-width: 0;
    }

    .header {
      display: flex;
      align-items: baseline;
      gap: var(--sys-spacing-sm);
    }

    ::slotted([slot='author']) {
      color: var(--comp-message-text-author);
      font-family: var(--sys-typography-label-fontFamily);
      font-size: var(--sys-typography-label-fontSize);
      font-weight: var(--sys-typography-label-fontWeight);
      line-height: var(--sys-typography-label-lineHeight);
    }

    ::slotted([slot='timestamp']) {
      color: var(--comp-message-text-timestamp);
      font-family: var(--sys-typography-caption-fontFamily);
      font-size: var(--sys-typography-caption-fontSize);
      font-weight: var(--sys-typography-caption-fontWeight);
      line-height: var(--sys-typography-caption-lineHeight);
    }
  `;

  /** `'received'` (default) aligns to the start; `'sent'` aligns to the end. */
  @property({ type: String, reflect: true }) side: GhMessageSide = 'received';

  protected override render(): unknown {
    return html`<div class="row" part="row">
      <div class="avatar" part="avatar"><slot name="avatar"></slot></div>
      <div class="content" part="content">
        <div class="header" part="header">
          <slot name="author"></slot>
          <slot name="timestamp"></slot>
        </div>
        <slot></slot>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-message': GhMessage;
  }
}

// packages/react/src/components/Message.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes } from 'react';
import { cssVars } from '../lib/cssVars.js';

/** Which side of the conversation a {@link Message} sits on. */
export type MessageSide = 'received' | 'sent';

export interface MessageProps extends HTMLAttributes<HTMLDivElement> {
  /** `'received'` (default) aligns to the start; `'sent'` aligns to the end. */
  side?: MessageSide;
}

const message = tokens.comp.message;
const c = cssVars.comp.message;

/**
 * A hand-drawn chat message row: an optional {@link MessageAvatar}, then a
 * {@link MessageContent} column (author + timestamp header and a
 * {@link Bubble}). `side` flips the layout so outgoing messages align to the
 * end. Spacing and text colours come from `@ghds/tokens` (`comp.message.*`).
 */
export const Message = forwardRef<HTMLDivElement, MessageProps>(function Message(
  { side = 'received', children, style, ...rest },
  forwardedRef,
) {
  const rootStyle: CSSProperties = {
    display: 'flex',
    flexDirection: side === 'sent' ? 'row-reverse' : 'row',
    alignItems: 'flex-start',
    gap: message.rowGap,
    ...style,
  };
  return (
    <div ref={forwardedRef} style={rootStyle} {...rest}>
      {children}
    </div>
  );
});

/** Leading avatar slot for a {@link Message}. */
export const MessageAvatar = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function MessageAvatar({ children, style, ...rest }, forwardedRef) {
    const avatarStyle: CSSProperties = {
      display: 'flex',
      flexShrink: 0,
      ...style,
    };
    return (
      <div ref={forwardedRef} style={avatarStyle} {...rest}>
        {children}
      </div>
    );
  },
);

/** The stacked content column (header + bubble) of a {@link Message}. */
export const MessageContent = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function MessageContent({ children, style, ...rest }, forwardedRef) {
    const contentStyle: CSSProperties = {
      display: 'flex',
      flexDirection: 'column',
      gap: message.gap,
      minWidth: 0,
      ...style,
    };
    return (
      <div ref={forwardedRef} style={contentStyle} {...rest}>
        {children}
      </div>
    );
  },
);

/** The author name shown above a message's bubble. */
export const MessageAuthor = forwardRef<HTMLSpanElement, HTMLAttributes<HTMLSpanElement>>(
  function MessageAuthor({ children, style, ...rest }, forwardedRef) {
    const authorStyle: CSSProperties = {
      color: c.text.author,
      fontFamily: tokens.sys.typography.label.fontFamily,
      fontSize: tokens.sys.typography.label.fontSize,
      fontWeight: tokens.sys.typography.label.fontWeight,
      lineHeight: String(tokens.sys.typography.label.lineHeight),
      ...style,
    };
    return (
      <span ref={forwardedRef} style={authorStyle} {...rest}>
        {children}
      </span>
    );
  },
);

/** The timestamp shown alongside the author of a message. */
export const MessageTimestamp = forwardRef<HTMLSpanElement, HTMLAttributes<HTMLSpanElement>>(
  function MessageTimestamp({ children, style, ...rest }, forwardedRef) {
    const timestampStyle: CSSProperties = {
      color: c.text.timestamp,
      fontFamily: tokens.sys.typography.caption.fontFamily,
      fontSize: tokens.sys.typography.caption.fontSize,
      fontWeight: tokens.sys.typography.caption.fontWeight,
      lineHeight: String(tokens.sys.typography.caption.lineHeight),
      ...style,
    };
    return (
      <span ref={forwardedRef} style={timestampStyle} {...rest}>
        {children}
      </span>
    );
  },
);
