// packages/web-components/src/components/modal.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

let modalUid = 0;

/**
 * `<gh-modal>` — a hand-drawn modal dialog.
 *
 * Built on the native `<dialog>` element (`showModal()`), which provides focus
 * trapping, focus restoration, the top layer, and Escape-to-close for free; the
 * `::backdrop` is styled as the token scrim and the panel is a sketchy box
 * (`@ghds/sketch-core`). Reflects `open` and dispatches a `close` `CustomEvent`
 * on Escape / backdrop click / dialog close. Colours and sketch parameters come
 * from `@ghds/tokens` (`comp.modal.*`).
 */
@customElement('gh-modal')
export class GhModal extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        color: var(--comp-modal-panel-stroke);
      }

      dialog {
        position: relative;
        box-sizing: border-box;
        max-width: 32rem;
        width: 100%;
        padding: var(--comp-modal-panel-padding);
        border: none;
        background: transparent;
        color: var(--comp-modal-text-body);
        overflow: visible;
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        line-height: var(--sys-typography-body-lineHeight);
      }

      dialog::backdrop {
        background: var(--comp-modal-scrim-color);
        opacity: var(--comp-modal-scrim-opacity);
      }

      .title {
        position: relative;
        margin: 0 0 var(--comp-modal-panel-gap);
        color: var(--comp-modal-text-title);
        font-family: var(--sys-typography-title-fontFamily);
        font-size: var(--sys-typography-title-fontSize);
        font-weight: var(--sys-typography-title-fontWeight);
        line-height: var(--sys-typography-title-lineHeight);
      }

      .body {
        position: relative;
      }

      .sketch-fill {
        fill: var(--comp-modal-panel-bg);
        stroke: none;
      }
    `,
  ];

  /** Whether the dialog is shown. */
  @property({ type: Boolean, reflect: true }) open = false;
  /** Accessible title, rendered as a heading and wired to `aria-labelledby`. */
  @property({ type: String }) heading = '';
  /** Close when the backdrop is clicked. */
  @property({ type: Boolean }) closeOnScrimClick = true;

  @query('dialog') private dialogEl?: HTMLDialogElement;

  private readonly titleId = `gh-modal-${modalUid++}-title`;

  protected override get frame(): HTMLElement {
    return this.dialogEl ?? this;
  }

  protected override updated(changed: PropertyValues): void {
    if (!changed.has('open')) {
      return;
    }
    const dialog = this.dialogEl;
    if (!dialog) {
      return;
    }
    if (this.open && !dialog.open) {
      try {
        dialog.showModal();
      } catch {
        // jsdom / unsupported environments: fall back to the non-modal open state.
        dialog.setAttribute('open', '');
      }
      this.measure();
    } else if (!this.open && dialog.open) {
      dialog.close();
    }
  }

  private readonly requestClose = (): void => {
    this.dispatchEvent(new CustomEvent('close', { bubbles: true, composed: true }));
  };

  private readonly onCancel = (event: Event): void => {
    // Let the consumer own `open`: prevent the native auto-close and ask to close.
    event.preventDefault();
    this.requestClose();
  };

  private readonly onDialogClick = (event: MouseEvent): void => {
    if (!this.closeOnScrimClick) {
      return;
    }
    // The <dialog> element is itself the padded panel, so `target === dialog` is
    // true for clicks in the panel's own padding too. Treat only clicks that
    // land outside the dialog's box (i.e. on the ::backdrop) as a scrim click.
    const dialog = this.dialogEl;
    if (!dialog || event.target !== dialog) {
      return;
    }
    const rect = dialog.getBoundingClientRect();
    const inside =
      event.clientX >= rect.left &&
      event.clientX <= rect.right &&
      event.clientY >= rect.top &&
      event.clientY <= rect.bottom;
    if (!inside) {
      this.requestClose();
    }
  };

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.modal.sketch.roughness,
      bowing: tokens.comp.modal.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return html`<dialog
      aria-labelledby=${this.heading ? this.titleId : nothing}
      @cancel=${this.onCancel}
      @click=${this.onDialogClick}
    >
      ${this.renderSketch()}
      ${this.heading ? html`<h2 class="title" id=${this.titleId}>${this.heading}</h2>` : nothing}
      <div class="body"><slot></slot></div>
    </dialog>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-modal': GhModal;
  }
}

// packages/react/src/components/Modal.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, type ReactNode, useEffect, useId, useRef } from 'react';
import { createPortal } from 'react-dom';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface ModalProps {
  /** Whether the dialog is shown. */
  open: boolean;
  /** Called when the user requests to close (scrim click, Escape). */
  onClose: () => void;
  /** Accessible title, rendered as a heading and wired to `aria-labelledby`. */
  title?: string;
  /** Dialog body. */
  children?: ReactNode;
  /** Close when the scrim is clicked. Defaults to `true`. */
  closeOnScrimClick?: boolean;
}

const modal = tokens.comp.modal;
const c = cssVars.comp.modal;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
const FOCUSABLE =
  'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';

/**
 * A hand-drawn modal dialog. Renders through a portal on `document.body` with a
 * scrim, a sketchy panel (`@ghds/sketch-core`), `role="dialog"` +
 * `aria-modal="true"`, focus trapping (Tab cycles within the dialog), focus
 * restoration to the previously-focused element on close, Escape-to-close, and
 * body scroll lock. Colours and sketch parameters come from `@ghds/tokens`
 * (`comp.modal.*`).
 */
export function Modal({ open, onClose, title, children, closeOnScrimClick = true }: ModalProps) {
  const titleId = useId();
  const panelRef = useRef<HTMLDivElement>(null);
  const previousFocus = useRef<HTMLElement | null>(null);

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: modal.sketch.roughness,
    bowing: modal.sketch.bowing,
    inset: INSET,
  });
  const ref = mergeRefs(panelRef, sketchRef);

  useEffect(() => {
    if (!open) {
      return;
    }
    previousFocus.current = (document.activeElement as HTMLElement) ?? null;
    const panel = panelRef.current;
    const focusables = panel?.querySelectorAll<HTMLElement>(FOCUSABLE);
    (focusables && focusables.length > 0 ? focusables[0] : panel)?.focus();

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    return () => {
      document.body.style.overflow = previousOverflow;
      previousFocus.current?.focus?.();
    };
  }, [open]);

  if (!open) {
    return null;
  }

  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Escape') {
      event.stopPropagation();
      onClose();
      return;
    }
    if (event.key !== 'Tab') {
      return;
    }
    const panel = panelRef.current;
    if (!panel) {
      return;
    }
    const focusables = [...panel.querySelectorAll<HTMLElement>(FOCUSABLE)];
    if (focusables.length === 0) {
      // Nothing focusable inside — keep focus on the dialog.
      event.preventDefault();
      return;
    }
    const first = focusables[0];
    const last = focusables[focusables.length - 1];
    const active = document.activeElement;
    // The panel itself (tabIndex=-1) receives focus when a non-focusable body
    // element is clicked; treat it like the pre-first position so Shift+Tab
    // wraps to the end instead of escaping the portal.
    if (event.shiftKey && (active === first || active === panel)) {
      event.preventDefault();
      last?.focus();
    } else if (!event.shiftKey && active === last) {
      event.preventDefault();
      first?.focus();
    }
  };

  const overlayStyle: CSSProperties = {
    position: 'fixed',
    inset: 0,
    zIndex: modal.zIndex,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: tokens.sys.spacing.lg,
  };

  const scrimStyle: CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: c.scrim.color,
    opacity: modal.scrim.opacity,
  };

  const panelStyle: CSSProperties = {
    ...sketchHostStyle,
    position: 'relative',
    boxSizing: 'border-box',
    maxWidth: '32rem',
    width: '100%',
    maxHeight: '90vh',
    overflow: 'auto',
    padding: modal.panel.padding,
    color: c.text.body,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
  };

  const titleStyle: CSSProperties = {
    position: 'relative',
    margin: `0 0 ${modal.panel.gap}`,
    color: c.text.title,
    fontFamily: tokens.sys.typography.title.fontFamily,
    fontSize: tokens.sys.typography.title.fontSize,
    fontWeight: tokens.sys.typography.title.fontWeight,
    lineHeight: String(tokens.sys.typography.title.lineHeight),
  };

  return createPortal(
    // biome-ignore lint/a11y/noStaticElementInteractions: keydown here only traps Tab / forwards Escape for the dialog; the dialog itself owns focus
    <div style={overlayStyle} onKeyDown={handleKeyDown}>
      <div
        style={scrimStyle}
        aria-hidden="true"
        onClick={closeOnScrimClick ? onClose : undefined}
      />
      <div
        ref={ref}
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? titleId : undefined}
        tabIndex={-1}
        style={panelStyle}
      >
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={c.panel.stroke}
          strokeWidth={STROKE_WIDTH}
          fillColor={c.panel.bg}
          fillRendering="fill"
        />
        {title && (
          <h2 id={titleId} style={titleStyle}>
            {title}
          </h2>
        )}
        <div style={{ position: 'relative' }}>{children}</div>
      </div>
    </div>,
    document.body,
  );
}
