// packages/web-components/src/components/select.ts
import {
  autoUpdate,
  computePosition,
  flip,
  offset,
  shift,
  size as sizeMiddleware,
} from '@floating-ui/dom';
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';
import './icon.js';
import { type GhSelectListbox, type GhSelectOption, getSelectOptionId } from './select-listbox.js';
import './select-listbox.js';

export type { GhSelectOption };

let selectIdCounter = 0;
const TYPEAHEAD_RESET_MS = 500;

/**
 * `<gh-select>` — a hand-drawn, form-associated single-select dropdown.
 *
 * The trigger is a real `<button>`; the listbox panel (`<gh-select-listbox>`)
 * and its keyboard/typeahead model are hand-implemented, following the
 * WAI-ARIA "select-only combobox" pattern (`role="combobox"` trigger,
 * `role="listbox"` panel, `aria-activedescendant` roving highlight — real DOM
 * focus never leaves the trigger). Options are supplied as a plain data array
 * (`options`), not slotted children — light DOM has no context mechanism to
 * bridge selection state to slotted `<gh-select-option>` elements the way
 * React's children composition can.
 */
@customElement('gh-select')
export class GhSelect extends SketchyBase {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...SketchyBase.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        color: var(--comp-select-trigger-stroke-default);
      }

      :host(:hover) {
        color: var(--comp-select-trigger-stroke-hover);
      }

      :host(:focus-within) {
        color: var(--comp-select-trigger-stroke-focus);
      }

      :host([disabled]) {
        color: var(--comp-select-trigger-stroke-disabled);
      }

      .field {
        display: flex;
        flex-direction: column;
        gap: var(--sys-spacing-xs);
      }

      label {
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
        color: var(--sys-color-text-secondary);
      }

      .trigger {
        position: relative;
        box-sizing: border-box;
        width: 100%;
        margin: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--comp-select-trigger-gap);
        padding: var(--comp-select-trigger-padding-vertical) var(--comp-select-trigger-padding-horizontal);
        background: transparent;
        border: none;
        outline: none;
        color: var(--comp-select-trigger-text-value);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        font-weight: var(--sys-typography-body-fontWeight);
        line-height: var(--sys-typography-body-lineHeight);
        cursor: pointer;
      }

      .trigger:disabled {
        color: var(--comp-select-trigger-text-disabled);
        cursor: not-allowed;
      }

      .placeholder {
        color: var(--comp-select-trigger-text-placeholder);
      }

      .chevron {
        flex-shrink: 0;
        transition: transform var(--sys-animation-duration-fast) var(--sys-animation-easing-standard);
      }

      :host([data-open]) .chevron {
        transform: rotate(180deg);
      }
    `,
  ];

  /** The selectable options. */
  @property({ type: Array }) options: GhSelectOption[] = [];
  /** Current field value. Mirrored to the form value. */
  @property({ type: String, reflect: true }) value = '';
  /** Submitted control name. */
  @property({ type: String }) name = '';
  /** Shown when nothing is selected. */
  @property({ type: String }) placeholder = '';
  /** Optional visible label, also the accessible name. */
  @property({ type: String }) label = '';
  /** Disables interaction and form participation. */
  @property({ type: Boolean, reflect: true }) disabled = false;

  @state() private open = false;
  @state() private highlightedValue = '';

  @query('.trigger') private triggerEl!: HTMLButtonElement;
  @query('gh-select-listbox') private listboxEl!: GhSelectListbox;

  private readonly internals: ElementInternals = this.attachInternals();
  private readonly selectId = `gh-select-${++selectIdCounter}`;
  // Captured once on first render — the authored `value`, restored by
  // `formResetCallback`, matching native reset behavior.
  private defaultValue = '';
  private cleanupAutoUpdate: (() => void) | undefined;
  private readonly typeahead: {
    buffer: string;
    timeout: ReturnType<typeof setTimeout> | undefined;
  } = {
    buffer: '',
    timeout: undefined,
  };

  protected override get frame(): HTMLElement {
    return this.triggerEl ?? this;
  }

  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.select.sketch.roughness,
      bowing: tokens.comp.select.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  private enabledOptions(): GhSelectOption[] {
    return this.options.filter((option) => !option.disabled);
  }

  private openWithInitialHighlight(): void {
    this.open = true;
    const enabled = this.enabledOptions();
    if (enabled.length === 0) {
      return;
    }
    const selected = enabled.some((option) => option.value === this.value)
      ? this.value
      : enabled[0]?.value;
    this.highlightedValue = selected ?? '';
  }

  private highlightAt(position: 'first' | 'last'): void {
    const enabled = this.enabledOptions();
    if (enabled.length === 0) {
      return;
    }
    this.highlightedValue =
      (position === 'first' ? enabled[0]?.value : enabled[enabled.length - 1]?.value) ?? '';
  }

  private moveHighlight(direction: 1 | -1): void {
    const enabled = this.enabledOptions();
    if (enabled.length === 0) {
      return;
    }
    const currentIndex = enabled.findIndex((option) => option.value === this.highlightedValue);
    const nextIndex = Math.min(Math.max(currentIndex + direction, 0), enabled.length - 1);
    this.highlightedValue = enabled[nextIndex]?.value ?? '';
  }

  private selectValue(nextValue: string): void {
    this.value = nextValue;
    this.open = false;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
    this.triggerEl?.focus();
  }

  private readonly handleOptionSelect = (event: Event): void => {
    const { value: nextValue } = (event as CustomEvent<{ value: string }>).detail;
    this.selectValue(nextValue);
  };

  private readonly handleOptionHighlight = (event: Event): void => {
    this.highlightedValue = (event as CustomEvent<{ value: string }>).detail.value;
  };

  private readonly handleTriggerClick = (): void => {
    if (this.disabled) {
      return;
    }
    this.open = !this.open;
  };

  private readonly handleOutsidePointerDown = (event: PointerEvent): void => {
    if (!this.open) {
      return;
    }
    const path = event.composedPath();
    if (!path.includes(this) && !path.includes(this.listboxEl)) {
      this.open = false;
    }
  };

  private readonly handleKeyDown = (event: KeyboardEvent): void => {
    if (this.disabled) {
      return;
    }
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (this.open) {
          this.moveHighlight(1);
        } else {
          this.openWithInitialHighlight();
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (this.open) {
          this.moveHighlight(-1);
        } else {
          this.openWithInitialHighlight();
        }
        break;
      case 'Home':
        if (this.open) {
          event.preventDefault();
          this.highlightAt('first');
        }
        break;
      case 'End':
        if (this.open) {
          event.preventDefault();
          this.highlightAt('last');
        }
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        if (this.open) {
          if (this.highlightedValue) {
            this.selectValue(this.highlightedValue);
          }
        } else {
          this.openWithInitialHighlight();
        }
        break;
      case 'Escape':
        if (this.open) {
          event.preventDefault();
          this.open = false;
        }
        break;
      case 'Tab':
        this.open = false;
        break;
      default:
        if (event.key.length === 1 && /\S/.test(event.key)) {
          if (!this.open) {
            this.open = true;
          }
          this.typeahead.buffer += event.key.toLowerCase();
          if (this.typeahead.timeout) {
            clearTimeout(this.typeahead.timeout);
          }
          this.typeahead.timeout = setTimeout(() => {
            this.typeahead.buffer = '';
          }, TYPEAHEAD_RESET_MS);
          const match = this.enabledOptions().find((option) =>
            option.label.toLowerCase().startsWith(this.typeahead.buffer),
          );
          if (match) {
            this.highlightedValue = match.value;
          }
        }
    }
  };

  private syncFormValue(): void {
    this.internals.setFormValue(this.value || null);
  }

  // A string-form `aria-activedescendant` (an ID attribute) cannot resolve
  // into `gh-select-listbox`'s own, separate shadow root — ID references only
  // resolve within the same tree scope as the referencing element. Reflected
  // ARIA *element references* (`ariaActiveDescendantElement`) don't have that
  // restriction, so this sets the actual option element directly instead of
  // an ID string. Not yet in TypeScript's DOM lib, hence the cast.
  private async updateActiveDescendant(): Promise<void> {
    if (!this.triggerEl) {
      return;
    }
    await this.listboxEl?.updateComplete;
    const target =
      this.open && this.highlightedValue && this.listboxEl
        ? (this.listboxEl.shadowRoot?.getElementById(
            getSelectOptionId(this.selectId, this.highlightedValue),
          ) ?? null)
        : null;
    (
      this.triggerEl as unknown as { ariaActiveDescendantElement: Element | null }
    ).ariaActiveDescendantElement = target;
  }

  private startPositioning(): void {
    if (!this.triggerEl || !this.listboxEl) {
      return;
    }
    const update = () => {
      computePosition(this.triggerEl, this.listboxEl, {
        placement: 'bottom-start',
        strategy: 'fixed',
        middleware: [
          offset(Number.parseFloat(tokens.comp.select.panel.offset)),
          flip(),
          shift({ padding: Number.parseFloat(tokens.sys.spacing.sm) }),
          sizeMiddleware({
            padding: Number.parseFloat(tokens.sys.spacing.sm),
            apply: ({ rects, availableHeight }) => {
              Object.assign(this.listboxEl.style, {
                minWidth: `${rects.reference.width}px`,
                maxHeight: `${availableHeight}px`,
              });
            },
          }),
        ],
      }).then(({ x, y }) => {
        Object.assign(this.listboxEl.style, {
          position: 'fixed',
          left: `${x}px`,
          top: `${y}px`,
        });
      });
    };
    this.cleanupAutoUpdate = autoUpdate(this.triggerEl, this.listboxEl, update);
  }

  private stopPositioning(): void {
    this.cleanupAutoUpdate?.();
    this.cleanupAutoUpdate = undefined;
  }

  protected override firstUpdated(): void {
    super.firstUpdated();
    this.defaultValue = this.value;
    this.syncFormValue();
  }

  override disconnectedCallback(): void {
    document.removeEventListener('pointerdown', this.handleOutsidePointerDown);
    this.stopPositioning();
    super.disconnectedCallback();
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('value') || changed.has('disabled')) {
      this.syncFormValue();
    }
    if (changed.has('open')) {
      this.toggleAttribute('data-open', this.open);
      if (this.open) {
        this.startPositioning();
        document.addEventListener('pointerdown', this.handleOutsidePointerDown);
      } else {
        this.stopPositioning();
        document.removeEventListener('pointerdown', this.handleOutsidePointerDown);
      }
    }
    // No host-level `internals.role`/`ariaExpanded`/`ariaHasPopup` here — the
    // real, fully-functional ARIA contract already lives on the inner
    // `<button class="trigger">` (delegatesFocus makes it the actual
    // interactive target). Duplicating role="combobox" on the host too would
    // expose two nested combobox-role nodes for one visual control.
    void this.updateActiveDescendant();
  }

  // --- Form-associated lifecycle callbacks ---------------------------------

  formResetCallback(): void {
    this.value = this.defaultValue;
  }

  formDisabledCallback(disabled: boolean): void {
    this.disabled = disabled;
  }

  formStateRestoreCallback(state: string | File | FormData | null): void {
    if (typeof state === 'string') {
      this.value = state;
    }
  }

  protected override render(): unknown {
    const selectedOption = this.options.find((option) => option.value === this.value);
    const labelId = `${this.selectId}-label`;
    const listboxId = `${this.selectId}-listbox`;
    return html`<div class="field">
      ${this.label ? html`<label id=${labelId}>${this.label}</label>` : nothing}
      <button
        class="trigger"
        type="button"
        role="combobox"
        aria-haspopup="listbox"
        aria-expanded=${this.open}
        aria-controls=${listboxId}
        ?disabled=${this.disabled}
        @click=${this.handleTriggerClick}
        @keydown=${this.handleKeyDown}
      >
        ${this.renderSketch()}
        <span class=${selectedOption ? '' : 'placeholder'}>${selectedOption?.label ?? this.placeholder}</span>
        <gh-icon class="chevron" name="chevron-down" size="sm" style="color: inherit"></gh-icon>
      </button>
      <gh-select-listbox
        id=${listboxId}
        ?open=${this.open}
        .options=${this.options}
        .value=${this.value}
        .highlightedValue=${this.highlightedValue}
        .hostId=${this.selectId}
        .listboxLabel=${this.label}
        @option-select=${this.handleOptionSelect}
        @option-highlight=${this.handleOptionHighlight}
      ></gh-select-listbox>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-select': GhSelect;
  }
}

// packages/react/src/components/Select.tsx
import {
  autoUpdate,
  flip,
  offset,
  shift,
  size as sizeMiddleware,
  useFloating,
} from '@floating-ui/react-dom';
import { tokens } from '@ghds/tokens';
import { Label } from '@radix-ui/react-label';
import {
  type CSSProperties,
  createContext,
  type KeyboardEvent,
  type ReactNode,
  useCallback,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { Icon } from './Icon.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

interface RegisteredOption {
  value: string;
  label: string;
  disabled: boolean;
}

interface SelectContextValue {
  readonly value: string | undefined;
  readonly highlightedValue: string | undefined;
  readonly onSelect: (value: string) => void;
  readonly onHighlight: (value: string) => void;
  readonly registerOption: (value: string, label: string, disabled: boolean) => void;
  readonly unregisterOption: (value: string) => void;
  readonly getOptionId: (value: string) => string;
}

/** Internal — read by {@link SelectOption} when rendered inside a {@link Select}. */
const SelectContext = createContext<SelectContextValue | null>(null);

export interface SelectProps {
  /** Controlled selected value. */
  value?: string;
  /** Initial value when uncontrolled. */
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  /** Visible label. Associated to the trigger via Radix `Label` for accessibility. */
  label?: string;
  /** Shown when nothing is selected. */
  placeholder?: string;
  disabled?: boolean;
  id?: string;
  /** `SelectOption` elements. */
  children: ReactNode;
}

export interface SelectOptionProps {
  value: string;
  disabled?: boolean;
  children: ReactNode;
}

const select = tokens.comp.select;
const c = cssVars.comp.select;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
const TYPEAHEAD_RESET_MS = 500;

function resolveTriggerStroke(focused: boolean, hovered: boolean, disabled: boolean): string {
  if (disabled) {
    return c.trigger.stroke.disabled;
  }
  if (focused) {
    return c.trigger.stroke.focus;
  }
  return hovered ? c.trigger.stroke.hover : c.trigger.stroke.default;
}

function resolveOptionBg(selected: boolean, highlighted: boolean): string {
  if (selected) {
    return highlighted ? c.option.bg.selectedHover : c.option.bg.selected;
  }
  return highlighted ? c.option.bg.highlighted : c.option.bg.default;
}

/**
 * A hand-drawn single-select dropdown. Unlike every other GHDS form control,
 * the trigger is a real `<button>` but the listbox panel and its keyboard
 * model are hand-implemented (no native `<select>` involved) — a real
 * `<select>`'s native dropdown UI can't be restyled to match the hand-drawn
 * aesthetic. Follows the WAI-ARIA "select-only combobox" pattern:
 * `role="combobox"` trigger + `role="listbox"` panel, with
 * `aria-activedescendant` driving a roving highlight — DOM focus never
 * leaves the trigger button while the panel is open.
 *
 * Positioned via `@floating-ui/react-dom`'s `useFloating`, `position: fixed`
 * (no portal/reparenting) — this is clipped only by an ancestor that
 * establishes a new containing block (`transform`/`filter`/`contain`), an
 * accepted v1 limitation.
 */
export function Select({
  value,
  defaultValue,
  onValueChange,
  label,
  placeholder,
  disabled = false,
  id,
  children,
}: SelectProps) {
  const reactId = useId();
  const selectId = id ?? reactId;
  const listboxId = `${selectId}-listbox`;
  const getOptionId = useCallback(
    (optionValue: string) => `${selectId}-option-${optionValue}`,
    [selectId],
  );

  const [open, setOpen] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [focused, setFocused] = useState(false);
  const [internalValue, setInternalValue] = useState(defaultValue);
  const [highlightedValue, setHighlightedValue] = useState<string | undefined>(undefined);
  const optionsRef = useRef<RegisteredOption[]>([]);
  const typeaheadRef = useRef<{ buffer: string; timeout: ReturnType<typeof setTimeout> | null }>({
    buffer: '',
    timeout: null,
  });
  const triggerRef = useRef<HTMLButtonElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);

  const isControlled = value !== undefined;
  const currentValue = isControlled ? value : internalValue;

  const { refs, floatingStyles } = useFloating({
    open,
    placement: 'bottom-start',
    strategy: 'fixed',
    // The panel is always mounted (just hidden via `display:none` — see
    // below) so `SelectOption` children can register on first render; without
    // gating on `open`, `autoUpdate`'s scroll/resize listeners would run for
    // this Select's entire mounted lifetime instead of only while it's open.
    whileElementsMounted: open ? autoUpdate : undefined,
    middleware: [
      offset(toPx(select.panel.offset)),
      flip(),
      shift({ padding: toPx(tokens.sys.spacing.sm) }),
      sizeMiddleware({
        padding: toPx(tokens.sys.spacing.sm),
        apply({ rects, availableHeight, elements }) {
          Object.assign(elements.floating.style, {
            minWidth: `${rects.reference.width}px`,
            maxHeight: `${availableHeight}px`,
          });
        },
      }),
    ],
  });

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLButtonElement>({
    fillStyle: 'solid',
    roughness: select.sketch.roughness,
    bowing: select.sketch.bowing,
    inset: INSET,
  });

  const getEnabledOptions = useCallback(
    () => optionsRef.current.filter((option) => !option.disabled),
    [],
  );

  const registerOption = useCallback(
    (optionValue: string, optionLabel: string, optionDisabled: boolean) => {
      if (!optionsRef.current.some((option) => option.value === optionValue)) {
        optionsRef.current = [
          ...optionsRef.current,
          { value: optionValue, label: optionLabel, disabled: optionDisabled },
        ];
      }
    },
    [],
  );

  const unregisterOption = useCallback((optionValue: string) => {
    optionsRef.current = optionsRef.current.filter((option) => option.value !== optionValue);
  }, []);

  const handleSelect = useCallback(
    (optionValue: string) => {
      if (!isControlled) {
        setInternalValue(optionValue);
      }
      onValueChange?.(optionValue);
      setOpen(false);
      triggerRef.current?.focus();
    },
    [isControlled, onValueChange],
  );

  const handleHighlight = useCallback((optionValue: string) => {
    setHighlightedValue(optionValue);
  }, []);

  const contextValue = useMemo<SelectContextValue>(
    () => ({
      value: currentValue,
      highlightedValue,
      onSelect: handleSelect,
      onHighlight: handleHighlight,
      registerOption,
      unregisterOption,
      getOptionId,
    }),
    [
      currentValue,
      highlightedValue,
      handleSelect,
      handleHighlight,
      registerOption,
      unregisterOption,
      getOptionId,
    ],
  );

  // Click-outside-to-close. `pointerdown` (capture-equivalent timing) beats
  // the trigger's own `click` handler, avoiding the classic "outside click
  // also re-triggers the trigger and reopens" bug.
  useEffect(() => {
    if (!open) {
      return;
    }
    const handlePointerDown = (event: PointerEvent) => {
      const target = event.target as Node;
      if (!triggerRef.current?.contains(target) && !panelRef.current?.contains(target)) {
        setOpen(false);
      }
    };
    document.addEventListener('pointerdown', handlePointerDown);
    return () => document.removeEventListener('pointerdown', handlePointerDown);
  }, [open]);

  const openWithInitialHighlight = () => {
    setOpen(true);
    const enabled = getEnabledOptions();
    if (enabled.length === 0) {
      return;
    }
    const selected =
      currentValue !== undefined && enabled.some((option) => option.value === currentValue)
        ? currentValue
        : enabled[0]?.value;
    setHighlightedValue(selected);
  };

  const highlightAt = (position: 'first' | 'last') => {
    const enabled = getEnabledOptions();
    if (enabled.length === 0) {
      return;
    }
    setHighlightedValue(
      position === 'first' ? enabled[0]?.value : enabled[enabled.length - 1]?.value,
    );
  };

  const moveHighlight = (direction: 1 | -1) => {
    const enabled = getEnabledOptions();
    if (enabled.length === 0) {
      return;
    }
    const currentIndex = enabled.findIndex((option) => option.value === highlightedValue);
    const nextIndex = Math.min(Math.max(currentIndex + direction, 0), enabled.length - 1);
    setHighlightedValue(enabled[nextIndex]?.value);
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    if (disabled) {
      return;
    }
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        if (open) {
          moveHighlight(1);
        } else {
          openWithInitialHighlight();
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (open) {
          moveHighlight(-1);
        } else {
          openWithInitialHighlight();
        }
        break;
      case 'Home':
        if (open) {
          event.preventDefault();
          highlightAt('first');
        }
        break;
      case 'End':
        if (open) {
          event.preventDefault();
          highlightAt('last');
        }
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        if (open) {
          if (highlightedValue !== undefined) {
            handleSelect(highlightedValue);
          }
        } else {
          openWithInitialHighlight();
        }
        break;
      case 'Escape':
        if (open) {
          event.preventDefault();
          setOpen(false);
        }
        break;
      case 'Tab':
        setOpen(false);
        break;
      default:
        if (event.key.length === 1 && /\S/.test(event.key)) {
          if (!open) {
            setOpen(true);
          }
          const typeahead = typeaheadRef.current;
          typeahead.buffer += event.key.toLowerCase();
          if (typeahead.timeout) {
            clearTimeout(typeahead.timeout);
          }
          typeahead.timeout = setTimeout(() => {
            typeahead.buffer = '';
          }, TYPEAHEAD_RESET_MS);
          const match = getEnabledOptions().find((option) =>
            option.label.toLowerCase().startsWith(typeahead.buffer),
          );
          if (match) {
            setHighlightedValue(match.value);
          }
        }
    }
  };

  const selectedOption = optionsRef.current.find((option) => option.value === currentValue);

  const fieldStyle: CSSProperties = {
    display: 'inline-flex',
    flexDirection: 'column',
    gap: select.trigger.gap,
    fontFamily: tokens.sys.typography.body.fontFamily,
  };

  const labelStyle: CSSProperties = {
    color: c.trigger.text.label,
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.label.lineHeight),
  };

  const triggerStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: select.trigger.gap,
    boxSizing: 'border-box',
    width: '100%',
    margin: 0,
    padding: `${select.trigger.padding.vertical} ${select.trigger.padding.horizontal}`,
    border: 'none',
    outline: 'none',
    background: 'transparent',
    color: disabled ? c.trigger.text.disabled : c.trigger.text.default,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    fontWeight: tokens.sys.typography.body.fontWeight,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
    cursor: disabled ? 'not-allowed' : 'pointer',
  };

  const panelStyle: CSSProperties = {
    ...floatingStyles,
    // Always mounted (see the render below) so `SelectOption` children register
    // themselves on first render and the trigger can show the selected label
    // before the panel has ever been opened — visibility is toggled here rather
    // than by conditionally rendering the panel at all.
    display: open ? 'flex' : 'none',
    zIndex: select.panel.zIndex,
    background: c.panel.bg,
    border: `${STROKE_WIDTH}px solid ${c.panel.stroke}`,
    borderRadius: select.panel.radius,
    boxShadow: c.panel.shadow,
    padding: select.panel.padding,
    flexDirection: 'column',
    gap: select.panel.gap,
    boxSizing: 'border-box',
    overflowY: 'auto',
  };

  const ref = mergeRefs(sketchRef, refs.setReference, triggerRef);

  return (
    <div style={fieldStyle}>
      {label !== undefined && (
        <Label htmlFor={selectId} style={labelStyle}>
          {label}
        </Label>
      )}
      <button
        ref={ref}
        id={selectId}
        type="button"
        role="combobox"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-controls={listboxId}
        aria-activedescendant={
          open && highlightedValue !== undefined ? getOptionId(highlightedValue) : undefined
        }
        disabled={disabled}
        style={triggerStyle}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        onClick={() => setOpen((next) => !next)}
        onKeyDown={handleKeyDown}
      >
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={resolveTriggerStroke(focused, hovered, disabled)}
          strokeWidth={STROKE_WIDTH}
          fillColor={disabled ? c.trigger.bg.disabled : c.trigger.bg.default}
          fillRendering="fill"
        />
        <span>{selectedOption?.label ?? placeholder}</span>
        <Icon
          name="chevron-down"
          size="sm"
          style={{
            transform: open ? 'rotate(180deg)' : undefined,
            transition: `transform ${tokens.sys.animation.duration.fast} ${tokens.sys.animation.easing.standard}`,
          }}
        />
      </button>
      <div
        ref={mergeRefs(panelRef, refs.setFloating)}
        id={listboxId}
        role="listbox"
        aria-label={label}
        style={panelStyle}
      >
        <SelectContext.Provider value={contextValue}>{children}</SelectContext.Provider>
      </div>
    </div>
  );
}

/**
 * One option inside a {@link Select}. Has no standalone meaning outside an
 * open `Select` panel — no native element backs it, and its highlight/
 * selected state is entirely driven by the parent's context.
 */
export function SelectOption({ value, disabled = false, children }: SelectOptionProps) {
  const ctx = useContext(SelectContext);
  if (!ctx) {
    throw new Error('SelectOption must be rendered inside a Select');
  }

  // Only a plain string `children` gives a meaningful typeahead label — for
  // JSX children (e.g. an icon + text), `String(children)` would stringify to
  // `"[object Object]"` and silently break/collide typeahead matching, so this
  // option is simply excluded from typeahead instead (a graceful v1
  // degradation, not a workaround for an error case).
  const labelText = typeof children === 'string' ? children : '';

  useEffect(() => {
    ctx.registerOption(value, labelText, disabled);
    return () => ctx.unregisterOption(value);
  }, [ctx, value, labelText, disabled]);

  const isSelected = ctx.value === value;
  const isHighlighted = ctx.highlightedValue === value;

  const optionStyle: CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    padding: `${select.option.padding.vertical} ${select.option.padding.horizontal}`,
    borderRadius: select.option.radius,
    cursor: disabled ? 'not-allowed' : 'pointer',
    color: disabled
      ? c.option.text.disabled
      : isSelected
        ? c.option.text.selected
        : c.option.text.default,
    background: disabled ? c.option.bg.default : resolveOptionBg(isSelected, isHighlighted),
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
  };

  return (
    // biome-ignore lint/a11y/useKeyWithClickEvents: intentionally not a keyboard focus target — Select's aria-activedescendant pattern keeps real DOM focus on the trigger button; Enter/Space there select the highlighted option.
    // biome-ignore lint/a11y/useFocusableInteractive: same reason — options are never individually focusable by design (aria-activedescendant, not roving tabindex).
    <div
      id={ctx.getOptionId(value)}
      role="option"
      aria-selected={isSelected}
      aria-disabled={disabled || undefined}
      style={optionStyle}
      onClick={() => {
        if (!disabled) {
          ctx.onSelect(value);
        }
      }}
      onMouseEnter={() => {
        if (!disabled) {
          ctx.onHighlight(value);
        }
      }}
    >
      {children}
    </div>
  );
}
