// packages/web-components/src/components/skeleton.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { ellipse, rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Shape of a `<gh-skeleton>` placeholder. */
export type GhSkeletonVariant = 'rect' | 'text' | 'circle';

/**
 * `<gh-skeleton>` — a hand-drawn loading placeholder.
 *
 * A sketchy filled shape (`@ghds/sketch-core`) that gently pulses opacity while
 * content loads. Colours, radius, and the pulse duration are token-driven
 * (`comp.skeleton.*`); the dimmed opacity is `sys.opacity.disabled`. The pulse
 * is suppressed under `prefers-reduced-motion: reduce`. The host is
 * `aria-hidden` — announce the busy state on the region it replaces.
 *
 * The host element itself is the sized box (`inline-block`, matching the React
 * implementation); its width/height/radius are applied in `updated()` so the
 * base `ResizeObserver` (which watches the host) re-measures whenever `width`,
 * `height`, or `variant` change.
 */
@customElement('gh-skeleton')
export class GhSkeleton extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        position: relative;
        box-sizing: border-box;
        color: var(--comp-skeleton-stroke);
        animation: gh-skeleton-pulse calc(var(--comp-skeleton-duration) * 3) ease-in-out infinite;
      }

      @keyframes gh-skeleton-pulse {
        0%,
        100% {
          opacity: 1;
        }
        50% {
          opacity: var(--sys-opacity-disabled);
        }
      }

      @media (prefers-reduced-motion: reduce) {
        :host {
          animation: none;
        }
      }

      /* Override the base's line-stroked fill with a solid region fill. */
      .sketch-fill {
        fill: var(--comp-skeleton-bg);
        stroke: none;
      }
    `,
  ];

  /** Placeholder shape. */
  @property({ type: String, reflect: true }) variant: GhSkeletonVariant = 'rect';
  /** Width as a CSS value. Defaults to `100%` (or the diameter for `circle`). */
  @property({ type: String }) width = '';
  /** Height as a CSS value. Defaults per variant. */
  @property({ type: String }) height = '';

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute('aria-hidden', 'true');
  }

  // For `circle`, both axes share one diameter (matching React/RN) so passing a
  // single dimension yields a square, not an ellipse.
  private get circleDiameter(): string {
    return this.height || this.width || 'var(--sys-spacing-2xl)';
  }

  private get resolvedWidth(): string {
    if (this.variant === 'circle') {
      return this.circleDiameter;
    }
    return this.width || '100%';
  }

  private get resolvedHeight(): string {
    if (this.variant === 'circle') {
      return this.circleDiameter;
    }
    return (
      this.height || (this.variant === 'text' ? 'var(--sys-spacing-md)' : 'var(--sys-spacing-lg)')
    );
  }

  private get resolvedRadius(): string {
    return this.variant === 'rect' ? 'var(--comp-skeleton-radius)' : 'var(--sys-radius-pill)';
  }

  protected override updated(): void {
    // Size the host box; changing it triggers the base ResizeObserver → measure.
    this.style.width = this.resolvedWidth;
    this.style.height = this.resolvedHeight;
    this.style.borderRadius = this.resolvedRadius;
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return this.variant === 'circle'
      ? ellipse(0, 0, width, height, options)
      : rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.skeleton.sketch.roughness,
      bowing: tokens.comp.skeleton.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return this.renderSketch();
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-skeleton': GhSkeleton;
  }
}

// packages/react/src/components/Skeleton.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes, useRef } from 'react';
import { useLoopingAnimation } from '../hooks/useLoopingAnimation.js';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Shape of a {@link Skeleton} placeholder. */
export type SkeletonVariant = 'rect' | 'text' | 'circle';

export interface SkeletonProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  /** Placeholder shape. Defaults to `'rect'`. */
  variant?: SkeletonVariant;
  /** Width (number ⇒ px). Defaults to `100%` (or the diameter for `circle`). */
  width?: number | string;
  /** Height (number ⇒ px). Defaults per variant. */
  height?: number | string;
}

const skeleton = tokens.comp.skeleton;
const c = cssVars.comp.skeleton;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
const DURATION_MS = Number.parseFloat(skeleton.duration);
const PULSE_MIN = tokens.sys.opacity.disabled;
const RECT_HEIGHT = tokens.sys.spacing.lg;
const TEXT_HEIGHT = tokens.sys.spacing.md;
const CIRCLE_SIZE = tokens.sys.spacing['2xl'];

/**
 * A hand-drawn loading placeholder: a sketchy filled shape (`@ghds/sketch-core`)
 * that gently pulses opacity while content loads. Colours, radius, the pulse
 * duration, and the dimmed opacity all come from `@ghds/tokens`
 * (`comp.skeleton.*` / `sys.opacity.disabled`). The pulse is suppressed under
 * `prefers-reduced-motion: reduce`.
 *
 * Purely decorative (`aria-hidden`) — announce the busy state on the region it
 * replaces (e.g. `aria-busy` on a container), not on each placeholder.
 */
export const Skeleton = forwardRef<HTMLSpanElement, SkeletonProps>(function Skeleton(
  { variant = 'rect', width, height, style, ...rest },
  forwardedRef,
) {
  const isCircle = variant === 'circle';

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLSpanElement>({
    shape: isCircle ? 'ellipse' : 'rectangle',
    roughness: skeleton.sketch.roughness,
    bowing: skeleton.sketch.bowing,
    fillStyle: 'solid',
    inset: INSET,
  });

  const hostRef = useRef<HTMLSpanElement>(null);
  const ref = mergeRefs(sketchRef, hostRef, forwardedRef);

  useLoopingAnimation(hostRef, [{ opacity: 1 }, { opacity: PULSE_MIN }, { opacity: 1 }], {
    durationMs: DURATION_MS * 3,
    easing: 'ease-in-out',
  });

  let resolvedWidth: number | string;
  let resolvedHeight: number | string;
  if (isCircle) {
    const diameter = height ?? width ?? CIRCLE_SIZE;
    resolvedWidth = diameter;
    resolvedHeight = diameter;
  } else {
    resolvedWidth = width ?? '100%';
    resolvedHeight = height ?? (variant === 'text' ? TEXT_HEIGHT : RECT_HEIGHT);
  }
  const radius = isCircle || variant === 'text' ? tokens.sys.radius.pill : skeleton.radius;

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-block',
    boxSizing: 'border-box',
    width: resolvedWidth,
    height: resolvedHeight,
    borderRadius: radius,
    ...style,
  };

  return (
    <span ref={ref} aria-hidden="true" style={rootStyle} {...rest}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke}
        strokeWidth={STROKE_WIDTH}
        fillColor={c.bg}
        fillRendering="fill"
      />
    </span>
  );
});
