// packages/web-components/src/components/switch.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { ellipse, rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, svg } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/**
 * `<gh-switch>` — a hand-drawn toggle switch.
 *
 * Renders a real `<input type="checkbox" role="switch">` in the shadow DOM —
 * browsers compute `aria-checked` from the native `checked` property
 * regardless of the role override, so Space toggles and correct AT
 * announcement come free. The track comes from `@ghds/sketch-core` (filled
 * solid); the thumb is a second, smaller ellipse computed directly from
 * `@ghds/sketch-core`, positioned left/right based on checked state.
 */
@customElement('gh-switch')
export class GhSwitch extends SketchyBase {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...SketchyBase.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-flex;
        align-items: center;
        gap: var(--comp-switch-gap);
        color: var(--comp-switch-stroke-default);
        cursor: pointer;
      }

      :host([checked]) {
        color: var(--comp-switch-stroke-checked);
        --ghds-sketch-fill-color: var(--comp-switch-bg-on-default);
      }

      :host([checked]:hover) {
        --ghds-sketch-fill-color: var(--comp-switch-bg-on-hover);
      }

      :host(:not([checked])) {
        --ghds-sketch-fill-color: var(--comp-switch-bg-off-default);
      }

      :host([disabled]) {
        color: var(--comp-switch-stroke-disabled);
        cursor: not-allowed;
      }

      :host([disabled][checked]) {
        --ghds-sketch-fill-color: var(--comp-switch-bg-on-disabled);
      }

      :host([disabled]:not([checked])) {
        --ghds-sketch-fill-color: var(--comp-switch-bg-off-disabled);
      }

      .track {
        position: relative;
        box-sizing: border-box;
        width: var(--comp-switch-track-width);
        height: var(--comp-switch-track-height);
        flex-shrink: 0;
      }

      .track:focus-within {
        outline: var(--sys-border-width-default) solid var(--comp-switch-stroke-focus);
        outline-offset: var(--sys-spacing-xs);
      }

      .thumb {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        overflow: visible;
        pointer-events: none;
      }

      .thumb path {
        fill: var(--comp-switch-thumb-color-default);
        stroke: var(--comp-switch-thumb-color-default);
        stroke-width: var(--sys-border-width-default);
        stroke-linecap: round;
      }

      :host([disabled]) .thumb path {
        fill: var(--comp-switch-thumb-color-disabled);
        stroke: var(--comp-switch-thumb-color-disabled);
      }

      input {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        margin: 0;
        opacity: 0;
        cursor: inherit;
      }

      label {
        color: var(--comp-switch-text-label);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
      }

      :host([disabled]) label {
        color: var(--comp-switch-text-disabled);
      }
    `,
  ];

  /** Checked state. */
  @property({ type: Boolean, reflect: true }) checked = false;
  /** Disables interaction and form participation. */
  @property({ type: Boolean, reflect: true }) disabled = false;
  /** Submitted control name. */
  @property({ type: String }) name = '';
  /** Submitted value when checked. */
  @property({ type: String }) value = 'on';
  /** Optional visible label, also the accessible name. */
  @property({ type: String }) label = '';

  @query('.track') private trackEl!: HTMLDivElement;
  @query('input') private inputEl!: HTMLInputElement;

  private readonly internals: ElementInternals = this.attachInternals();
  private readonly switchId = `gh-switch-${Math.random().toString(36).slice(2)}`;

  protected override get frame(): HTMLElement {
    return this.trackEl ?? this;
  }

  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.switch.sketch.roughness,
      bowing: tokens.comp.switch.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override updated(): void {
    // `ElementInternals.states` (CustomStateSet) isn't implemented in every
    // environment yet (e.g. jsdom) — guard so this degrades gracefully rather
    // than throwing where it's unsupported.
    this.internals.states?.delete('checked');
    if (this.checked) {
      this.internals.states?.add('checked');
    }
    this.internals.setFormValue(this.checked ? this.value : null);
  }

  private renderThumb(): unknown {
    if (this.sketchWidth <= 0 || this.sketchHeight <= 0) {
      return nothing;
    }
    const size = Number.parseFloat(tokens.comp.switch.thumb.size);
    const thumbInset = Number.parseFloat(tokens.comp.switch.thumb.inset);
    const y = (this.sketchHeight - size) / 2;
    const x = this.checked ? this.sketchWidth - size - thumbInset : thumbInset;
    const drawable = ellipse(x, y, size, size, {
      roughness: tokens.comp.switch.sketch.roughness,
      bowing: tokens.comp.switch.sketch.bowing,
      seed: this.effectiveSeed,
      fillStyle: 'solid',
    });
    return html`<svg class="thumb" viewBox="0 0 ${this.sketchWidth} ${this.sketchHeight}" aria-hidden="true" focusable="false">
      ${drawable.fillPaths.map((d) => svg`<path d=${d}></path>`)}
    </svg>`;
  }

  private readonly handleChange = (): void => {
    this.checked = this.inputEl.checked;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
  };

  formResetCallback(): void {
    this.checked = false;
  }

  formDisabledCallback(disabled: boolean): void {
    this.disabled = disabled;
  }

  formStateRestoreCallback(state: string | File | FormData | null): void {
    this.checked = typeof state === 'string';
  }

  protected override render(): unknown {
    return html`<div class="track">
        ${this.renderSketch()} ${this.renderThumb()}
        <input
          id=${this.switchId}
          type="checkbox"
          role="switch"
          .checked=${this.checked}
          aria-checked=${this.checked}
          aria-label=${this.label ? nothing : this.getAttribute('aria-label') || nothing}
          ?disabled=${this.disabled}
          @change=${this.handleChange}
        />
      </div>
      ${this.label ? html`<label for=${this.switchId}>${this.label}</label>` : nothing}`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-switch': GhSwitch;
  }
}

// packages/react/src/components/Switch.tsx
import { ellipse } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { Label } from '@radix-ui/react-label';
import {
  type ChangeEvent,
  type CSSProperties,
  forwardRef,
  type InputHTMLAttributes,
  useId,
  useMemo,
  useState,
} from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface SwitchProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size' | 'role' | 'aria-checked'> {
  /** Visible label. Associated to the input via Radix `Label` for accessibility. */
  label?: string;
}

const sw = tokens.comp.switch;
const c = cssVars.comp.switch;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
const TRACK_WIDTH = toPx(tokens.comp.switch.track.width);
const TRACK_HEIGHT = toPx(tokens.comp.switch.track.height);
const THUMB_SIZE = toPx(tokens.comp.switch.thumb.size);
const THUMB_INSET = toPx(tokens.comp.switch.thumb.inset);

/**
 * A hand-drawn switch (toggle). Renders a real
 * `<input type="checkbox" role="switch">` — browsers compute `aria-checked`
 * from the native `checked` property regardless of the role override, so
 * Space toggles and correct AT announcement come free, no custom keydown
 * handler. The track comes from `@ghds/sketch-core` (via {@link useSketch});
 * the thumb is a second, smaller ellipse computed directly from
 * `@ghds/sketch-core`, positioned left/right based on checked state.
 */
export const Switch = forwardRef<HTMLInputElement, SwitchProps>(function Switch(
  {
    label,
    checked,
    defaultChecked,
    disabled = false,
    style,
    onMouseEnter,
    onMouseLeave,
    onFocus,
    onBlur,
    onChange,
    id,
    ...rest
  },
  forwardedRef,
) {
  const reactId = useId();
  const inputId = id ?? reactId;

  const [hovered, setHovered] = useState(false);
  const [focused, setFocused] = useState(false);
  const [internalChecked, setInternalChecked] = useState(defaultChecked ?? false);

  const isChecked = checked ?? internalChecked;

  const {
    ref: sketchRef,
    drawable,
    size,
    seed,
  } = useSketch<HTMLDivElement>({
    shape: 'rectangle',
    roughness: sw.sketch.roughness,
    bowing: sw.sketch.bowing,
    fillStyle: 'solid',
    inset: INSET,
  });

  const thumb = useMemo(() => {
    if (size.width <= 0 || size.height <= 0) {
      return null;
    }
    const y = (size.height - THUMB_SIZE) / 2;
    const x = isChecked ? size.width - THUMB_SIZE - THUMB_INSET : THUMB_INSET;
    return ellipse(x, y, THUMB_SIZE, THUMB_SIZE, {
      roughness: sw.sketch.roughness,
      bowing: sw.sketch.bowing,
      seed,
      fillStyle: 'solid',
    });
  }, [isChecked, size, seed]);

  const trackFill = disabled
    ? isChecked
      ? c.bg.on.disabled
      : c.bg.off.disabled
    : isChecked
      ? hovered
        ? c.bg.on.hover
        : c.bg.on.default
      : c.bg.off.default;
  const trackStroke = disabled
    ? c.stroke.disabled
    : isChecked
      ? c.stroke.checked
      : c.stroke.default;
  const thumbColor = disabled ? c.thumb.color.disabled : c.thumb.color.default;

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    if (checked === undefined) {
      setInternalChecked(event.target.checked);
    }
    onChange?.(event);
  };

  const fieldStyle: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: sw.gap,
    fontFamily: tokens.sys.typography.body.fontFamily,
  };

  const trackStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-block',
    boxSizing: 'border-box',
    width: TRACK_WIDTH,
    height: TRACK_HEIGHT,
    flexShrink: 0,
    outline: focused ? `${STROKE_WIDTH}px solid ${c.stroke.focus}` : 'none',
    outlineOffset: tokens.sys.spacing.xs,
    ...style,
  };

  const inputStyle: CSSProperties = {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    margin: 0,
    opacity: 0,
    cursor: disabled ? 'not-allowed' : 'pointer',
  };

  const labelStyle: CSSProperties = {
    color: disabled ? c.text.disabled : c.text.label,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
  };

  const ref = mergeRefs(sketchRef, forwardedRef);

  return (
    <span style={fieldStyle}>
      <span style={trackStyle}>
        <SketchSurface
          drawable={drawable}
          width={size.width}
          height={size.height}
          strokeColor={trackStroke}
          strokeWidth={STROKE_WIDTH}
          fillColor={trackFill}
          fillRendering="fill"
        />
        {thumb && (
          <SketchSurface
            drawable={thumb}
            width={size.width}
            height={size.height}
            strokeColor={thumbColor}
            strokeWidth={STROKE_WIDTH}
            fillColor={thumbColor}
            fillRendering="fill"
          />
        )}
        <input
          {...rest}
          ref={ref}
          type="checkbox"
          role="switch"
          id={inputId}
          checked={isChecked}
          aria-checked={isChecked}
          disabled={disabled}
          style={inputStyle}
          onChange={handleChange}
          onMouseEnter={(event) => {
            setHovered(true);
            onMouseEnter?.(event);
          }}
          onMouseLeave={(event) => {
            setHovered(false);
            onMouseLeave?.(event);
          }}
          onFocus={(event) => {
            setFocused(true);
            onFocus?.(event);
          }}
          onBlur={(event) => {
            setFocused(false);
            onBlur?.(event);
          }}
        />
      </span>
      {label !== undefined && (
        <Label htmlFor={inputId} style={labelStyle}>
          {label}
        </Label>
      )}
    </span>
  );
});
