// packages/web-components/src/components/table.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';
import './checkbox.js';
import './icon.js';

/** A column definition. */
export interface GhTableColumn {
  key: string;
  header: string;
  sortable?: boolean;
  align?: 'left' | 'right' | 'center';
}

/** A row: a stable `id` plus a cell value per column key. */
export interface GhTableRow {
  id: string;
  [key: string]: string | number;
}

export type GhSortDirection = 'asc' | 'desc';
export interface GhTableSort {
  key: string;
  direction: GhSortDirection;
}

/**
 * `<gh-table>` — a hand-drawn data table. A sketchy outline frames a semantic
 * `<table>` with sortable headers (`aria-sort`) and optional row selection
 * (a `<gh-checkbox>` column + select-all). Controlled: dispatches
 * `sort-change` (`{ key, direction }`) and `selection-change` (`string[]`) and
 * renders the rows as given. Token-driven (`comp.table.*`).
 */
@customElement('gh-table')
export class GhTable extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        position: relative;
        overflow-x: auto;
        color: var(--comp-table-stroke);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
      }
      table {
        position: relative;
        width: 100%;
        border-collapse: collapse;
      }
      caption {
        text-align: left;
        padding: var(--comp-table-padding-horizontal);
        color: var(--comp-table-text-header);
      }
      th,
      td {
        padding: var(--comp-table-padding-vertical) var(--comp-table-padding-horizontal);
        border-bottom: var(--sys-border-width-default) solid var(--comp-table-rowBorder);
        text-align: left;
      }
      thead tr {
        background: var(--comp-table-headerBg);
      }
      th {
        color: var(--comp-table-text-header);
        font-weight: var(--sys-typography-label-fontWeight);
      }
      td {
        color: var(--comp-table-text-cell);
      }
      tr[data-selected] {
        background: var(--comp-table-selectedBg);
      }
      .sort {
        display: inline-flex;
        align-items: center;
        gap: var(--sys-spacing-xs);
        padding: 0;
        border: none;
        background: transparent;
        color: inherit;
        font: inherit;
        font-weight: inherit;
        cursor: pointer;
      }
      .sort .chevron {
        display: inline-flex;
        color: var(--comp-table-text-icon);
      }
      .sketch-fill {
        fill: var(--comp-table-bg);
        stroke: none;
      }
    `,
  ];

  @property({ attribute: false }) columns: GhTableColumn[] = [];
  @property({ attribute: false }) rows: GhTableRow[] = [];
  @property({ type: String }) caption = '';
  @property({ attribute: false }) sort?: GhTableSort;
  @property({ attribute: false }) selectedIds?: string[];

  private get selectable(): boolean {
    return this.selectedIds !== undefined;
  }

  private emitSelection(ids: string[]): void {
    this.dispatchEvent(
      new CustomEvent('selection-change', { detail: ids, bubbles: true, composed: true }),
    );
  }

  private handleSort(key: string): void {
    const direction: GhSortDirection =
      this.sort?.key === key && this.sort.direction === 'asc' ? 'desc' : 'asc';
    this.dispatchEvent(
      new CustomEvent('sort-change', { detail: { key, direction }, bubbles: true, composed: true }),
    );
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.table.sketch.roughness,
      bowing: tokens.comp.table.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    const selected = new Set(this.selectedIds ?? []);
    const allSelected = this.rows.length > 0 && this.rows.every((r) => selected.has(r.id));
    const someSelected = this.rows.some((r) => selected.has(r.id));

    return html`${this.renderSketch()}
      <table>
        ${this.caption ? html`<caption>${this.caption}</caption>` : nothing}
        <thead>
          <tr>
            ${
              this.selectable
                ? html`<th scope="col" style="width:1%">
                    <gh-checkbox
                      aria-label="Select all rows"
                      ?checked=${allSelected}
                      ?indeterminate=${!allSelected && someSelected}
                      @change=${() =>
                        this.emitSelection(allSelected ? [] : this.rows.map((r) => r.id))}
                    ></gh-checkbox>
                  </th>`
                : nothing
            }
            ${this.columns.map((col) => {
              const active = this.sort?.key === col.key;
              const ariaSort = active
                ? this.sort?.direction === 'asc'
                  ? 'ascending'
                  : 'descending'
                : col.sortable
                  ? 'none'
                  : nothing;
              return html`<th scope="col" aria-sort=${ariaSort} style=${`text-align:${col.align ?? 'left'}`}>
                ${
                  col.sortable
                    ? html`<button class="sort" type="button" @click=${() => this.handleSort(col.key)}>
                        ${col.header}
                        ${
                          active
                            ? html`<span class="chevron"
                                ><gh-icon
                                  name=${this.sort?.direction === 'asc' ? 'chevron-up' : 'chevron-down'}
                                  size="sm"
                                ></gh-icon
                              ></span>`
                            : nothing
                        }
                      </button>`
                    : col.header
                }
              </th>`;
            })}
          </tr>
        </thead>
        <tbody>
          ${this.rows.map((row) => {
            const isSelected = selected.has(row.id);
            return html`<tr ?data-selected=${isSelected}>
              ${
                this.selectable
                  ? html`<td>
                      <gh-checkbox
                        aria-label=${`Select row ${row.id}`}
                        ?checked=${isSelected}
                        @change=${() =>
                          this.emitSelection(
                            isSelected
                              ? (this.selectedIds ?? []).filter((x) => x !== row.id)
                              : [...(this.selectedIds ?? []), row.id],
                          )}
                      ></gh-checkbox>
                    </td>`
                  : nothing
              }
              ${this.columns.map(
                (col) =>
                  html`<td style=${`text-align:${col.align ?? 'left'}`}>${row[col.key]}</td>`,
              )}
            </tr>`;
          })}
        </tbody>
      </table>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-table': GhTable;
  }
}

// packages/react/src/components/Table.tsx
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { toPx } from '../lib/units.js';
import { Checkbox } from './Checkbox.js';
import { Icon } from './Icon.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** A column definition. */
export interface TableColumn {
  /** Row-cell key this column reads. */
  key: string;
  /** Header content. */
  header: ReactNode;
  /** Whether the column can be sorted. */
  sortable?: boolean;
  /** Cell text alignment. */
  align?: 'left' | 'right' | 'center';
}

/** A row: a stable `id` plus a cell value per column key. */
export interface TableRow {
  id: string;
  [key: string]: ReactNode;
}

export type SortDirection = 'asc' | 'desc';
export interface TableSort {
  key: string;
  direction: SortDirection;
}

export interface TableProps extends Omit<HTMLAttributes<HTMLTableElement>, 'onChange'> {
  columns: TableColumn[];
  rows: TableRow[];
  /** Accessible caption for the table. */
  caption?: string;
  /** Controlled sort state; the table emits intent and renders rows as given. */
  sort?: TableSort;
  onSortChange?: (sort: TableSort) => void;
  /** Controlled selected row ids. Providing this (with a handler) shows checkboxes. */
  selectedIds?: string[];
  onSelectionChange?: (ids: string[]) => void;
}

const table = tokens.comp.table;
const c = cssVars.comp.table;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

/**
 * A hand-drawn data table. A sketchy outline (`@ghds/sketch-core`) frames a
 * semantic `<table>` with sortable column headers (`aria-sort`) and optional row
 * selection (a leading checkbox column with a select-all header). Sorting and
 * selection are **controlled** — the table emits intent via `onSortChange` /
 * `onSelectionChange` and renders the `rows` in the order given. Colours,
 * padding, and sketch parameters come from `@ghds/tokens` (`comp.table.*`).
 */
export const Table = forwardRef<HTMLTableElement, TableProps>(function Table(
  { columns, rows, caption, sort, onSortChange, selectedIds, onSelectionChange, style, ...rest },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: table.sketch.roughness,
    bowing: table.sketch.bowing,
    inset: INSET,
  });

  const selectable = selectedIds !== undefined && onSelectionChange !== undefined;
  const selected = new Set(selectedIds ?? []);
  const allSelected = rows.length > 0 && rows.every((row) => selected.has(row.id));
  const someSelected = rows.some((row) => selected.has(row.id));

  const toggleAll = () => {
    onSelectionChange?.(allSelected ? [] : rows.map((row) => row.id));
  };
  const toggleRow = (id: string) => {
    if (selected.has(id)) {
      onSelectionChange?.([...selected].filter((x) => x !== id));
    } else {
      onSelectionChange?.([...selected, id]);
    }
  };

  const handleSort = (key: string) => {
    const direction: SortDirection = sort?.key === key && sort.direction === 'asc' ? 'desc' : 'asc';
    onSortChange?.({ key, direction });
  };

  const containerStyle: CSSProperties = {
    ...sketchHostStyle,
    boxSizing: 'border-box',
    overflowX: 'auto',
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    ...style,
  };

  const tableStyle: CSSProperties = {
    position: 'relative',
    width: '100%',
    borderCollapse: 'collapse',
  };

  const cellBase: CSSProperties = {
    padding: `${table.padding.vertical} ${table.padding.horizontal}`,
    borderBottom: `${STROKE_WIDTH}px solid ${c.rowBorder}`,
  };

  return (
    <div ref={sketchRef} style={containerStyle}>
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke}
        strokeWidth={STROKE_WIDTH}
        fillColor={c.bg}
        fillRendering="fill"
      />
      <table ref={forwardedRef} style={tableStyle} {...rest}>
        {caption && (
          <caption
            style={{ textAlign: 'left', padding: table.padding.horizontal, color: c.text.header }}
          >
            {caption}
          </caption>
        )}
        <thead>
          <tr style={{ background: c.headerBg }}>
            {selectable && (
              <th scope="col" style={{ ...cellBase, width: '1%' }}>
                <Checkbox
                  checked={allSelected}
                  indeterminate={!allSelected && someSelected}
                  onChange={toggleAll}
                  aria-label="Select all rows"
                />
              </th>
            )}
            {columns.map((col) => {
              const active = sort?.key === col.key;
              const ariaSort = active
                ? sort?.direction === 'asc'
                  ? 'ascending'
                  : 'descending'
                : col.sortable
                  ? 'none'
                  : undefined;
              return (
                <th
                  key={col.key}
                  scope="col"
                  aria-sort={ariaSort}
                  style={{
                    ...cellBase,
                    textAlign: col.align ?? 'left',
                    color: c.text.header,
                    fontWeight: tokens.sys.typography.label.fontWeight,
                  }}
                >
                  {col.sortable ? (
                    <button
                      type="button"
                      onClick={() => handleSort(col.key)}
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: tokens.sys.spacing.xs,
                        padding: 0,
                        border: 'none',
                        background: 'transparent',
                        color: 'inherit',
                        font: 'inherit',
                        fontWeight: 'inherit',
                        cursor: 'pointer',
                      }}
                    >
                      {col.header}
                      {active && (
                        <span style={{ display: 'inline-flex', color: c.text.icon }}>
                          <Icon
                            name={sort?.direction === 'asc' ? 'chevron-up' : 'chevron-down'}
                            size="sm"
                          />
                        </span>
                      )}
                    </button>
                  ) : (
                    col.header
                  )}
                </th>
              );
            })}
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            const isSelected = selected.has(row.id);
            return (
              <tr key={row.id} style={isSelected ? { background: c.selectedBg } : undefined}>
                {selectable && (
                  <td style={cellBase}>
                    <Checkbox
                      checked={isSelected}
                      onChange={() => toggleRow(row.id)}
                      aria-label={`Select row ${row.id}`}
                    />
                  </td>
                )}
                {columns.map((col) => (
                  <td
                    key={col.key}
                    style={{ ...cellBase, textAlign: col.align ?? 'left', color: c.text.cell }}
                  >
                    {row[col.key]}
                  </td>
                ))}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
});
