// packages/web-components/src/components/toast.ts
import type { IconName } from '@ghds/icons';
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';
import './icon.js';

/** Severity of a `<gh-toast>`. */
export type GhToastVariant = 'info' | 'success' | 'warning' | 'danger';

const ICON: Record<GhToastVariant, IconName> = {
  info: 'info',
  success: 'check',
  warning: 'warning',
  danger: 'warning',
};

/** Auto-dismiss timeout (behavioural timing, not a motion token). */
const DEFAULT_DURATION = 5000;

/**
 * `<gh-toast>` — a hand-drawn toast notification. A sketchy, elevated box
 * fixed to the bottom-right that auto-dismisses after `duration`. `danger`
 * exposes `role="alert"`; the rest `role="status"`. Reflects `open` and
 * dispatches a `close` event on auto-dismiss / close button. Token-driven
 * (`comp.toast.*`).
 */
@customElement('gh-toast')
export class GhToast extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        --_toast-stroke: var(--comp-toast-stroke-info);
        --_toast-icon: var(--comp-toast-icon-info);
        color: var(--_toast-stroke);
      }
      :host([variant='success']) {
        --_toast-stroke: var(--comp-toast-stroke-success);
        --_toast-icon: var(--comp-toast-icon-success);
      }
      :host([variant='warning']) {
        --_toast-stroke: var(--comp-toast-stroke-warning);
        --_toast-icon: var(--comp-toast-icon-warning);
      }
      :host([variant='danger']) {
        --_toast-stroke: var(--comp-toast-stroke-danger);
        --_toast-icon: var(--comp-toast-icon-danger);
      }
      :host {
        display: none;
      }
      :host([open]) {
        display: block;
      }
      .toast {
        position: fixed;
        right: var(--sys-spacing-lg);
        bottom: var(--sys-spacing-lg);
        z-index: var(--comp-toast-zIndex);
        display: flex;
        align-items: flex-start;
        gap: var(--comp-toast-gap);
        box-sizing: border-box;
        max-width: 24rem;
        padding: var(--comp-toast-padding);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        line-height: var(--sys-typography-body-lineHeight);
      }
      .icon {
        position: relative;
        display: inline-flex;
        color: var(--_toast-icon);
      }
      .content {
        position: relative;
        flex: 1;
        min-width: 0;
        color: var(--comp-toast-text-body);
      }
      .title {
        color: var(--comp-toast-text-title);
        font-weight: var(--sys-typography-label-fontWeight);
      }
      .close {
        position: relative;
        display: inline-flex;
        padding: 0;
        border: none;
        background: transparent;
        color: var(--comp-toast-text-body);
        cursor: pointer;
      }
      .sketch-fill {
        fill: var(--comp-toast-bg);
        stroke: none;
      }
    `,
  ];

  @property({ type: Boolean, reflect: true }) open = false;
  @property({ type: String, reflect: true }) variant: GhToastVariant = 'info';
  @property({ type: String }) heading = '';
  /** Auto-dismiss after this many ms; `0` to persist. */
  @property({ type: Number }) duration = DEFAULT_DURATION;

  @query('.toast') private toastEl?: HTMLElement;

  private readonly internals: ElementInternals = this.attachInternals();
  private timer: ReturnType<typeof setTimeout> | null = null;

  // Measure the fixed-positioned panel, not the (zero-height) host.
  protected override get frame(): HTMLElement {
    return this.toastEl ?? this;
  }

  private clearTimer(): void {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  }

  override disconnectedCallback(): void {
    this.clearTimer();
    super.disconnectedCallback();
  }

  private requestClose(): void {
    this.dispatchEvent(new CustomEvent('close', { bubbles: true, composed: true }));
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('variant')) {
      this.internals.role = this.variant === 'danger' ? 'alert' : 'status';
    }
    if (changed.has('open') || changed.has('duration')) {
      // Re-arm on either `open` or `duration` changing, so setting duration=0 on
      // an already-open toast cancels the pending auto-dismiss (matching React/RN).
      this.clearTimer();
      if (this.open) {
        if (changed.has('open')) {
          this.measure();
        }
        if (this.duration > 0) {
          this.timer = setTimeout(() => this.requestClose(), this.duration);
        }
      }
    }
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.toast.sketch.roughness,
      bowing: tokens.comp.toast.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  protected override render(): unknown {
    return html`<div class="toast" part="toast">
      ${this.renderSketch()}
      <span class="icon"><gh-icon name=${ICON[this.variant]} size="sm"></gh-icon></span>
      <div class="content">
        ${this.heading ? html`<div class="title">${this.heading}</div>` : nothing}
        <div><slot></slot></div>
      </div>
      <button class="close" aria-label="Dismiss" @click=${() => this.requestClose()}>
        <gh-icon name="close" size="sm"></gh-icon>
      </button>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-toast': GhToast;
  }
}

// packages/react/src/components/Toast.tsx
import type { IconName } from '@ghds/icons';
import { tokens } from '@ghds/tokens';
import { type CSSProperties, forwardRef, type ReactNode, useEffect, useRef } from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { Icon } from './Icon.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

/** Severity of a {@link Toast}. */
export type ToastVariant = 'info' | 'success' | 'warning' | 'danger';

export interface ToastProps {
  /** Whether the toast is shown. */
  open: boolean;
  /** Called on auto-dismiss or when the close button is pressed. */
  onClose: () => void;
  /** Severity. Defaults to `'info'`. */
  variant?: ToastVariant;
  /** Optional bold title. */
  title?: ReactNode;
  /** Message body. */
  children?: ReactNode;
  /** Auto-dismiss after this many ms; `0` to persist. Defaults to 5000. */
  duration?: number;
}

const toast = tokens.comp.toast;
const c = cssVars.comp.toast;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;
// Auto-dismiss timeout is a behavioural timing (like Select's typeahead reset),
// not a motion token — kept as a component default.
const DEFAULT_DURATION = 5000;

const ICON: Record<ToastVariant, IconName> = {
  info: 'info',
  success: 'check',
  warning: 'warning',
  danger: 'warning',
};

/**
 * A hand-drawn toast notification: a sketchy, elevated box (`@ghds/sketch-core`)
 * that appears fixed to the bottom-right and auto-dismisses after `duration`.
 * `danger` uses `role="alert"` (assertive); the rest use `role="status"`
 * (polite). Controlled via `open`/`onClose`; stack multiple toasts by rendering
 * several. Colours and sketch parameters come from `@ghds/tokens`
 * (`comp.toast.*`).
 */
export const Toast = forwardRef<HTMLDivElement, ToastProps>(function Toast(
  { open, onClose, variant = 'info', title, children, duration = DEFAULT_DURATION },
  forwardedRef,
) {
  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLDivElement>({
    fillStyle: 'solid',
    roughness: toast.sketch.roughness,
    bowing: toast.sketch.bowing,
    inset: INSET,
  });
  const ref = mergeRefs(sketchRef, forwardedRef);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  useEffect(() => {
    if (!open || duration <= 0) {
      return;
    }
    const timer = setTimeout(() => onCloseRef.current(), duration);
    return () => clearTimeout(timer);
  }, [open, duration]);

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    position: 'fixed',
    right: tokens.sys.spacing.lg,
    bottom: tokens.sys.spacing.lg,
    zIndex: toast.zIndex,
    display: 'flex',
    alignItems: 'flex-start',
    gap: toast.gap,
    boxSizing: 'border-box',
    maxWidth: '24rem',
    padding: toast.padding,
    color: c.text.body,
    fontFamily: tokens.sys.typography.body.fontFamily,
    fontSize: tokens.sys.typography.body.fontSize,
    lineHeight: String(tokens.sys.typography.body.lineHeight),
  };

  // The live region stays mounted (empty when closed) so a polite `status`
  // announcement fires when the message is inserted on open, rather than the
  // region appearing already-populated.
  const closedStyle: CSSProperties = {
    position: 'fixed',
    width: 0,
    height: 0,
    overflow: 'hidden',
  };

  return (
    <div
      ref={ref}
      role={variant === 'danger' ? 'alert' : 'status'}
      aria-live={variant === 'danger' ? 'assertive' : 'polite'}
      style={open ? rootStyle : closedStyle}
    >
      {open && (
        <>
          <SketchSurface
            drawable={drawable}
            width={size.width}
            height={size.height}
            strokeColor={c.stroke[variant]}
            strokeWidth={STROKE_WIDTH}
            fillColor={c.bg}
            fillRendering="fill"
            shadowColor={c.stroke[variant]}
          />
          <span style={{ position: 'relative', display: 'inline-flex', color: c.icon[variant] }}>
            <Icon name={ICON[variant]} size="sm" />
          </span>
          <div style={{ position: 'relative', flex: 1, minWidth: 0 }}>
            {title !== undefined && (
              <div
                style={{ color: c.text.title, fontWeight: tokens.sys.typography.label.fontWeight }}
              >
                {title}
              </div>
            )}
            {children !== undefined && <div>{children}</div>}
          </div>
          <button
            type="button"
            aria-label="Dismiss"
            onClick={onClose}
            style={{
              position: 'relative',
              display: 'inline-flex',
              padding: 0,
              border: 'none',
              background: 'transparent',
              color: c.text.body,
              cursor: 'pointer',
            }}
          >
            <Icon name="close" size="sm" />
          </button>
        </>
      )}
    </div>
  );
});
