// packages/web-components/src/components/toggle.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, type PropertyValues } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/**
 * `<gh-toggle>` — a hand-drawn two-state (pressed / not-pressed) button.
 *
 * A real `<button>` owns the semantics with `aria-pressed`; the sketchy box
 * (`@ghds/sketch-core`, solid fill) changes fill with the pressed state. The
 * pressed state is also exposed via `internals.states` (`:state(pressed)`).
 * Form-associated: when `name` is set it contributes `value` while pressed.
 * Colours, padding and sketch parameters come from `@ghds/tokens`
 * (`comp.toggle.*`).
 */
@customElement('gh-toggle')
export class GhToggle extends SketchyBase {
  static formAssociated = true;

  static override shadowRootOptions: ShadowRootInit = {
    ...SketchyBase.shadowRootOptions,
    delegatesFocus: true,
  };

  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        color: var(--comp-toggle-stroke);
        cursor: pointer;
        --ghds-sketch-fill-color: var(--comp-toggle-bg-default);
      }

      :host(:hover) {
        --ghds-sketch-fill-color: var(--comp-toggle-bg-hover);
      }

      :host([pressed]) {
        --ghds-sketch-fill-color: var(--comp-toggle-bg-pressed);
      }

      :host([disabled]) {
        cursor: not-allowed;
        opacity: var(--sys-opacity-disabled, 0.5);
      }

      button {
        appearance: none;
        position: relative;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: var(--sys-spacing-sm);
        box-sizing: border-box;
        margin: 0;
        padding: var(--comp-toggle-padding-vertical) var(--comp-toggle-padding-horizontal);
        border: none;
        background: transparent;
        color: var(--comp-toggle-text-default);
        font-family: var(--sys-typography-label-fontFamily);
        font-size: var(--sys-typography-label-fontSize);
        font-weight: var(--sys-typography-label-fontWeight);
        line-height: var(--sys-typography-label-lineHeight);
        cursor: inherit;
      }

      :host([pressed]) button {
        color: var(--comp-toggle-text-pressed);
      }

      .label {
        position: relative;
        display: inline-flex;
        align-items: center;
        gap: var(--sys-spacing-sm);
      }

      button:focus-visible {
        outline: var(--sys-border-width-thick) solid var(--comp-toggle-focus-ring);
        outline-offset: var(--sys-spacing-xs);
        border-radius: var(--comp-toggle-radius);
      }
    `,
  ];

  /** Pressed (on) state. */
  @property({ type: Boolean, reflect: true }) pressed = false;
  /** Disables interaction and form participation. */
  @property({ type: Boolean, reflect: true }) disabled = false;
  /** Submitted control name (enables form association when set). */
  @property({ type: String }) name = '';
  /** Submitted value when pressed. */
  @property({ type: String }) value = 'on';
  /** Accessible label when no visible text is slotted. */
  @property({ type: String }) label = '';

  private readonly internals: ElementInternals = this.attachInternals();
  private defaultPressed = false;

  protected override firstUpdated(): void {
    super.firstUpdated();
    this.defaultPressed = this.pressed;
  }

  get form(): HTMLFormElement | null {
    return this.internals.form;
  }

  protected override updated(changed: PropertyValues): void {
    if (changed.has('pressed')) {
      this.internals.states?.delete('pressed');
      if (this.pressed) {
        this.internals.states?.add('pressed');
      }
    }
    this.internals.setFormValue(this.pressed ? this.value : null);
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.toggle.sketch.roughness,
      bowing: tokens.comp.toggle.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  private readonly onClick = (): void => {
    if (this.disabled) {
      return;
    }
    this.pressed = !this.pressed;
    this.dispatchEvent(new Event('change', { bubbles: true, composed: true }));
  };

  formResetCallback(): void {
    this.pressed = this.defaultPressed;
  }

  formDisabledCallback(disabled: boolean): void {
    this.disabled = disabled;
  }

  protected override render(): unknown {
    return html`<button
      part="button"
      type="button"
      aria-pressed=${this.pressed ? 'true' : 'false'}
      aria-label=${this.label || nothing}
      ?disabled=${this.disabled}
      @click=${this.onClick}
    >
      ${this.renderSketch()}
      <span class="label"><slot>${this.label}</slot></span>
    </button>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-toggle': GhToggle;
  }
}

// packages/react/src/components/Toggle.tsx
import { tokens } from '@ghds/tokens';
import {
  type ButtonHTMLAttributes,
  type CSSProperties,
  forwardRef,
  type MouseEvent,
  useState,
} from 'react';
import { useSketch } from '../hooks/useSketch.js';
import { cssVars } from '../lib/cssVars.js';
import { mergeRefs } from '../lib/mergeRefs.js';
import { toPx } from '../lib/units.js';
import { SketchSurface, sketchHostStyle } from './SketchSurface.js';

export interface ToggleProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange' | 'aria-pressed'> {
  /** Controlled pressed state. */
  pressed?: boolean;
  /** Initial pressed state when uncontrolled. Defaults to `false`. */
  defaultPressed?: boolean;
  /** Called with the next pressed state when toggled. */
  onPressedChange?: (pressed: boolean) => void;
}

const toggle = tokens.comp.toggle;
const c = cssVars.comp.toggle;
const STROKE_WIDTH = toPx(tokens.sys.border.width.default);
const INSET = STROKE_WIDTH;

/**
 * A hand-drawn two-state toggle button. Renders a `<button>` with
 * `aria-pressed`; Space/Enter toggle it natively. The sketchy outline + fill
 * come from `@ghds/sketch-core` (via {@link useSketch}) — the same drawing the
 * `Button` uses — and every colour, padding and sketch parameter comes from
 * `@ghds/tokens` (`comp.toggle.*`). The SVG is decorative (`aria-hidden`).
 */
export const Toggle = forwardRef<HTMLButtonElement, ToggleProps>(function Toggle(
  {
    pressed,
    defaultPressed = false,
    onPressedChange,
    children,
    disabled = false,
    style,
    type,
    onClick,
    onMouseEnter,
    onMouseLeave,
    onFocus,
    onBlur,
    ...rest
  },
  forwardedRef,
) {
  const [internalPressed, setInternalPressed] = useState(defaultPressed);
  const [hovered, setHovered] = useState(false);
  const [focused, setFocused] = useState(false);

  const isPressed = pressed ?? internalPressed;

  const {
    ref: sketchRef,
    drawable,
    size,
  } = useSketch<HTMLButtonElement>({
    fillStyle: 'solid',
    roughness: toggle.sketch.roughness,
    bowing: toggle.sketch.bowing,
    inset: INSET,
  });

  const ref = mergeRefs(sketchRef, forwardedRef);

  const fill = isPressed ? c.bg.pressed : hovered ? c.bg.hover : c.bg.default;

  const rootStyle: CSSProperties = {
    ...sketchHostStyle,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.sys.spacing.xs,
    boxSizing: 'border-box',
    padding: `${toggle.padding.vertical} ${toggle.padding.horizontal}`,
    border: 'none',
    background: 'transparent',
    appearance: 'none',
    cursor: disabled ? 'not-allowed' : 'pointer',
    color: isPressed ? c.text.pressed : c.text.default,
    fontFamily: tokens.sys.typography.label.fontFamily,
    fontSize: tokens.sys.typography.label.fontSize,
    fontWeight: tokens.sys.typography.label.fontWeight,
    lineHeight: String(tokens.sys.typography.label.lineHeight),
    outline: focused ? `${STROKE_WIDTH}px solid ${c.focus.ring}` : 'none',
    outlineOffset: tokens.sys.spacing.xs,
    opacity: disabled ? 0.5 : 1,
    ...style,
  };

  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    if (pressed === undefined) {
      setInternalPressed((prev) => !prev);
    }
    onPressedChange?.(!isPressed);
    onClick?.(event);
  };

  return (
    <button
      ref={ref}
      type={type ?? 'button'}
      aria-pressed={isPressed}
      disabled={disabled}
      data-state={isPressed ? 'on' : 'off'}
      style={rootStyle}
      onClick={handleClick}
      onMouseEnter={(e) => {
        setHovered(true);
        onMouseEnter?.(e);
      }}
      onMouseLeave={(e) => {
        setHovered(false);
        onMouseLeave?.(e);
      }}
      onFocus={(e) => {
        setFocused(true);
        onFocus?.(e);
      }}
      onBlur={(e) => {
        setFocused(false);
        onBlur?.(e);
      }}
      {...rest}
    >
      <SketchSurface
        drawable={drawable}
        width={size.width}
        height={size.height}
        strokeColor={c.stroke}
        strokeWidth={STROKE_WIDTH}
        fillColor={fill}
        fillRendering="fill"
      />
      <span
        style={{
          position: 'relative',
          display: 'inline-flex',
          alignItems: 'center',
          gap: tokens.sys.spacing.xs,
        }}
      >
        {children}
      </span>
    </button>
  );
});
