// packages/web-components/src/components/breadcrumb.ts
import { css, html, LitElement, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import './icon.js';

/** One entry in a `<gh-breadcrumb>` trail. */
export interface GhBreadcrumbItem {
  label: string;
  href?: string;
}

/**
 * `<gh-breadcrumb>` — a breadcrumb navigation trail.
 *
 * Renders a `<nav>` landmark wrapping an ordered list; the last item is the
 * current page (`aria-current="page"`, not a link). Colours, gap, and
 * typography are token-driven (`comp.breadcrumb.*`); separators are hand-drawn
 * `<gh-icon>` chevrons. Activating a link dispatches a `select` `CustomEvent`
 * with `{ item, index }`.
 */
@customElement('gh-breadcrumb')
export class GhBreadcrumb extends LitElement {
  static override styles = css`
    :host {
      display: block;
    }

    ol {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: var(--comp-breadcrumb-gap);
      margin: 0;
      padding: 0;
      list-style: none;
      font-family: var(--sys-typography-body-fontFamily);
      font-size: var(--sys-typography-body-fontSize);
      line-height: var(--sys-typography-body-lineHeight);
    }

    li {
      display: inline-flex;
      align-items: center;
      gap: var(--comp-breadcrumb-gap);
    }

    a {
      color: var(--comp-breadcrumb-text-link);
      text-decoration: none;
    }

    a:hover {
      color: var(--comp-breadcrumb-text-linkHover);
    }

    .current {
      color: var(--comp-breadcrumb-text-current);
      font-weight: var(--sys-typography-label-fontWeight);
    }

    .sep {
      display: inline-flex;
      color: var(--comp-breadcrumb-separator);
    }
  `;

  /** Trail from root → current. */
  @property({ attribute: false }) items: GhBreadcrumbItem[] = [];
  /** Accessible name for the nav landmark. */
  @property({ type: String }) label = 'Breadcrumb';

  private select(item: GhBreadcrumbItem, index: number): void {
    this.dispatchEvent(
      new CustomEvent('select', { detail: { item, index }, bubbles: true, composed: true }),
    );
  }

  protected override render(): unknown {
    const last = this.items.length - 1;
    return html`<nav aria-label=${this.label}>
      <ol>
        ${this.items.map((item, index) => {
          const isLast = index === last;
          return html`<li>
            ${
              isLast || item.href === undefined
                ? html`<span
                    class=${isLast ? 'current' : ''}
                    aria-current=${isLast ? 'page' : nothing}
                    >${item.label}</span
                  >`
                : html`<a href=${item.href} @click=${() => this.select(item, index)}
                    >${item.label}</a
                  >`
            }
            ${
              isLast
                ? nothing
                : html`<span class="sep" aria-hidden="true"
                    ><gh-icon name="chevron-right" size="sm"></gh-icon
                  ></span>`
            }
          </li>`;
        })}
      </ol>
    </nav>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-breadcrumb': GhBreadcrumb;
  }
}

// packages/react-native/src/components/Breadcrumb.tsx
import { useTheme } from '@shopify/restyle';
import { Box, Text } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';
import { Icon } from './Icon.js';

/** One entry in a {@link Breadcrumb} trail. */
export interface BreadcrumbItem {
  /** Visible label. */
  label: string;
  /** Link target (web parity). On React Native, use `onSelect` to navigate. */
  href?: string;
}

/** Props for {@link Breadcrumb}. */
export interface BreadcrumbProps {
  /** Trail from root → current. The last item is the current page. */
  items: BreadcrumbItem[];
  /** Accessible name for the nav landmark. Defaults to `'Breadcrumb'`. */
  label?: string;
  /** Fired when a non-current item is pressed. */
  onSelect?: (item: BreadcrumbItem, index: number) => void;
  /** Test handle for queries. */
  testID?: string;
}

/**
 * A breadcrumb navigation trail. Renders a horizontal row of links separated by
 * hand-drawn chevrons; the last item is the current page. Colours and typography
 * come from `@ghds/tokens` via the Restyle theme (`comp.breadcrumb.*`). React
 * Native has no `href`, so navigation is delegated to the `onSelect` callback.
 */
export function Breadcrumb({ items, label = 'Breadcrumb', onSelect, testID }: BreadcrumbProps) {
  const theme = useTheme<Theme>();
  const last = items.length - 1;

  return (
    <Box
      flexDirection="row"
      flexWrap="wrap"
      alignItems="center"
      role="navigation"
      accessibilityLabel={label}
      testID={testID}
    >
      {items.map((item, index) => {
        const isLast = index === last;
        return (
          // biome-ignore lint/suspicious/noArrayIndexKey: breadcrumb items are a positional, ordered trail
          <Box key={index} flexDirection="row" alignItems="center">
            {isLast ? (
              // Current page: emphasised (label weight) + marked selected, matching
              // the aria-current="page" the web platforms set.
              <Text
                variant="body"
                color="breadcrumbTextCurrent"
                fontWeight={theme.textVariants.label.fontWeight}
                accessibilityRole="text"
                accessibilityState={{ selected: true }}
              >
                {item.label}
              </Text>
            ) : item.href === undefined ? (
              <Text variant="body" color="breadcrumbTextCurrent" accessibilityRole="text">
                {item.label}
              </Text>
            ) : (
              <Text
                variant="body"
                color="breadcrumbTextLink"
                accessibilityRole="link"
                onPress={() => onSelect?.(item, index)}
              >
                {item.label}
              </Text>
            )}
            {!isLast && (
              <Box paddingHorizontal="xs">
                <Icon name="chevron-right" size="sm" color={theme.colors.breadcrumbSeparator} />
              </Box>
            )}
          </Box>
        );
      })}
    </Box>
  );
}
