// packages/web-components/src/components/input-group.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/**
 * `<gh-input-group>` — a hand-drawn field that wraps addons (icons, text,
 * buttons) and a bare `<input>` / `<gh-*>` control inside a single sketchy box.
 *
 * The box is a sketchy rectangle outline from `@ghds/sketch-core` drawn over a
 * token-driven solid background. The outline stroke uses `currentColor`: the
 * host resolves it to `comp.inputGroup.stroke.default`, switches to the focus
 * colour on `:focus-within`, and to the danger colour when `invalid`. When
 * `disabled` the surface mutes to the disabled background. Every colour,
 * padding, radius and sketch parameter comes from `comp.inputGroup.*` tokens.
 */
@customElement('gh-input-group')
export class GhInputGroup extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-inputGroup-stroke-default);
      }

      :host(:focus-within) {
        color: var(--comp-inputGroup-stroke-focus);
      }

      :host([invalid]) {
        color: var(--comp-inputGroup-stroke-danger);
      }

      .group {
        position: relative;
        display: flex;
        align-items: center;
        gap: var(--comp-inputGroup-gap);
        box-sizing: border-box;
        padding: var(--comp-inputGroup-padding-vertical) var(--comp-inputGroup-padding-horizontal);
        background: var(--comp-inputGroup-bg-default);
        border-radius: var(--comp-inputGroup-radius);
        font-family: var(--sys-typography-body-fontFamily);
        font-size: var(--sys-typography-body-fontSize);
        font-weight: var(--sys-typography-body-fontWeight);
        line-height: var(--sys-typography-body-lineHeight);
        color: var(--comp-inputGroup-text-value);
      }

      :host([disabled]) .group {
        background: var(--comp-inputGroup-bg-disabled);
      }

      .body {
        position: relative;
        display: flex;
        align-items: center;
        gap: var(--comp-inputGroup-gap);
        flex: 1;
        min-width: 0;
      }

      /* A bare input placed in the group loses its own chrome — the group
         paints the box. */
      ::slotted(input) {
        flex: 1;
        min-width: 0;
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        border: none;
        outline: none;
        background: transparent;
        color: var(--comp-inputGroup-text-value);
        font-family: inherit;
        font-size: inherit;
        font-weight: inherit;
        line-height: inherit;
      }
    `,
  ];

  /** Disables the whole group and mutes the surface. */
  @property({ type: Boolean, reflect: true }) disabled = false;
  /** Marks the group invalid, painting the danger stroke. */
  @property({ type: Boolean, reflect: true }) invalid = false;

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.inputGroup.sketch.roughness,
      bowing: tokens.comp.inputGroup.sketch.bowing,
    };
  }

  protected override render(): unknown {
    return html`<div class="group" part="group">
      ${this.renderSketch()}
      <div class="body">
        <slot></slot>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-input-group': GhInputGroup;
  }
}

// packages/react-native/src/components/InputGroup.tsx
import { useTheme } from '@shopify/restyle';
import { createContext, type ReactNode, useContext, useState } from 'react';
import { TextInput, type TextInputProps } from 'react-native';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box, Text } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';

interface InputGroupContextValue {
  /** Whether the whole group (and thus its input) is disabled. */
  disabled: boolean;
  /** Lifts focus state from the inner input up to the group outline. */
  setFocused: (focused: boolean) => void;
}

const InputGroupContext = createContext<InputGroupContextValue>({
  disabled: false,
  setFocused: () => {},
});

/** Props for {@link InputGroup}. */
export interface InputGroupProps {
  /** Disables the whole group and mutes the surface. */
  disabled?: boolean;
  /** Marks the group invalid, painting the danger stroke. */
  invalid?: boolean;
  /** Group content — an {@link InputGroupInput} plus {@link InputGroupAddon}s. */
  children?: ReactNode;
  /** Test handle for queries. */
  testID?: string;
}

/**
 * A hand-drawn field that composes a bare {@link InputGroupInput} with leading
 * and/or trailing {@link InputGroupAddon}s (icons, text) inside a single
 * sketchy box. Focus within the group switches the outline to the focus
 * colour. Every colour, padding, radius and sketch parameter comes from
 * `@ghds/tokens` (`comp.inputGroup.*`) via the Restyle theme.
 */
export function InputGroup({
  disabled = false,
  invalid = false,
  children,
  testID,
}: InputGroupProps) {
  const theme = useTheme<Theme>();
  const [focused, setFocused] = useState(false);

  const { onLayout, size, drawable } = useSketch({
    inset: theme.borderWidths.default,
    roughness: theme.inputGroupSketch.roughness,
    bowing: theme.inputGroupSketch.bowing,
    fillStyle: 'solid',
  });

  let strokeColor: string;
  if (invalid) {
    strokeColor = theme.colors.inputGroupStrokeDanger;
  } else if (focused && !disabled) {
    strokeColor = theme.colors.inputGroupStrokeFocus;
  } else {
    strokeColor = theme.colors.inputGroupStrokeDefault;
  }

  const fillColor = disabled ? theme.colors.inputGroupBgDisabled : theme.colors.inputGroupBgDefault;

  return (
    <InputGroupContext.Provider value={{ disabled, setFocused }}>
      <Box
        onLayout={onLayout}
        flexDirection="row"
        alignItems="center"
        gap="inputGroupGap"
        paddingHorizontal="inputGroupHorizontal"
        paddingVertical="inputGroupVertical"
        borderRadius="inputGroup"
        testID={testID}
      >
        <SketchBackground
          drawable={drawable}
          size={size}
          strokeColor={strokeColor}
          fillColor={fillColor}
          strokeWidth={theme.borderWidths.default}
        />
        {children}
      </Box>
    </InputGroupContext.Provider>
  );
}

/** Props for {@link InputGroupInput}. */
export interface InputGroupInputProps
  extends Omit<TextInputProps, 'editable' | 'onFocus' | 'onBlur'> {
  /** Explicit disabled override; otherwise inherited from the group. */
  disabled?: boolean;
}

/** The bare, borderless text input placed inside an {@link InputGroup}. */
export function InputGroupInput({ disabled, style, ...rest }: InputGroupInputProps) {
  const theme = useTheme<Theme>();
  const { disabled: groupDisabled, setFocused } = useContext(InputGroupContext);
  const isDisabled = disabled ?? groupDisabled;

  return (
    <TextInput
      editable={!isDisabled}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      placeholderTextColor={theme.colors.inputGroupTextDisabled}
      style={[
        {
          flex: 1,
          minWidth: 0,
          padding: 0,
          backgroundColor: 'transparent',
          color: isDisabled
            ? theme.colors.inputGroupTextDisabled
            : theme.colors.inputGroupTextValue,
          fontFamily: theme.textVariants.body.fontFamily,
          fontSize: theme.textVariants.body.fontSize,
        },
        style,
      ]}
      {...rest}
    />
  );
}

/**
 * A leading or trailing addon slot inside an {@link InputGroup} — an icon or
 * short text. Rendered in the muted addon text colour; place it before or after
 * {@link InputGroupInput} in the child order to position it.
 */
export function InputGroupAddon({ children }: { children?: ReactNode }) {
  return (
    <Box flexDirection="row" alignItems="center" gap="xs" flexShrink={0}>
      {typeof children === 'string' ? (
        <Text variant="label" color="inputGroupAddonText">
          {children}
        </Text>
      ) : (
        children
      )}
    </Box>
  );
}
