// packages/web-components/src/components/progress.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { rectangle } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html, nothing, svg } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

const INSET = Number.parseFloat(tokens.sys.border.width.default);
/** Width fraction of the sweeping segment while indeterminate. */
const INDETERMINATE_FRACTION = 0.4;

/**
 * `<gh-progress>` — a hand-drawn progress bar.
 *
 * The rail and fill are sketchy rectangles (`@ghds/sketch-core`); colours,
 * height and sketch parameters are token-driven (`comp.progress.*`). Set `value`
 * for a determinate bar or leave it unset for an indeterminate sweep
 * (suppressed under `prefers-reduced-motion: reduce`). Exposed as
 * `role="progressbar"` with the appropriate `aria-value*`.
 */
@customElement('gh-progress')
export class GhProgress extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: block;
        width: 100%;
      }

      .track {
        position: relative;
        box-sizing: border-box;
        width: 100%;
        height: var(--comp-progress-track-height);
        border-radius: var(--comp-progress-radius);
        overflow: hidden;
      }

      .fill {
        position: absolute;
        top: 0;
        left: 0;
        height: 100%;
        border-radius: var(--comp-progress-radius);
        overflow: hidden;
      }

      .fill.indeterminate {
        width: 40%;
        animation: gh-progress-sweep calc(var(--comp-progress-duration) * 3) ease-in-out infinite;
      }

      @keyframes gh-progress-sweep {
        from {
          transform: translateX(-100%);
        }
        to {
          transform: translateX(250%);
        }
      }

      @media (prefers-reduced-motion: reduce) {
        .fill.indeterminate {
          animation: none;
        }
      }

      svg {
        position: absolute;
        inset: 0;
        overflow: visible;
        pointer-events: none;
      }

      .rail-fill {
        fill: var(--comp-progress-bg-rail);
      }

      .rail-stroke {
        fill: none;
        stroke: var(--comp-progress-stroke-rail);
        stroke-width: var(--sys-border-width-default);
        stroke-linecap: round;
        stroke-linejoin: round;
      }

      .bar-fill {
        fill: var(--comp-progress-bg-fill);
      }

      .bar-stroke {
        fill: none;
        stroke: var(--comp-progress-stroke-fill);
        stroke-width: var(--sys-border-width-default);
        stroke-linecap: round;
        stroke-linejoin: round;
      }
    `,
  ];

  /** Current value. Leave unset for an indeterminate bar. */
  @property({ type: Number }) value?: number;
  /** Maximum value. */
  @property({ type: Number }) max = 100;
  /** Accessible label describing what is progressing. */
  @property({ type: String }) label = '';

  private get indeterminate(): boolean {
    return this.value === undefined || this.value === null || Number.isNaN(this.value);
  }

  private get fraction(): number {
    if (this.indeterminate) {
      return INDETERMINATE_FRACTION;
    }
    return Math.min(1, Math.max(0, (this.value ?? 0) / this.max));
  }

  protected override updated(): void {
    this.setAttribute('role', 'progressbar');
    if (this.label) {
      this.setAttribute('aria-label', this.label);
    } else {
      this.removeAttribute('aria-label');
    }
    if (this.indeterminate) {
      this.removeAttribute('aria-valuenow');
      this.removeAttribute('aria-valuemin');
      this.removeAttribute('aria-valuemax');
    } else {
      this.setAttribute('aria-valuemin', '0');
      this.setAttribute('aria-valuemax', String(this.max));
      this.setAttribute('aria-valuenow', String(this.value));
    }
  }

  // Required by SketchyBase; unused because `render()` draws two layers directly.
  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return rectangle(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.progress.sketch.roughness,
      bowing: tokens.comp.progress.sketch.bowing,
      fillStyle: 'solid',
    };
  }

  private renderLayer(width: number, height: number, fillClass: string, strokeClass: string) {
    if (width <= 0 || height <= 0) {
      return nothing;
    }
    const drawable = rectangle(
      INSET,
      INSET,
      Math.max(1, width - INSET * 2),
      Math.max(1, height - INSET * 2),
      { ...this.sketchParams(), seed: this.effectiveSeed },
    );
    return html`<svg
      width=${width}
      height=${height}
      viewBox="0 0 ${width} ${height}"
      aria-hidden="true"
      focusable="false"
    >
      ${drawable.fillPaths.map((d) => svg`<path class=${fillClass} d=${d} fill-rule="evenodd"></path>`)}
      ${drawable.strokePaths.map((d) => svg`<path class=${strokeClass} d=${d}></path>`)}
    </svg>`;
  }

  protected override render(): unknown {
    const width = this.sketchWidth;
    const height = this.sketchHeight;
    const fillWidth = width * this.fraction;
    return html`<div class="track" part="track">
      ${this.renderLayer(width, height, 'rail-fill', 'rail-stroke')}
      <div
        class=${this.indeterminate ? 'fill indeterminate' : 'fill'}
        style=${this.indeterminate ? nothing : `width: ${this.fraction * 100}%`}
      >
        ${this.renderLayer(fillWidth, height, 'bar-fill', 'bar-stroke')}
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-progress': GhProgress;
  }
}

// packages/react-native/src/components/Progress.tsx
import { useTheme } from '@shopify/restyle';
import { useRef, useState } from 'react';
import { Animated, Easing, type LayoutChangeEvent, View } from 'react-native';
import { useReducedMotionLoop } from '../motion.js';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';

/** Props for {@link Progress}. */
export interface ProgressProps {
  /** Current value. Omit for an indeterminate bar. */
  value?: number;
  /** Maximum value. Defaults to `100`. */
  max?: number;
  /** Accessible label describing what is progressing. */
  label?: string;
  /** Test handle for queries. */
  testID?: string;
}

const INDETERMINATE_FRACTION = 0.4;

/**
 * A hand-drawn progress bar. The rail and fill are solid, token-driven surfaces
 * with a sketchy outline from `@ghds/sketch-core` (rendered with
 * `react-native-svg`); every colour, height and sketch parameter is sourced
 * from `@ghds/tokens` via the Restyle theme (`comp.progress.*`). Pass a `value`
 * for a determinate bar, or omit it for an indeterminate sweep (suppressed when
 * the OS "reduce motion" setting is on).
 */
export function Progress({ value, max = 100, label, testID }: ProgressProps) {
  const theme = useTheme<Theme>();
  const indeterminate = value === undefined;
  const fraction = indeterminate ? INDETERMINATE_FRACTION : Math.min(1, Math.max(0, value / max));

  const sweep = useRef(new Animated.Value(0)).current;
  const [trackWidth, setTrackWidth] = useState(0);

  const {
    onLayout: railLayout,
    size: railSize,
    drawable: railDrawable,
  } = useSketch({
    inset: theme.borderWidths.default,
    roughness: theme.progressSketch.roughness,
    bowing: theme.progressSketch.bowing,
  });

  const {
    onLayout: fillLayout,
    size: fillSize,
    drawable: fillDrawable,
  } = useSketch({
    inset: theme.borderWidths.default,
    roughness: theme.progressSketch.roughness,
    bowing: theme.progressSketch.bowing,
  });

  const duration = theme.progressDuration;

  useReducedMotionLoop(
    () =>
      Animated.loop(
        Animated.timing(sweep, {
          toValue: 1,
          duration: duration * 3,
          easing: Easing.inOut(Easing.ease),
          useNativeDriver: true,
        }),
      ),
    [duration, sweep],
    indeterminate,
  );

  const handleTrackLayout = (event: LayoutChangeEvent) => {
    setTrackWidth(event.nativeEvent.layout.width);
    railLayout(event);
  };

  const height = theme.progressTrackHeight;
  const radius = height / 2;
  const fillWidth = trackWidth * fraction;
  const translateX = sweep.interpolate({
    inputRange: [0, 1],
    outputRange: [-fillWidth, trackWidth + fillWidth],
  });

  return (
    <Box
      onLayout={handleTrackLayout}
      backgroundColor="progressBgRail"
      style={{ width: '100%', height, borderRadius: radius, overflow: 'hidden' }}
      testID={testID}
      accessibilityRole="progressbar"
      accessibilityLabel={label}
      // `accessibilityValue` drives native VoiceOver/TalkBack; react-native-web
      // does not forward the nested object, so the flat `aria-value*` props are
      // set for the web target (same gap class as Slider/Select — [[ghds-rnw-prop-gaps]]).
      accessibilityValue={indeterminate ? undefined : { min: 0, max, now: value }}
      aria-valuemin={indeterminate ? undefined : 0}
      aria-valuemax={indeterminate ? undefined : max}
      aria-valuenow={indeterminate ? undefined : value}
    >
      <SketchBackground
        drawable={railDrawable}
        size={railSize}
        strokeColor={theme.colors.progressStrokeRail}
        strokeWidth={theme.borderWidths.default}
      />
      <Animated.View
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          height: '100%',
          width: indeterminate ? `${INDETERMINATE_FRACTION * 100}%` : `${fraction * 100}%`,
          borderRadius: radius,
          overflow: 'hidden',
          backgroundColor: theme.colors.progressBgFill,
          transform: indeterminate ? [{ translateX }] : [],
        }}
      >
        <View onLayout={fillLayout} style={{ width: '100%', height: '100%' }}>
          <SketchBackground
            drawable={fillDrawable}
            size={fillSize}
            strokeColor={theme.colors.progressStrokeFill}
            strokeWidth={theme.borderWidths.default}
          />
        </View>
      </Animated.View>
    </Box>
  );
}
