// packages/web-components/src/components/spinner.ts
import type { SketchDrawable, SketchOptions } from '@ghds/sketch-core';
import { ellipse } from '@ghds/sketch-core';
import { tokens } from '@ghds/tokens';
import { css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { type SketchParams, SketchyBase } from '../sketchy-base.js';

/** Rendered diameter of a `<gh-spinner>`. */
export type GhSpinnerSize = 'sm' | 'md' | 'lg';

/**
 * `<gh-spinner>` — a hand-drawn loading spinner.
 *
 * A sketchy ellipse ring (`@ghds/sketch-core`) that rotates; the wobble of the
 * hand-drawn outline makes the spin legible. Colour, size and the spin duration
 * are token-driven (`comp.spinner.*`). Rotation is suppressed under
 * `prefers-reduced-motion: reduce`. Exposed as `role="status"` with a label.
 */
@customElement('gh-spinner')
export class GhSpinner extends SketchyBase {
  static override styles = [
    SketchyBase.sketchStyles,
    css`
      :host {
        display: inline-block;
        --_spinner-size: var(--comp-spinner-size-md);
        width: var(--_spinner-size);
        height: var(--_spinner-size);
        /* Drives the sketch stroke (currentColor). */
        color: var(--comp-spinner-indicator);
      }

      :host([size='sm']) {
        --_spinner-size: var(--comp-spinner-size-sm);
      }

      :host([size='lg']) {
        --_spinner-size: var(--comp-spinner-size-lg);
      }

      .spinner {
        position: relative;
        width: 100%;
        height: 100%;
        animation: gh-spin var(--comp-spinner-duration) linear infinite;
      }

      @keyframes gh-spin {
        to {
          transform: rotate(360deg);
        }
      }

      @media (prefers-reduced-motion: reduce) {
        .spinner {
          animation: none;
        }
      }
    `,
  ];

  /** Rendered diameter. */
  @property({ type: String, reflect: true }) size: GhSpinnerSize = 'md';
  /** Accessible label for the busy state. */
  @property({ type: String }) label = 'Loading';

  private readonly internals: ElementInternals = this.attachInternals();

  override connectedCallback(): void {
    super.connectedCallback();
    this.internals.role = 'status';
  }

  protected override updated(): void {
    this.internals.ariaLabel = this.label;
  }

  protected override sketch(width: number, height: number, options: SketchOptions): SketchDrawable {
    return ellipse(0, 0, width, height, options);
  }

  protected override sketchParams(): SketchParams {
    return {
      roughness: tokens.comp.spinner.sketch.roughness,
      bowing: tokens.comp.spinner.sketch.bowing,
    };
  }

  protected override render(): unknown {
    return html`<span class="spinner" part="spinner">${this.renderSketch()}</span>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'gh-spinner': GhSpinner;
  }
}

// packages/react-native/src/components/Spinner.tsx
import { useTheme } from '@shopify/restyle';
import { useRef } from 'react';
import { Animated, Easing } from 'react-native';
import { useReducedMotionLoop } from '../motion.js';
import { SketchBackground } from '../sketch/SketchBackground.js';
import { useSketch } from '../sketch/useSketch.js';
import { Box } from '../theme/primitives.js';
import type { Theme } from '../theme/theme.js';

/** Rendered diameter of a {@link Spinner}. */
export type SpinnerSize = 'sm' | 'md' | 'lg';

/** Props for {@link Spinner}. */
export interface SpinnerProps {
  /** Rendered diameter. Defaults to `'md'`. */
  size?: SpinnerSize;
  /** Accessible label for the busy state. Defaults to `'Loading'`. */
  label?: string;
  /** Test handle for queries. */
  testID?: string;
}

const FULL: ['0deg', '360deg'] = ['0deg', '360deg'];

/**
 * A hand-drawn loading spinner: a sketchy ellipse ring (`@ghds/sketch-core`,
 * rendered with `react-native-svg`) that rotates via the `Animated` API. The
 * wobble of the hand-drawn outline makes the spin legible. Colour, size and the
 * spin duration come from `@ghds/tokens` via the Restyle theme
 * (`comp.spinner.*`). Rotation is suppressed when the OS "reduce motion"
 * setting is on.
 */
export function Spinner({ size = 'md', label = 'Loading', testID }: SpinnerProps) {
  const theme = useTheme<Theme>();
  const rotation = useRef(new Animated.Value(0)).current;

  const {
    onLayout,
    size: measured,
    drawable,
  } = useSketch({
    shape: 'ellipse',
    inset: theme.borderWidths.default,
    roughness: theme.spinnerSketch.roughness,
    bowing: theme.spinnerSketch.bowing,
  });

  const duration = theme.spinnerDuration;

  useReducedMotionLoop(
    () =>
      Animated.loop(
        Animated.timing(rotation, {
          toValue: 1,
          duration,
          easing: Easing.linear,
          useNativeDriver: true,
        }),
      ),
    [rotation, duration],
  );

  const dimension = theme.spinnerSizes[size];
  const rotate = rotation.interpolate({ inputRange: [0, 1], outputRange: FULL });

  return (
    <Box
      onLayout={onLayout}
      style={{ width: dimension, height: dimension }}
      testID={testID}
      accessibilityLabel={label}
      // `accessibilityState` drives native; react-native-web does not forward it,
      // so `role="status"` + `aria-busy` are set for the web target to match the
      // React/Web-Component Spinners' `role="status"` ([[ghds-rnw-prop-gaps]]).
      accessibilityState={{ busy: true }}
      role="status"
      aria-busy={true}
    >
      <Animated.View style={{ width: '100%', height: '100%', transform: [{ rotate }] }}>
        <SketchBackground
          drawable={drawable}
          size={measured}
          strokeColor={theme.colors.spinnerIndicator}
          strokeWidth={theme.borderWidths.default}
        />
      </Animated.View>
    </Box>
  );
}
